### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by gai-chengpeng** [facebookresearch/SlowFast#101]
This error occurred at run time. Step by step debugging found that it was build_model `model = model.cuda(device=cur_device)` error in model_builder.py file. And `torch.cuda.is_available()` is True
.Where did I do it wrong.
> python tools/run_net.py --cfg /mnt/project2/my/slowfast/configs/Kinetics/SLOWFAST_8x8_R50.yaml DATA.PATH_TO_DATA_DIR /mnt/project2/my/data TEST.CHECKPOINT_FILE_PATH /mnt/project2/my/SLOWFAST_8x8_R50.pkl TRAIN.ENABLE False NUM_GPUS 1 MODEL.ARCH slowfast
[INFO: test_net.py:  122]: Test with config:
[INFO: test_net.py:  123]: AVA:
  ANNOTATION_DIR: /mnt/vol/gfsai-flash3-east/ai-group/users/haoqifan/ava/frame_list/
  BGR: False
  DETECTION_SCORE_THRESH: 0.9
  EXCLUSION_FILE: ava_val_excluded_timestamps_v2.2.csv
  FRAME_DIR: /mnt/fair-flash3-east/ava_trainval_frames.img/
  FRAME_LIST_DIR: /mnt/vol/gfsai-flash3-east/ai-group/users/haoqifan/ava/frame_list/
  FULL_TEST_ON_VAL: False
  GROUNDTRUTH_FILE: ava_val_v2.2.csv
  IMG_PROC_BACKEND: cv2
  LABEL_MAP_FILE: ava_action_list_v2.2_for_activitynet_2019.pbtxt
  TEST_FORCE_FLIP: False
  TEST_LISTS: ['val.csv']
  TEST_PREDICT_BOX_LISTS: ['ava_val_predicted_boxes.csv']
  TRAIN_GT_BOX_LISTS: ['ava_train_v2.2.csv']
  TRAIN_LISTS: ['train.csv']
  TRAIN_PCA_EIGVAL: [0.225, 0.224, 0.229]
  TRAIN_PCA_EIGVEC: [[-0.5675, 0.7192, 0.4009], [-0.5808, -0.0045, -0.814], [-0.5836, -0.6948, 0.4203]]
  TRAIN_PCA_JITTER_ONLY: True
  TRAIN_PREDICT_BOX_LISTS: []
  TRAIN_USE_COLOR_AUGMENTATION: False
BN:
  EPSILON: 1e-05
  MOMENTUM: 0.1
  NUM_BATCHES_PRECISE: 200
  USE_PRECISE_STATS: True
  WEIGHT_DECAY: 0.0
DATA:
  CROP_SIZE: 224
  INPUT_CHANNEL_NUM: [3, 3]
  MEAN: [0.45, 0.45, 0.45]
  NUM_FRAMES: 32
  PATH_PREFIX: 
  PATH_TO_DATA_DIR: /mnt/project2/my/data
  SAMPLING_RATE: 2
  STD: [0.225, 0.225, 0.225]
  TEST_CROP_SIZE: 256
  TRAIN_CROP_SIZE: 224
  TRAIN_JITTER_SCALES: [256, 320]
DATA_LOADER:
  ENABLE_MULTI_THREAD_DECODE: False
  NUM_WORKERS: 8
  PIN_MEMORY: True
DETECTION:
  ALIGNED: True
  ENABLE: False
  ROI_XFORM_RESOLUTION: 7
  SPATIAL_SCALE_FACTOR: 16
DIST_BACKEND: nccl
LOG_PERIOD: 10
MODEL:
  ARCH: slowfast
  DROPOUT_RATE: 0.5
  FC_INIT_STD: 0.01
  LOSS_FUNC: cross_entropy
  MULTI_PATHWAY_ARCH: ['slowfast']
  NUM_CLASSES: 400
  SINGLE_PATHWAY_ARCH: ['c2d', 'i3d', 'slowonly']
NONLOCAL:
  GROUP: [[1, 1], [1, 1], [1, 1], [1, 1]]
  INSTANTIATION: dot_product
  LOCATION: [[[], []], [[], []], [[], []], [[], []]]
  POOL: [[[1, 2, 2], [1, 2, 2]], [[1, 2, 2], [1, 2, 2]], [[1, 2, 2], [1, 2, 2]], [[1, 2, 2], [1, 2, 2]]]
NUM_GPUS: 1
NUM_SHARDS: 1
OUTPUT_DIR: .
RESNET:
  DEPTH: 50
  INPLACE_RELU: True
  NUM_BLOCK_TEMP_KERNEL: [[3, 3], [4, 4], [6, 6], [3, 3]]
  NUM_GROUPS: 1
  SPATIAL_DILATIONS: [[1, 1], [1, 1], [1, 1], [1, 1]]
  SPATIAL_STRIDES: [[1, 1], [2, 2], [2, 2], [2, 2]]
  STRIDE_1X1: False
  TRANS_FUNC: bottleneck_transform
  WIDTH_PER_GROUP: 64
  ZERO_INIT_FINAL_BN: True
RNG_SEED: 0
SHARD_ID: 0
SLOWFAST:
  ALPHA: 4
  BETA_INV: 8
  FUSION_CONV_CHANNEL_RATIO: 2
  FUSION_KERNEL_SZ: 7
SOLVER:
  BASE_LR: 0.1
  DAMPENING: 0.0
  GAMMA: 0.1
  LRS: []
  LR_POLICY: cosine
  MAX_EPOCH: 196
  MOMENTUM: 0.9
  NESTEROV: True
  OPTIMIZING_METHOD: sgd
  STEPS: []
  STEP_SIZE: 1
  WARMUP_EPOCHS: 34
  WARMUP_FACTOR: 0.1
  WARMUP_START_LR: 0.01
  WEIGHT_DECAY: 0.0001
TEST:
  BATCH_SIZE: 64
  CHECKPOINT_FILE_PATH: /mnt/project2/my/SLOWFAST_8x8_R50.pkl
  CHECKPOINT_TYPE: pytorch
  DATASET: kinetics
  ENABLE: True
  NUM_ENSEMBLE_VIEWS: 10
  NUM_SPATIAL_CROPS: 3
TRAIN:
  AUTO_RESUME: True
  BATCH_SIZE: 64
  CHECKPOINT_FILE_PATH: 
  CHECKPOINT_INFLATE: False
  CHECKPOINT_PERIOD: 1
  CHECKPOINT_TYPE: pytorch
  DATASET: kinetics
  ENABLE: False
  EVAL_PERIOD: 10
Segmentation fault (core dumped)

**Comment by takatosp1** [comment]
Hi
Thanks for playing with PySlowFast.
Looks your PyTorch was not properly installed, you might want to re-install PyTorch. (Seems there is something wrong with the mul_ or add_ op).
I feel re-install CUDA and then re-install PyTorch would fix this problem.

Feel free to share your update here :P
