### ISSUE TITLE
Cuda Error

### ISSUE THREAD

**Issue by rahul4tripathi2** [facebookresearch/SlowFast#104]
can anyone please share the parameter to tune in AVA config folder to run all AVA model in single GPU machine

Error - Cuda run out of memory 

tried reducing the batch size in all ava model but none works. Please suggest any way to solve cuda run out of memory.

**Comment by UNdedss** [comment]
Same issue for me. 

`RuntimeError: CUDA out of memory. Tried to allocate 32.00 MiB (GPU 0; 1.95 GiB total capacity; 566.34 MiB already allocated; 12.31 MiB free; 580.00 MiB reserved in total by PyTorch)`

So another question - what are the minimum system/GPU requirements for training and inference?

**Comment by takatosp1** [comment]
Hi,
Thanks for playing with PySlowFast :P 
It looks your GPU does not have enough memory to load the model with 8 batches. You might want to use a smaller NUM_GPUS and BATCH_SIZE, then it should help you fix the issue you got.

Feel free to share any update here :P
