### ISSUE TITLE
Is it an error in "checkpoint.py"?

### ISSUE THREAD

**Issue by Andy1621** [facebookresearch/SlowFast#108]
```python
        # Load the checkpoint on CPU to avoid GPU mem spike.
        checkpoint = torch.load(path_to_checkpoint, map_location="cpu")
        if inflation:
            # Try to inflate the model.
            model_state_dict_3d = (
                model.module.state_dict()
                if data_parallel
                else model.state_dict()
            )
            inflated_model_dict = inflate_weight(
                checkpoint["model_state"], model_state_dict_3d
            )
            ms.load_state_dict(inflated_model_dict, strict=False)
        else:
            ms.load_state_dict(checkpoint["model_state"])
            # Load the optimizer state (commonly not done when fine-tuning)
            if optimizer:
                optimizer.load_state_dict(checkpoint["optimizer_state"])
        if "epoch" in checkpoint.keys():
            epoch = checkpoint["epoch"]
        else:
            epoch = -1
```
https://github.com/facebookresearch/SlowFast/blob/b2cfb459efbab80a01b448e2ea13b5bdac76930b/slowfast/utils/checkpoint.py#L235
I think the optimizer should also be reloaded while inflating the weights, is it an error?

**Comment by takatosp1** [comment]
Hi,

Thanks for playing with PySlowFast!
If the inflated is used, then it means the pretrain model was trained on other 2D datasets (e.g., ImageNet), which is different to the current 3D datasets (Kinetics for example) used for training, then the optimizer’s stats are not supposed to be loaded.

However you could try to play with it, I guess it would not make a big difference.

**Comment by Andy1621** [comment]
Thanks for your patience~
