### ISSUE TITLE
No torch.no_grad() in test_net.py ?

### ISSUE THREAD

**Issue by vhvkhoa** [facebookresearch/SlowFast#109]
I am trying to test the pretrained model on my own dataset. I figured out that I can only run with tremendously limited parameters e.g. ```TEST.NUM_SPATIAL_CROP = 1``` and ```TEST.NUM_ENSEMBLE_VIEWS = 1```. After reading the code I noticed that there are two problems which lead to the above outcome:
1. I did not rescale my video size to 256 for the shortest side of height and width.
2. The code does not use ```with torch.no_grad()``` before the prediction code block in ```perform_test``` in test_net.py. After adding it to the code, I see that the GPU memory consumption is extremely decreased.

So I am wondering if it is okay to use ```torch.no_grad()``` ?

**Comment by feichtenhofer** [comment]
This is a great point, yes, it is okay to use it for memory conservation during inference!
