### ISSUE TITLE
Why do we have to feed in bboxes in the forward pass for action detection? Isn't that part of the output?

### ISSUE THREAD

**Issue by thesofakillers** [facebookresearch/SlowFast#114]
Hi, thank you very much for your research effort and this repository.

I am interested in producing AVA-like output for a given input video, i.e. an array of the following:

`frame number`, `person_box` (top-left (x1, y1) and bottom-right (x2,y2)),  `action_id`, `person_id`

I thought I could pass an array of the frames of the video into a model instantiated with `build_model` and a cfg where DETECTION.ENABLE = True.

However, in [video_model_builder.py](https://github.com/facebookresearch/SlowFast/blob/master/slowfast/models/video_model_builder.py), I see that with detection enabled, we need to also pass bounding boxes as input to the model:
https://github.com/facebookresearch/SlowFast/blob/6ff9dd9cdd0c0ed5a88a2c220bdf389d02b3ba97/slowfast/models/video_model_builder.py#L374-L375

This confuses me because I thought we would obtain bounding boxes for the detected actions on a given frame.

Do we simply pass an empty array? Am I missing something very obvious?

I had a look at @anhminh3105's demo and I see in [demo_net.py](https://github.com/anhminh3105/SlowFast/blob/master/tools/demo_net.py) they obtain bounding boxes by running the frames through Detectron2 DefaultPredictor first. They also manually sample the frames for the fast and slow pathway. If this is the correct process, why isn't it done in [test_net.py](https://github.com/facebookresearch/SlowFast/blob/master/tools/test_net.py)? Does `construct_loader` take care of these steps in [loader.py](https://github.com/facebookresearch/SlowFast/blob/master/slowfast/datasets/loader.py)?

In @anhminh3105's demo aswell as the [ava_demo.gif](https://github.com/facebookresearch/SlowFast/blob/master/demo/ava_demo.gif), I've also noticed that the bounding boxes are only relevant to specific single frames, i.e. they do not update frame-by-frame. Is this a natural consequence of the two stream SlowFast architecture? Is SlowFast not capable of per-frame action detection? 

Apologies for the many questions, I've had trouble navigating this codebase and fully grasping the paper. 

Thank you very much for your time and help!

**Comment by anhminh3105** [comment]
Hi @thesofakillers .

As stated from the paper itself, slowfast uses an independent person detector to propose bounding boxes in each frame and they used detectron’s module to ease the work and focus only focus on slowfast.

You may think of slowfast as a classification module.

The construct_loader indeed does the preprocessing steps of the frames in the dataset.

To preserve the original ideas in the paper and to provide a demo accordingly similar to how results are displayed in the gif, bounding boxes of the middle frame in the frame sequence are used for display. You may innovate it how you like.

Slowfast can be used to process per frame basis but it would be computationally costly based on what I have observed and experienced with slowfast.

Hope these help.

Best regards.
Minh

**Comment by thesofakillers** [comment]
Hi @anhminh3105 

Thank you so much for the response! It is what I was beginning to understand since posting the issue. 
Thanks once again for all your work on the demo portion of the code, it has been of immense help.

**Comment by nikky4D** [comment]
Were you able to modifi

> Hi @anhminh3105
> 
> Thank you so much for the response! It is what I was beginning to understand since posting the issue.
> Thanks once again also for all your work on the demo portion of the code, it has been of immense help.

Were you able to modify the output with frame numbers? And get a per frame classification? I am stuck myself working on something similar to what you are doing
