### ISSUE TITLE
AssertionError: update_bn_stats is meant to run for 200 iterations, but the dataloader stops at 78 iterations.

### ISSUE THREAD

**Issue by leemengxing** [facebookresearch/SlowFast#117]
thanks your work! I train I3D_8*8_R50 on my own data, but got a error.how to debug it, can you give me nay suggestions?

**Comment by bqhuyy** [comment]
Hi, I meet the same error. Have you come up with the solution?

**Comment by d123456ddq** [comment]
You need to set BN.NUM_BATCHES_PRECISE <= 78（up to you datasets iterations）, also see slowfast/configs/defaults.py line 29 for details.
