### ISSUE TITLE
Run error

### ISSUE THREAD

**Issue by onlyonewater** [facebookresearch/SlowFast#119]
I use command     python ./tools/run_net.py --cfg ./configs/Kinetics/C2D_8x8_R50.yaml DATA.PATH_TO_DATA_DIR ~/data/kinetics400/ NUM_GPUS 2 TRAIN.BATCH_SIZE 16 to train a model,but it has some problems.

RuntimeError: Caught RuntimeError in DataLoader worker process 0
RuntimeError: Failed to fetch video after 10 retries

I am very confused.Thanks

**Comment by hengxiangYao** [comment]
Did you solve that? I encountered a similar error and I didn't use Kinetics dataset, I used my own dataset instead.
`File "/home/hyao8934/slowfast/slowfast/datasets/kinetics.py", line 212, in __getitem__
    raise RuntimeError(
RuntimeError: Failed to fetch video after 10 retries.

Segmentation fault (core dumped)`
That's the error message. And I used command
`python tools/run_net.py \--cfg configs/Kinetics/C2D_8x8_R50.yaml \DATA.PATH_TO_DATA_DIR /home2/share/clips \NUM_GPUS 1 \TRAIN.BATCH_SIZE 16`
How to solve that? Thanks

**Comment by onlyonewater** [comment]
Hi, @hengxiangYao ,I think in the data preparation, path_to_video should be the absolute path,eg,/home2/share/clips/xxxxx.mp4

**Comment by hengxiangYao** [comment]
@onlyonewater Thanks for the reply, it is solved after I change the absolute path.
btw, did you happen to meet error message saying "Failed to decode with pyav with exception: tuple index out of range" ? I met this while training, though the training process didn't terminate.

**Comment by onlyonewater** [comment]
oh,I think in the data preparation,the video should resize to the short edge size of 256,but I don't konw how to do it. If you solve it ,please tell  me.Thanks!!!

**Comment by pjw-cmd** [comment]
I had the same error, but when I changed to an absolute path, it showed that I couldn't find the train.csv file. How can I fix it?Thanks!
I use command python ./tools/run_net.py --cfg ./configs/Kinetics/C2D_8x8_R50.yaml DATA.PATH_TO_DATA_DIR ~/dataset/eating_hotdog/zzAi5HYDRdQ_000061_000071.mp4 NUM_GPUS 2 TRAIN.BATCH_SIZE 16.Error messae saying"AssertionError: /home/pjw/dataset/eating_hotdog/zzAi5HYDRdQ_000061_000071.mp4/train.csv dir not found
"

**Comment by onlyonewater** [comment]
I think the DATA.PATH_TO_DATA_DIR is ~dataset/   . In the train.csv ,the data dir should be the absolute path.

**Comment by pjw-cmd** [comment]
I modified command python ./tools/run_net.py --cfg ./configs/Kinetics/C2D_8x8_R50.yaml DATA.PATH_TO_DATA_DIR ~/dataset NUM_GPUS 2 TRAIN.BATCH_SIZE 16.Error messae saying"RuntimeError: Failed to fetch video after 10 retries.".Is there a problem with the train.csv file I created? , My train.csv file format is two columns, the first column is youtube_id (example "/home/pjw/dataset/eating_hotdog/07dVkTTGXv4.mp4"), and the second column is  eating_hotdog.

**Comment by onlyonewater** [comment]
oh,Sorry, I don't konw, I think your second colunmn should be the number of the label,you can get the classid.json from the following url :https://github.com/facebookresearch/video-nonlocal net/blob/master/process_data/kinetics/classids.json

**Comment by pjw-cmd** [comment]
This link doesn't open, the second column of my.csv file is the label, which is the same as the label name in kinetics-400_train.csv provided by author？I just downloaded the video in which Babel is in the eating_hotdog folder.It confused me for a long time.Thanks!

**Comment by onlyonewater** [comment]
Oh,Sorry,there is some wrong with the url,try this url again, [https://github.com/facebookresearch/video-nonlocal-net/blob/master/process_data/kinetics/classids.json](url)

**Comment by onlyonewater** [comment]
Oh,sorry,there is some wrong with the url,in google search,enter classids.json,you will find it at video-nonlocal-net Repository in github.

**Comment by pjw-cmd** [comment]
Thanks, I found it, but do I need to download this json file?Or is this json file related to the label of the second column of my train.csv file?

**Comment by onlyonewater** [comment]
Oh, I think you should download this json file . It is related to the label of the second column of the train.csv file , for example , replace eating_hotdog with the number of the json file .

**Comment by takatosp1** [comment]
Hi,
Thanks for playing with PySlowFast!
It seems the issue you reported is caused by an incorrect csv. You might want to follow the instruction from [here](https://github.com/facebookresearch/SlowFast/blob/master/slowfast/datasets/DATASET.md) to prepare your dataset. 
The expected format is something like:

```
path_to_video_1 label_1
path_to_video_2 label_2
path_to_video_3 label_3
...
path_to_video_N label_N
```
Feel free to re-open it if you haven't solve the issue.

**Comment by harishyvs** [comment]
Hi, 
I am still getting the following errors :
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
RuntimeError: Failed to fetch video after 10 retries.

The data entries in the test.csv file are in the order mentioned :
/home/my_name/***.mp4 101
where 101 is the label number. Am i missing anything here ?

**Comment by tathagatv** [comment]
@haooooooqi in the expected format you mentioned, don't we require commas as it is a csv file?
