### ISSUE TITLE
How does image resolution affect accuracy?

### ISSUE THREAD

**Issue by anuar12** [facebookresearch/SlowFast#12]
Hi thanks for great repo! 

Did you have a chance to experiment how input image resolution affects accuracy? I would imagine you use 224x224 for training because of the memory constraints and large dataset, but if one would use 640x640 would that make a large difference (excluding actions which involve small objects, e.g. smoking)?

**Comment by takatosp1** [comment]
Hi
Thanks for asking! 224x224 is also a standard setting to image classification on Kinetics, higher resolution is used only for certain tasks, and same Hong also apply to video. Note that higher resolution will not only increase the memory usage but also increase the flop, increasing flop would normally offer a slightly better performance. (If the way increasing flop is not too wrong)
