### ISSUE TITLE
 There is a mistake in the data preparation

### ISSUE THREAD

**Issue by hisiter97** [facebookresearch/SlowFast#122]
`  

        # T H W C -> C T H W.  
        frames = frames.permute(3, 0, 1, 2)  

        # Perform data augmentation.  

        frames = self.spatial_sampling(  
            frames,         # your requirement is T H W C  
            spatial_idx=spatial_sample_index,  
            min_scale=min_scale,  
            max_scale=max_scale,  
            crop_size=crop_size,  
        )  
`
But in  self.spatial_sampling function :   

frames (tensor): frames of images sampled from the video. The
                dimension is `num frames` x `height` x `width` x `channel`.

Is there a mistake here?

**Comment by Andy1621** [comment]
I think it's just a mistake in comment...
In `kinetics.py`
https://github.com/facebookresearch/SlowFast/blob/25a0f633b73fe2e1f9698f8a011dfc111828491b/slowfast/datasets/kinetics.py#L240
In `transform.py`
https://github.com/facebookresearch/SlowFast/blob/25a0f633b73fe2e1f9698f8a011dfc111828491b/slowfast/datasets/transform.py#L15
