### ISSUE TITLE
Error when loading from checkpoint

### ISSUE THREAD

**Issue by hengxiangYao** [facebookresearch/SlowFast#129]
[INFO: train_net.py:  255]: Load from last checkpoint.
Traceback (most recent call last):
  File "tools/run_net.py", line 152, in <module>
    main()
  File "tools/run_net.py", line 127, in main
    train(cfg=cfg)
  File "/home/hyao8934/slowfast/tools/train_net.py", line 257, in train
    checkpoint_epoch = cu.load_checkpoint(
  File "/home/hyao8934/slowfast/slowfast/utils/checkpoint.py", line 225, in load_checkpoint
    checkpoint = torch.load(path_to_checkpoint, map_location="cpu")
  File "/home/hyao8934/.conda/envs/pytorch-env/lib/python3.8/site-packages/torch/serialization.py", line 529, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/hyao8934/.conda/envs/pytorch-env/lib/python3.8/site-packages/torch/serialization.py", line 709, in _legacy_load
    deserialized_objects[key]._set_from_file(f, offset, f_should_read_directly)
RuntimeError: unexpected EOF, expected 789915 more bytes. The file might be corrupted.
terminate called after throwing an instance of 'c10::Error'
  what():  owning_ptr == NullType::singleton() || owning_ptr->refcount_.load() > 0 INTERNAL ASSERT FAILED at /opt/conda/conda-bld/pytorch_1579022027550/work/c10/util/intrusive_ptr.h:348, please report a bug to PyTorch. intrusive_ptr: Can only intrusive_ptr::reclaim() owning pointers that were created using intrusive_ptr::release(). (reclaim at /opt/conda/conda-bld/pytorch_1579022027550/work/c10/util/intrusive_ptr.h:348)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x47 (0x7f0ccda6c627 in /home/hyao8934/.conda/envs/pytorch-env/lib/python3.8/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0x148c55f (0x7f0cd0c2355f in /home/hyao8934/.conda/envs/pytorch-env/lib/python3.8/site-packages/torch/lib/libtorch.so)
frame #2: THStorage_free + 0x17 (0x7f0cd13ebb67 in /home/hyao8934/.conda/envs/pytorch-env/lib/python3.8/site-packages/torch/lib/libtorch.so)
frame #3: <unknown function> + 0x563c1d (0x7f0cffadcc1d in /home/hyao8934/.conda/envs/pytorch-env/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
<omitting python frames>
frame #21: __libc_start_main + 0xe7 (0x7f0d0e61fb97 in /lib/x86_64-linux-gnu/libc.so.6)

The error message shown like that, I don't know how to solve that and how to use checkpoint? It says "path_to_your_PyTorch_checkpoint" in introduction, but it seems auto-save the checkpoint already. 
Even I changed the model, it still says error when loading from checkpoint.

**Comment by takatosp1** [comment]
Hi,
Thanks for playing with PySlowFast!
You might want to check if the checkpoint you loaded is a caffe2 checkpoint or a pytorch checkpoint. If it is a Caffe2 checkpoint, you could go head to change the checkpoint type to caffe2, otherwise you could keep using pytorch :)

It looks like the error you got is caused by loading a caffe2 checkpoint as pytorch checkpoint,.
Feel free to share the update from your side :P.
