### ISSUE TITLE
launching issue of flop count

### ISSUE THREAD

**Issue by hengxiangYao** [facebookresearch/SlowFast#130]
Hi, thanks for the code.
I met an error while trying to do the training.
`[INFO: misc.py:  103]: Params: 24,327,632

[INFO: misc.py:  104]: Mem: 93.03857421875 MB

[WARNING: flop_count.py:  120]: Skipped operation aten::relu_ 49 time(s)

[WARNING: flop_count.py:  120]: Skipped operation aten::max_pool3d 2 time(s)

[WARNING: flop_count.py:  120]: Skipped operation aten::add 16 time(s)

[WARNING: flop_count.py:  120]: Skipped operation aten::avg_pool3d 1 time(s)

[WARNING: flop_count.py:  120]: Skipped operation aten::cat 1 time(s)

[WARNING: flop_count.py:  120]: Skipped operation aten::permute 1 time(s)

[WARNING: flop_count.py:  120]: Skipped operation aten::dropout 1 time(s)

[WARNING: flop_count.py:  120]: Skipped operation aten::add_ 1 time(s)

[WARNING: flop_count.py:  120]: Skipped operation aten::Int 1 time(s)

Traceback (most recent call last):
  File "tools/run_net.py", line 152, in <module>
    main()
  File "tools/run_net.py", line 127, in main
    train(cfg=cfg)
  File "/home/hyao8934/slowfast/tools/train_net.py", line 248, in train
    misc.log_model_info(model, cfg, is_train=True)
  File "/home/hyao8934/slowfast/slowfast/utils/misc.py", line 106, in log_model_info
    "FLOPs: {:,} GFLOPs".format(get_flop_stats(model, cfg, is_train))
  File "/home/hyao8934/slowfast/slowfast/utils/misc.py", line 87, in get_flop_stats
    gflop_dict, _ = flop_count(model, inputs)
ValueError: too many values to unpack (expected 2)
Segmentation fault (core dumped)
`
I believe I met this error the first time I tried, but didn't remember how to fix it. Could anyone help?
Thanks in advance!

**Comment by takatosp1** [comment]
Hey hengxiangYao, 
Thanks for playing with PySlowFast! Could you try to pull the latest fvcore?

**Comment by hengxiangYao** [comment]
Thanks for the reply, I recreate new virtual environment and it did the trick. Thank you!

**Comment by ldtuanAPCS** [comment]
Hi, 
I did pull the latest fvcore - version 0.1 but still get warnings for flop_count same as the comment above.  Could anyone help?
Thanks in advance!

**Comment by svajukiux** [comment]
I pulled the latest fvcore, but unfortunately I still get the same error and cannot start training.
