### ISSUE TITLE
CUDA error during training

### ISSUE THREAD

**Issue by hengxiangYao** [facebookresearch/SlowFast#131]
Hi, thank you for the code again.
The training process did begin,
![image](https://user-images.githubusercontent.com/46396374/75624027-40279700-5beb-11ea-80a7-4710d3841afc.png)
But after a few line, it appears:
![image](https://user-images.githubusercontent.com/46396374/75624035-5897b180-5beb-11ea-95e3-3701eff101d6.png)
My cuda version is
![image](https://user-images.githubusercontent.com/46396374/75624059-9ac0f300-5beb-11ea-91c6-64e26bbb768b.png)
And driver version is:
![image](https://user-images.githubusercontent.com/46396374/75624061-a57b8800-5beb-11ea-890f-7c8c61a08b31.png)
Sorry if it is a silly question, but I can't find the answer anywhere. Thanks in advance!

**Comment by takatosp1** [comment]
Hi 
Thanks for playing with PySlowFast. 
Looks your PyTorch was not properly installed, you might want to re-install PyTorch. (Seems there is something wrong with the mul_ or add_ op). 
I feel re-install CUDA and then re-install PyTorch would fix this problem.

Feel free to share your update here :P
