### ISSUE TITLE
I want to convert the model to torchlib model in C++, but the error is as follows. Would you please have a look?

### ISSUE THREAD

**Issue by Scheaven** [facebookresearch/SlowFast#135]
-----------code:--------
import torch

model = torch.load("mymodel.pth")        #Trained model
traced_script_module = torch.jit.script(model)
traced_script_module.save("model.pt")

------error--------
getattr's second argument must be a string literal:
  File "/home/basic/workspace/Scheaven/06_action_recognition/slowfast/slowfast/models/stem_helper.py", line 96
        for pathway in range(len(x)):
            print(pathway, ":::")
            m = getattr(self, "pathway{}_stem".format(pathway))
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
            x[pathway] = m(x[pathway])
        return x

**Comment by takatosp1** [comment]
Hi,
Thanks for playing with PySF! As far as I know the (older version of) torchlib does not support dynamic inference where the name of the layer is generated on the flight:
```
m = getattr(self, "pathway{}_stem".format(pathway))
```
 I am not sure whether they support it in the latest version.
You might want to 
1) firstly try the latest torchlib, and if it does not work, try
2) try hardcode the name as
```
self.pathway1_stem(x)
```

**Comment by BelongAl** [comment]
How to solve this problem? thank you!
