### ISSUE TITLE
Detection for Kinetics Dataset

### ISSUE THREAD

**Issue by NaeemKhan333** [facebookresearch/SlowFast#137]
Thanks for your nice work . I have question , Is detection is done during the training for kinetics Dataset or it is using the whole image frame of video in training. Please guide me about that and also how can use detection to get result like "ava_demo.gif" on kinetics Dataset . Thank you

**Comment by takatosp1** [comment]
Hi,
Thanks for playing with PySlowFast!
Video detection (action detection) models are trained on AVA dataset, a video clip is used as input. Details can be found in the [SlowFast paper](https://arxiv.org/pdf/1812.03982.pdf).
For ava_demo.gif, you need to get the bbox and the prediction results from the network, and visualize with any visualization tool you like to use.

**Comment by NaeemKhan333** [comment]
can you guide me what steps I need to done to train my own custom dataset to format like AVA Dataset and train the model on pyslowfast using detection method?

**Comment by PedestrianZQZ** [comment]
Hi @NaeemKhan333 , have you figured it out? I encountered with same question now

**Comment by ZainZhao** [comment]
> Hi,
> Thanks for playing with PySlowFast!
> Video detection (action detection) models are trained on AVA dataset, a video clip is used as input. Details can be found in the [SlowFast paper](https://arxiv.org/pdf/1812.03982.pdf).
> For ava_demo.gif, you need to get the bbox and the prediction results from the network, and visualize with any visualization tool you like to use.

Thanks for your nice work. if i train X3D on Kinetics for video classification, could i transform video to frame as input, or just raw video(train\val\test)?
Thank you again!

**Comment by PedestrianZQZ** [comment]
hi, i trained my model with raw videos, you can take ucf-101 as an example of file structure

**Comment by ZainZhao** [comment]
> hi, i trained my model with raw videos, you can take ucf-101 as an example of file structure

thank you for your reply. You means that the X3D in SlowFast has provided the code of frame transform ?

and I cannot find  ucf-101 as an example of file structure in Dir. config.

hope for your reply.

thank u again

**Comment by PedestrianZQZ** [comment]
Frankly speaking,  I didn't go through the code very carefully, and I used I3D rather than X3D as well. I'm not sure how this model deal with the video fed to it. I basically followed [this](https://github.com/facebookresearch/SlowFast/issues/149) issue, hope it will be helpful.
