### ISSUE TITLE
Should the BASE_LR be increased linearly with the total mini-batch size?

### ISSUE THREAD

**Issue by ZihaoWang-CV** [facebookresearch/SlowFast#14]
In appendix A of the paper,  the total mini-batch size is 1024 and the corresponding BASE_LR is set as 1.6.  While in the config file [SLOWFAST_16x8_R101_50_50.yaml](https://github.com/facebookresearch/SlowFast/blob/master/configs/Kinetics/c2/SLOWFAST_16x8_R101_50_50.yaml), the total mini-batch size is 64 and the corresponding BASE_LR is 0.1. Both of them are 16 times smaller than those reported in the paper.

Can I assume that the BASE_LR should be changed linearly with the total batch size in my own experiment setting? 

Thank you!

**Comment by takatosp1** [comment]
Good catch!
According to linear scaling rule, you shall scale the lr with the same ratio as you scale the over all batch size.
