### ISSUE TITLE
Question about data augmentation.

### ISSUE THREAD

**Issue by Abyssaledge** [facebookresearch/SlowFast#140]
Hi,
In `kinectis.py`, it seems that you didn't apply any color jitter for training. I guess you have done such experiment before. Does it affect performance?  Will it get higher test accuracy if I apply color jitter？

**Comment by takatosp1** [comment]
Hi
Thanks for playing with PySlowFast!
Yes I have tried it with I3D model long time ago on Kinetics K400 dataset, and I did not find it helps on that setting. 
Thanks
