### ISSUE TITLE
Testing with different crop size than training

### ISSUE THREAD

**Issue by kiyoon** [facebookresearch/SlowFast#142]
Hi, thanks for sharing the wonderful framework.
I was wondering why you train with 224x224 input and test with a bigger size of 256x256. I couldn't find the reason in the paper. Is there any particular reason?

I understand the fully-convolutional network can accept variable input size, and at the end of the model you have pooling to make the output the same size.
However, it seems like you use `cfg.DATA.CROP_SIZE` in the ResNet model which is set to 224x224 for both training and testing. Does it not affect the input you give to the model? Shouldn't you give 256x256 when testing?

Thank you.

**Comment by takatosp1** [comment]
Hi,
Thanks for playing with PySlowFast!
For training, a random crop is performed in a range of 256, 320, that is the reason to use 256x256 in testing.
