### ISSUE TITLE
Batch size when use more machines 

### ISSUE THREAD

**Issue by tonysy** [facebookresearch/SlowFast#145]
@takatosp1 @lyttonhao  Hi, thanks for your work.
I try to use this codebase to train the model with more than one machine.
If I keep your provided config as default, just use the following:
```bash
# Node-1
python tools/run_net.py \
  --cfg configs/Kinetics/C2D_8x8_R50.yaml \
--shard_id 0 --num_shards 2 --init_method tcp://gnode22:9999
# Node-2
python tools/run_net.py \
  --cfg configs/Kinetics/C2D_8x8_R50.yaml \
 --shard_id 1 --num_shards 2 --init_method tcp://gnode22:9999
```
each node include the 4 gpus.
I find though the batch size of the config is 64(which is default), the true optimization batch size is 128(=64/4*(4x2)), so the batch size of BN become 16 instead of 8(=64/8, default). I'm curious about he batch size in the config is the total clips on one node only or all nodes ?

So, my question is: if I use more than one nodes, do I need to change the batch size and lr to keep the BN batch size with 8?

**Comment by takatosp1** [comment]
Hi,
Thanks for playing with PySlowFast!

If you change your overall batch size, you need to adjust your lr accordingly.
Let's say, the baseline is to use one machine with lr of 0.1. If you use two machine, the lr should be 0.2.
