### ISSUE TITLE
video container backend is 'torchvision' i find some error

### ISSUE THREAD

**Issue by ruyiweicas** [facebookresearch/SlowFast#148]
![image](https://user-images.githubusercontent.com/14344027/76755123-4490aa00-67be-11ea-90f1-0401d70a0c2c.png)
in my enviroument torchvision.io has not read_video_meta_data_from_memory

it is right???

**Comment by ruyiweicas** [comment]
![image](https://user-images.githubusercontent.com/14344027/76755334-a7824100-67be-11ea-91b9-2361da858141.png)

**Comment by ruyiweicas** [comment]
should be  **io._read_video_from_memory()** not **io.read_video_from_memory()** right???

**Comment by ruyiweicas** [comment]
![image](https://user-images.githubusercontent.com/14344027/76756459-ae11b800-67c0-11ea-9b60-2709a9427c66.png)


Why did make this mistake? Sincerely hope you can get help

**Comment by takatosp1** [comment]
Hi,
Thanks for playing with PySlowFast!
I am not sure what is the torch vision version you were using, but you might want to upgrade yours. The version you were using seems to be a legacy version.

If you check the current version from [here](https://github.com/pytorch/vision/blob/master/torchvision/io/__init__.py), you will find:

"""
from ._video_opt import (
    Timebase,
    VideoMetaData,
    _HAS_VIDEO_OPT,
    _probe_video_from_file,
    _probe_video_from_memory,
    _read_video_from_file,
    _read_video_from_memory,
    _read_video_timestamps_from_file,
    _read_video_timestamps_from_memory,
)
from .video import (
    read_video,
    read_video_from_memory,
    read_video_meta_data_from_memory,
    read_video_timestamps,
    write_video,
)


__all__ = [
    "write_video",
    "read_video",
    "read_video_timestamps",
    "read_video_meta_data_from_memory",
    "read_video_from_memory",
    "_read_video_from_file",
    "_read_video_timestamps_from_file",
    "_probe_video_from_file",
    "_read_video_from_memory",
    "_read_video_timestamps_from_memory",
    "_probe_video_from_memory",
    "_HAS_VIDEO_OPT",
    "_read_video_clip_from_memory",
    "_read_video_meta_data",
    "VideoMetaData",
    "Timebase",
]
"""

Thanks for your kind remind and I will add one line to remind users to use the master version of torchvision. :)

**Comment by takatosp1** [comment]
> should be **io._read_video_from_memory()** not **io.read_video_from_memory()** right???

No!!!

**Comment by sourabmaity** [comment]
I got this issue again 
`AttributeError: '_OpNamespace' object has no attribute 'read_video_from_memory'`

on latest torchvision 0.13.0
And your [link ](https://github.com/pytorch/vision/blob/main/torchvision/io/__init__.py)also showing that read_video_from_memory is not present 
How to solve that??
