### ISSUE TITLE
error while loading model

### ISSUE THREAD

**Issue by gooners1886** [facebookresearch/SlowFast#15]
when I run 
python tools/run_net.py \
  --cfg configs/Kinetics/SLOWFAST_8x8_R50.yaml \
  DATA.PATH_TO_DATA_DIR data/k400/val_mini.csv \
  TEST.CHECKPOINT_FILE_PATH checkpoints/k400/SLOWFAST_8x8_R50.pkl \
  TRAIN.ENABLE False

This error happens:
[INFO: checkpoint.py:  204]: res5_1_branch2b_bn_b: (512,) => s5.pathway0_res1.branch2.b_bn.bias: (512,)
[INFO: checkpoint.py:  204]: res3_1_branch2a_bn_riv: (128,) => s3.pathway0_res1.branch2.a_bn.running_var: (128,)
[INFO: checkpoint.py:  204]: res5_1_branch2b_bn_s: (512,) => s5.pathway0_res1.branch2.b_bn.weight: (512,)
[INFO: checkpoint.py:  204]: res4_4_branch2c_w: (1024, 256, 1, 1, 1) => s4.pathway0_res4.branch2.c.weight: (1024, 256, 1, 1, 1)
[INFO: checkpoint.py:  204]: t_res2_1_branch2c_w: (32, 8, 1, 1, 1) => s2.pathway1_res1.branch2.c.weight: (32, 8, 1, 1, 1)
[INFO: checkpoint.py:  204]: t_res5_0_branch1_w: (256, 128, 1, 1, 1) => s5.pathway1_res0.branch1.weight: (256, 128, 1, 1, 1)
[INFO: checkpoint.py:  204]: res2_2_branch2c_bn_riv: (256,) => s2.pathway0_res2.branch2.c_bn.running_var: (256,)
Traceback (most recent call last):
  File "tools/run_net.py", line 152, in <module>
    main()
  File "tools/run_net.py", line 148, in main
    test(cfg=cfg)
  File "/data/yangyang/code/sf/sf4/tools/test_net.py", line 102, in test
    convert_from_caffe2=cfg.TEST.CHECKPOINT_TYPE == "caffe2",
  File "/data/yangyang/code/sf/sf4/slowfast/utils/checkpoint.py", line 197, in load_checkpoint
    tuple(ms.state_dict()[converted_key].shape),
AssertionError: t_res4_5_branch2c_bn_subsample_w: (256, 128, 7, 1, 1) does not match s4_fuse.conv_f2s.weight: (256, 128, 5, 1, 1)

i download the model directly from https://dl.fbaipublicfiles.com/pyslowfast/model_zoo/SLOWFAST_8x8_R50.pkl 

My env info is:
python 3.6.9 in anaconda 
CentOS7.2

**Comment by takatosp1** [comment]
Hi,
Thanks for using the pretrained model!
In https://github.com/facebookresearch/SlowFast/blob/master/MODEL_ZOO.md you will see we have the path to the configs next to each of the pretrained models. Then you'll probably see the config for SLOWFAST_8x8_R50 is Kinetics/c2/SLOWFAST_8x8_R50.yaml rather than Kinetics/SLOWFAST_8x8_R50.yaml.
So long story short, you are using a wrong config now, you can go ahead to use the config under c2 folder and the problem shall be solved. :)
