### ISSUE TITLE
C2D scores on Kinetics

### ISSUE THREAD

**Issue by ecr23xx** [facebookresearch/SlowFast#150]
I notice that the R50 C2D scores on Kinetics-400 you report (67.2) is much lower than that in [facebookresearch/video-nonlocal-net](https://github.com/facebookresearch/video-nonlocal-net) (71.9). The input frames are both 8.

One possible reason could be the pre-trained model. You train it from scratch but nonlocal use ImageNet pre-trained model. But I don't think it would have such a big impact. Are there any other explanations?

**Comment by takatosp1** [comment]
Hi,
Thanks for playing with PySlowFast!
The job you referring is indeed *training from scratch* and get us get us 67.2. I feel for C2D, the model would largely benefit from ImageNet pretraining.

**Comment by ecr23xx** [comment]
Thanks for your quick reply.
