### ISSUE TITLE
could you please attach hyperlinks about theses models?

### ISSUE THREAD

**Issue by k-zha14** [facebookresearch/SlowFast#154]
hi, guys! I really appreciate your open-source work. However, as a freshman in this field, I really want to know more about these models. In your [MODEL_ZOO](https://github.com/facebookresearch/SlowFast/blob/master/MODEL_ZOO.md) file,  I see many models, like C2D, I3D and etc. Could you please attach some hyperlink about these model? Or maybe you can just briefly explain the architecture about these model ? 
Thank u so much!

**Comment by k-zha14** [comment]
BTW, what the hell is SlowOnly? I can't even google it. I really want to know it.

**Comment by takatosp1** [comment]
Hi,
Thanks for playing with PySlowFast, you could take a look at:
https://arxiv.org/pdf/1711.07971.pdf
https://arxiv.org/pdf/1812.03982.pdf
I guess these two papers covers most of the models we use in the codebase
Thanks
