### ISSUE TITLE
I appear in Windows emersion KeyError: 'forkserver' can you help me to have a look

### ISSUE THREAD

**Issue by wangaoqi-waq** [facebookresearch/SlowFast#155]
When I was in Windows reiteration：
python tools/run_net.py 
--cfg configs/AVA/c2/SLOWFAST_32x2_R101_50_50_v2.1.yaml 
DATA.PATH_TO_DATA_DIR datasets/ava 
TEST.CHECKPOINT_FILE_PATH models/SLOWFAST_32x2_R101_50_50_v2.1.pkl 
TRAIN.ENABLE False 

In the following error：

Traceback (most recent call last):
  File "C:\Anaconda3\envs\pytorch\lib\multiprocessing\context.py", line 190, in get_context
    ctx = _concrete_contexts[method]
KeyError: 'forkserver'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/run_net.py", line 151, in <module>
    torch.multiprocessing.set_start_method("forkserver")
  File "C:\Anaconda3\envs\pytorch\lib\multiprocessing\context.py", line 246, in set_start_method
    self._actual_context = self.get_context(method)
  File "C:\Anaconda3\envs\pytorch\lib\multiprocessing\context.py", line 238, in get_context
    return super().get_context(method)
  File "C:\Anaconda3\envs\pytorch\lib\multiprocessing\context.py", line 192, in get_context
    raise ValueError('cannot find context for %r' % method)
ValueError: cannot find context for 'forkserver'
how can I solve it? thank you！

**Comment by takatosp1** [comment]
Hi,
Thanks for plaything with PySlowFast!
Seems currently in your ENV the default method to start a new process is forkserver, however windows does not support forkserver.
You could manually set it to spawn, which should fix the problem.
More details: https://docs.python.org/3/library/multiprocessing.html

Thanks

**Comment by takatosp1** [comment]
Hi 
I have removed the forserver from the main.py for your use case. Please try with the latest master to see if you still see the issue.

**Comment by wangaoqi-waq** [comment]
Thank you for your reply, an unknown error occurred because Windows will also, I've been using ubuntu
After I might try Windows, thank you

**Comment by takatosp1** [comment]
Hi,
Feel free to remove the forkserver line in `tools/run_net.py'.
