### ISSUE TITLE
RuntimeError: Failed to fetch video after 10 retries

### ISSUE THREAD

**Issue by digbose92** [facebookresearch/SlowFast#158]
I am trying to train the Slowfast network on my custom dataset (where I have a single label for each video). I have prepared the dataset files according to the instructions provided in https://github.com/facebookresearch/SlowFast/blob/master/slowfast/datasets/DATASET.md (under the Kinetics section). The snapshot of my train.csv file looks like this:
<img width="1341" alt="Screen Shot 2020-03-29 at 4 13 43 PM" src="https://user-images.githubusercontent.com/14272549/77863587-5586e580-71d8-11ea-8012-5bac8a4d83b1.png">

But when I am trying to train on my custom dataset using the command: python tools/run_net.py --cfg configs/Kinetics/C2D_8x8_R50.yaml DATA.PATH_TO_DATA_DIR /home/digbose92/MM_ads/ads_codes_final/csv_slowfast_files/ NUM_GPUS 2 TRAIN.BATCH_SIZE 4

I am getting the following error:
<img width="1673" alt="Screen Shot 2020-03-29 at 4 16 58 PM" src="https://user-images.githubusercontent.com/14272549/77863668-caf2b600-71d8-11ea-8181-1d8c0211dea8.png">

Any help is appreciated. Thanks in advance.

**Comment by takatosp1** [comment]
Hi Thanks for playing with PySlowFast!

Looks like the format of you data is not what the code expected. One simple way to debug this is to remove the try and see where piece of code give you the error.

**Comment by takatosp1** [comment]
I think the solution I proposed should fix the issue in your use case. I'll close the issue for now and feel free to re-open it if it is not fix.

**Comment by digbose92** [comment]
Hi @takatosp1 many thanks for the suggestion. I did exactly as the proposed solution. I fixed the csv file and it looks like this : 
<img width="768" alt="Screen Shot 2020-03-30 at 1 45 59 PM" src="https://user-images.githubusercontent.com/14272549/77960374-0a7ada00-728d-11ea-96d4-4aa7165baec8.png">
 Based on your suggestion, I used the following command to run:
```
python tools/run_net.py --cfg configs/Kinetics/C2D_8x8_R50.yaml DATA.PATH_TO_DATA_DIR /data/digbose92/resized_ads_videos/ads_of_world_jwt NUM_GPUS 1 TRAIN.BATCH_SIZE 4 DATA_LOADER.NUM_WORKERS 16
```
I am getting this error:
<img width="1668" alt="Screen Shot 2020-03-30 at 2 04 57 PM" src="https://user-images.githubusercontent.com/14272549/77962013-a6a5e080-728f-11ea-80af-a8c130ca9100.png">

Thanks in advance !

**Comment by Luoxsh6** [comment]
@digbose92 I think you can try to print out the video path in the kinetics.py, and you might see something wrong with you data path, I had solved this problem by changing the _C.DATA.PATH_PREFIX tag in slowfast/config/defaults.py
