### ISSUE TITLE
Failure to fetch video after retries

### ISSUE THREAD

**Issue by digbose92** [facebookresearch/SlowFast#160]
Hi @takatosp1 many thanks for the suggestion. I did exactly as the proposed solution. I fixed the csv file and it looks like this : 
<img width="768" alt="Screen Shot 2020-03-30 at 1 45 59 PM" src="https://user-images.githubusercontent.com/14272549/77960374-0a7ada00-728d-11ea-96d4-4aa7165baec8.png">
 Based on your suggestion, I used the following command to run:
```
python tools/run_net.py --cfg configs/Kinetics/C2D_8x8_R50.yaml DATA.PATH_TO_DATA_DIR /data/digbose92/resized_ads_videos/ads_of_world_jwt NUM_GPUS 1 TRAIN.BATCH_SIZE 4 DATA_LOADER.NUM_WORKERS 16
```
I am getting this error:
<img width="1668" alt="Screen Shot 2020-03-30 at 2 04 57 PM" src="https://user-images.githubusercontent.com/14272549/77962013-a6a5e080-728f-11ea-80af-a8c130ca9100.png">

Thanks in advance !

_Originally posted by @digbose92 in https://github.com/facebookresearch/SlowFast/issues/158#issuecomment-606250120_

**Comment by takatosp1** [comment]
Hi,
Thanks for playing with PySF!
Could you comment the line of "try" and share me the error message?
Thanks

**Comment by digbose92** [comment]
Hi @takatosp1, thanks for the suggestion. I commented the try statement and re-ran the script. I am getting the following error message.
<img width="1680" alt="Screen Shot 2020-04-03 at 1 01 45 PM" src="https://user-images.githubusercontent.com/14272549/78400423-86d22d80-75ab-11ea-8e16-c0ed3656f984.png">
For your reference, I am using pytorch 1.4.0 and PyAv 6.1.0. Rest of the packages were installed as mentioned in https://github.com/facebookresearch/SlowFast/blob/master/INSTALL.md 
Thanks for the help !

**Comment by digbose92** [comment]
The error is pretty similar to the one mentioned here :https://github.com/mikeboers/PyAV/issues/485 . Looks like a problem with pyav while handling corrupt files.

**Comment by digbose92** [comment]
Hi @takatosp1, I was able to solve the issue by reinstalling PyAv 6.2.0. I cross-checked the validity of video files and they were okay. The problem was PyAv 6.1.0. Thanks for your help !

**Comment by shivangi1410** [comment]
@digbose92 i am getting the same error and i am using PyAv 8.1.0 version.
can you please help?

Error
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.6/dist-packages/slowfast/datasets/kinetics.py", line 218, in __getitem__
    self._num_retries
RuntimeError: Failed to fetch video after 10 retries.
