### ISSUE TITLE
About the base  LR for SGDR

### ISSUE THREAD

**Issue by oLIVIa-Ld** [facebookresearch/SlowFast#161]
I‘ve found that the Slowfast used the SGDR and the base LR was set to 1.6 in K-400.
how does the base LR be settled?

**Comment by tonysy** [comment]
The baseline is to use one machine with lr of 0.1(8GPUs, batch_size=64), if you increase the batch_size, the lr should be increased linearly.  As presented in the appendix of the original SlowFast paper, they use 128GPUs(batch_size=128*8=1024=64*8), thus the LR is 1.6.

**Comment by takatosp1** [comment]
Thanks tonysy for answering the quetsion.

**Comment by bqhuyy** [comment]
> The baseline is to use one machine with lr of 0.1(8GPUs, batch_size=64), if you increase the batch_size, the lr should be increased linearly. As presented in the appendix of the original SlowFast paper, they use 128GPUs(batch_size=128x8=1024=64x16), thus the LR is 1.6.

Do I need to change MAX_EPOCH, WARMUP_EPOCHS, and WARMUP_START_LR? If yes, are there any rules for this? Thank you
