### ISSUE TITLE
Charades data split file link

### ISSUE THREAD

**Issue by ecr23xx** [facebookresearch/SlowFast#189]
Hi, I'm working on the Charades dataset. But the link to Charades data split file (in DATASET.md) seems broken. Could you update it?

**Comment by ecr23xx** [comment]
Is it the same as that provided in [facebookresearch/video-long-term-feature-banks](https://github.com/facebookresearch/video-long-term-feature-banks/blob/583c9a9dec89cdfdf867012fdf00bfcfb3bd56bb/DATASET.md)?

**Comment by lhyfst** [comment]
I'm working on the Charades dataset, too. I can run and train the model using the csv files in facebookresearch/video-long-term-feature-banks. So I think it should be the same files.

**Comment by ecr23xx** [comment]
OK, thanks!
