### ISSUE TITLE
UnicodeDecodeError when loading the pre-trained model

### ISSUE THREAD

**Issue by Shumpei-Kikuta** [facebookresearch/SlowFast#19]
Thank you for your great work!

When I tried to load the model you provided [here](https://github.com/facebookresearch/SlowFast/blob/master/MODEL_ZOO.md), I encountered the following error:

```
Traceback (most recent call last):
  File "tools/run_net.py", line 152, in <module>
    main()
  File "tools/run_net.py", line 128, in main
    train(cfg=cfg)
  File "/home/ubuntu/projects/SlowFast/tools/train_net.py", line 217, in train
    convert_from_caffe2=cfg.TRAIN.CHECKPOINT_TYPE == "caffe2",
  File "/home/ubuntu/projects/SlowFast/slowfast/utils/checkpoint.py", line 212, in load_checkpoint
    checkpoint = torch.load(path_to_checkpoint, map_location="cpu")
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.7/site-packages/torch/serialization.py", line 426, in load
    return _load(f, map_location, pickle_module, **pickle_load_args)
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.7/site-packages/torch/serialization.py", line 603, in _load
    magic_number = pickle_module.load(f, **pickle_load_args)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd4 in position 1: invalid continuation byte
```

This problem occurred probably because I tried to decode in a different way from way of encoding.
I would appreciate it if you could show me how this problem has happened, and how to solve it.

Thank you for your consideration!

**Comment by takatosp1** [comment]
Thanks for using the code.

Could you share me what is the version of python you are using? For PySlowFast the recommend version of python is 3.6.

**Comment by Shumpei-Kikuta** [comment]
Thank you for replying.

I use Python 3.7.3, which may cause this problem.
I am going to use 3.6 and let you know what happens.

**Comment by takatosp1** [comment]
I just updated my comments with more details.

**Comment by Shumpei-Kikuta** [comment]
Although I switched 3.7.3 to 3.6.9 by using a virtual environment, I still have the same problem.
I use torch torch==1.3.0 and torchvision==0.4.1.
Would you have another idea?

**Comment by takatosp1** [comment]
Have you set CHECKPOINT_TYPE to caffe2?

**Comment by Shumpei-Kikuta** [comment]
No, I haven't.
Let me try in that way.

**Comment by takatosp1** [comment]
Could you show me the path to the config you were using?

**Comment by takatosp1** [comment]
You might able to find more instruction regarding to loading pretrain model in GETTING_STARTED.md

**Comment by Shumpei-Kikuta** [comment]
I use default.py and never changed.
_C.TRAIN.CHECKPOINT_TYPE = "pytorch" 

Once I switch pytorch to caffe2, I succeeded in loading the pre-trained model.
Thank you so much!!

**Comment by takatosp1** [comment]
Thanks. Again you could find the detailed instruction of how to load model (pytorch or caffe2) in GETTING_STARTED.md
