### ISSUE TITLE
some question in the assert len({len(pool_size), self.num_pathways}) == 1

### ISSUE THREAD

**Issue by sdjsngs** [facebookresearch/SlowFast#193]
I got a question for this code ,  assert len({len(pool_size), self.num_pathways}) == 1  mean the len({len(pool_size), self.num_pathways}) should be 1?  
 in slowfast  self.num_pathways=2  and the len(pool_size) has its only len value.  it should be 2  how could it  be 1 ?    i am confused , would any one  give some solution ? thank you !

**Comment by takatosp1** [comment]
Hi,

Thanks for playing with PySlowFast!

len(
{
len(pool_size), 
self.num_pathways
}
) == 1 

Means len(pool_size) == self.num_pathways
