### ISSUE TITLE
About multigrid training

### ISSUE THREAD

**Issue by chongruo** [facebookresearch/SlowFast#195]
Can I ask when the code for multigrid training will be merged? Is it possible to provide instructions on how to train models with multigrid training? Thanks

**Comment by chaoyuaw** [comment]
Hi @chongruo ,  We just updated the README, MODEL_ZOO, yamls, etc. for multigrid training. Thanks for your interests!

**Comment by chongruo** [comment]
> Hi @chongruo , We just updated the README, MODEL_ZOO, yamls, etc. for multigrid training. Thanks for your interests!

Thanks!
