### ISSUE TITLE
DefaultCPUAllocator: not enough memory: you tried to allocate 93321840 bytes. Buy new RAM!

### ISSUE THREAD

**Issue by sdjsngs** [facebookresearch/SlowFast#196]
HI,  I run  this code  on HMDB51 dataset , when training,  my RAM is continued growth. i  have 32GB RAM  and  train will stop in the first few epoch .   I run  this code on one GTX1080TI and  use the torch.cuda.empty_cache()  for each batch size . the memory of GPU will get down and up, but the RAM is still growth. Could any one tell some sloution about  this? i use pyav==6.2.0 to load the video dataset.  
Thank You !!!

**Comment by takatosp1** [comment]
Hi, Thanks for playing with PySlowFast!
Could you try to reduce the NUM_WORKERS? It will help you save some RAM.

**Comment by sdjsngs** [comment]
HI i use  NUM_WORKERS=0  , but it did not work . and i test  this code  if just use  dataloader part  with pyav  , RAM growth , so it may be the data loader problem  and i still work on it .  may load single video with opencv-python will help.

**Comment by sdjsngs** [comment]
@takatosp1  
HI i use NUM_WORKERS=0 , but it did not work . and i test this code if just use dataloader part with pyav , RAM growth , so it may be the data loader problem and i still work on it . may load single video with opencv-python will help.

**Comment by sdjsngs** [comment]
@takatosp1  i use the cv2 code  to load the  video data in kinetics.py/__getitem__  and  it works now and RAM  is    9.4GB  ,  not growth  .  i work this code on windows10, torch1.4.2 +cu92 .    thank you for your reply ！！！ 
Have a nice day !!!

**Comment by BonGum** [comment]
@sdjsngs How did you figure it out with cv2 code？ I think maybe I encounter the same problem as yours.
![problem](https://github.com/facebookresearch/SlowFast/assets/58102607/77e686c2-cdc5-439e-9729-4094e8d21d12)
Looking forward to your reply! pls
