### ISSUE TITLE
runtime mismatching the estimated FLOPs

### ISSUE THREAD

**Issue by Cory-M** [facebookresearch/SlowFast#198]
Hi, thanks for sharing this great video recognition framework! 

I tried to run the Kinetics/SLOW_4x16_R50.yaml and Kinetics/SLOWFAST_4x16_R50.yaml, which FLOPs are **20** and **27** GFLOPs. However, the runtime for SLOWFAST is 2-3 times larger than that of SLOW: (both on 2 GPU, batch_size 32, recorded by timediff and with cuda.synchronization). 

              SLOW.          SLOWFAST
     FLOPs     20               27
     foward    0.14s           0.3s
     backward  0.25s           0.7s

Similar results hold true for SLOWFAST_8x8_R50 and SLOW_8x8_R50. 

Does anyone have any ideas about why this is happening? Thanks so much!

**Comment by takatosp1** [comment]
Hi,
Thanks for playing with PySlowFast!
I haven't thoroughly benchmark the forward/ backward time between slow and slowfast models, but in generally two stream network are expected to be slower than the single stream network with the same FLOPs.

**Comment by youngwanLEE** [comment]
@Cory-M 
Hi,
Could you let us know how to compute the FLOPs?
