### ISSUE TITLE
RuntimeError: Caught RuntimeError in DataLoader worker process 0.

### ISSUE THREAD

**Issue by harishyvs** [facebookresearch/SlowFast#206]
Hi,
I am still getting the following errors :
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
RuntimeError: Failed to fetch video after 10 retries.
Failed to decode by pyav with exception: division by zero

The data entries in the test.csv file are in the order mentioned :
/home/my_name/***.mp4 101
where 101 is the label number. Am i missing anything here ? @takatosp1

Note : I am testing the SlowFast network on my own video from the internet.
I don't have a json file. 
Should I create one ?

**Comment by harishyvs** [comment]
Hey, solved it. Mostly the problem was not following the pre-processing steps.

**Comment by chenjiakun** [comment]
> Hey, solved it. Mostly the problem was not following the pre-processing steps.



> Hey, solved it. Mostly the problem was not following the pre-processing steps.

Hi！How did you solve this problem？

**Comment by chenjiakun** [comment]
> Hey, solved it. Mostly the problem was not following the pre-processing steps.

Hi！How did you solve this problem？
