### ISSUE TITLE
AssertionError: Override list has odd length: ['NUM_GPUS', '1', 'TRAIN.BATCH_SIZE', '8', 'SOLVER.BASE_LR', '0.0125', 'DATA.PATH_TO_DATA_DIR']; it must be a list of pairs

### ISSUE THREAD

**Issue by zhulishun** [facebookresearch/SlowFast#207]
when I 
“python tools/run_net.py --cfg configs/Kinetics/C2D_8x8_R50.yaml NUM_GPUS 1 TRAIN.BATCH_SIZE 8 SOLVER.BASE_LR 0.0125 DATA.PATH_TO_DATA_DIR”
-
AssertionError: Override list has odd length: ['NUM_GPUS', '1', 'TRAIN.BATCH_SIZE', '8', 'SOLVER.BASE_LR', '0.0125', 'DATA.PATH_TO_DATA_DIR']; it must be a list of pairs

**Comment by ysl208** [comment]
I'm getting the same error. How did you resolve it?

**Comment by guochengqian** [comment]
It should be:
`python tools/run_net.py --cfg configs/Kinetics/C2D_8x8_R50.yaml --opts NUM_GPUS 1 TRAIN.BATCH_SIZE 8 SOLVER.BASE_LR 0.0125 DATA.PATH_TO_DATA_DIR`

This repo is not frequently updated and README files are quite outdated.
