### ISSUE TITLE
Frame lists links for Charades and Something-Something-V2 don't work

### ISSUE THREAD

**Issue by LukasHedegaard** [facebookresearch/SlowFast#209]
The frame list links provided in https://github.com/facebookresearch/SlowFast/blob/master/slowfast/datasets/DATASET.md under sections "Charades" and "Something-Something-V2" give a 403 Forbidden response.

Tested with two computers (MacOS and Ubuntu 18) in Denmark.

**Comment by IoannaNti** [comment]
Same for me in the UK - links for frame list in  "Charades" and "Something-Something-V2" give 
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>476D54ECB4721A46</RequestId>
<HostId>
a7ZIibaPKeO6wN+UWXfAtbYPRrRasnEv/oBMlzPZoiaiVvi0uBuUkj80sUa5F31kEESEogvG+VE=
</HostId>
</Error>

**Comment by fangchengji** [comment]
Same issue

**Comment by fangchengji** [comment]
Found frame list in this issue (https://github.com/facebookresearch/SlowFast/issues/190)

**Comment by takatosp1** [comment]
Hi, Thanks for playing with PySlowFast!
The link has been updated.

Thanks,
Haoqi
