### ISSUE TITLE
ImportError: libtorch_cpu.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by zhulishun** [facebookresearch/SlowFast#210]
python tools/run_net.py --cfg configs/Kinetics/C2D_8x8_R50.yaml NUM_GPUS 1 TRAIN.BATCH_SIZE 8 SOLVER.BASE_LR 0.0125 DATA.PATH_TO_DATA_DIR path_to_your_data_folder

Traceback (most recent call last):
  File "tools/run_net.py", line 10, in <module>
    from test_net import test
  File "/home/zhutianhao/SlowFast/tools/test_net.py", line 12, in <module>
    import slowfast.utils.misc as misc
  File "/home/zhutianhao/SlowFast/slowfast/utils/misc.py", line 17, in <module>
    from slowfast.models.batchnorm_helper import SubBatchNorm3d
  File "/home/zhutianhao/SlowFast/slowfast/models/__init__.py", line 6, in <module>
    from .video_model_builder import ResNet, SlowFast  # noqa
  File "/home/zhutianhao/SlowFast/slowfast/models/video_model_builder.py", line 12, in <module>
    from . import head_helper, resnet_helper, stem_helper
  File "/home/zhutianhao/SlowFast/slowfast/models/head_helper.py", line 8, in <module>
    from detectron2.layers import ROIAlign
  File "/home/zhutianhao/SlowFast/detectron2_repo/detectron2/layers/__init__.py", line 3, in <module>
    from .deform_conv import DeformConv, ModulatedDeformConv
  File "/home/zhutianhao/SlowFast/detectron2_repo/detectron2/layers/deform_conv.py", line 10, in <module>
    from detectron2 import _C
ImportError: libtorch_cpu.so: cannot open shared object file: No such file or directory

**Comment by SuX97** [comment]
Hi, I also have this problem. How did you solve this problem?

**Comment by zyy9605** [comment]
> Hi, I also have this problem. How did you solve this problem?

Hello, have you solved this problem ? Could you please tell your method? Looking forward your answer!!!

**Comment by zyy9605** [comment]
> python tools/run_net.py --cfg configs/Kinetics/C2D_8x8_R50.yaml NUM_GPUS 1 TRAIN.BATCH_SIZE 8 SOLVER.BASE_LR 0.0125 DATA.PATH_TO_DATA_DIR path_to_your_data_folder
> 
> Traceback (most recent call last):
> File "tools/run_net.py", line 10, in
> from test_net import test
> File "/home/zhutianhao/SlowFast/tools/test_net.py", line 12, in
> import slowfast.utils.misc as misc
> File "/home/zhutianhao/SlowFast/slowfast/utils/misc.py", line 17, in
> from slowfast.models.batchnorm_helper import SubBatchNorm3d
> File "/home/zhutianhao/SlowFast/slowfast/models/**init**.py", line 6, in
> from .video_model_builder import ResNet, SlowFast # noqa
> File "/home/zhutianhao/SlowFast/slowfast/models/video_model_builder.py", line 12, in
> from . import head_helper, resnet_helper, stem_helper
> File "/home/zhutianhao/SlowFast/slowfast/models/head_helper.py", line 8, in
> from detectron2.layers import ROIAlign
> File "/home/zhutianhao/SlowFast/detectron2_repo/detectron2/layers/**init**.py", line 3, in
> from .deform_conv import DeformConv, ModulatedDeformConv
> File "/home/zhutianhao/SlowFast/detectron2_repo/detectron2/layers/deform_conv.py", line 10, in
> from detectron2 import _C
> ImportError: libtorch_cpu.so: cannot open shared object file: No such file or directory

Have you solved this problem ? Could you please tell your method? Looking forward your answer!!!

**Comment by AKASH2907** [comment]
Did anyone solve this issue? I'm also facing this.
I have installed pytorch 1.8, cuda 10.2 and detectron2 accordingly.
