### ISSUE TITLE
How to test 131 ava test data

### ISSUE THREAD

**Issue by 97-tianyan** [facebookresearch/SlowFast#213]
Hello!I can now successfully test 64 val data, but I don't know how to test 13 test data.Because I could not find 131 annotation files of test data, maybe your code requires you to provide annotation files when testing.Unfortunately I didn't

**Comment by YuJiZhe** [comment]
> Hello!I can now successfully test 64 val data, but I don't know how to test 13 test data.Because I could not find 131 annotation files of test data, maybe your code requires you to provide annotation files when testing.Unfortunately I didn't

Hi!!!!!! Friend! can u help to how to successfully test 64 val data, this is my issue link~ 
[(https://github.com/facebookresearch/SlowFast/issues/469)]
Thank you in advance~
WOULD u like to add my wechat '565290560' to talk about it !~
