### ISSUE TITLE
Fine tuning on a new dataset

### ISSUE THREAD

**Issue by SiftingSands** [facebookresearch/SlowFast#218]
Reading the previous issues and responses, it appears that a fine-tuning example script is a work in progress? If that's the case, I was hoping to get clarification on a few things in the mean-time. 

- Do I need to register a new dataset in a similar fashion to /datasets/kinetics.py ? Does the new Dataset class have to exist in the datasets folder to have the registration work?
- Do I need to manually resize to 256 shortest edge for all of the videos before ingestion into the dataloader? I wasn't sure if this was already implemented or left to the user.
- Partial model freezing still needs implementation?

**Comment by SiftingSands** [comment]
Closing, I got things mostly figured out.

**Comment by abhaygargab** [comment]
Hello @SiftingSands,
Can you please share your findings. I have the same doubts.

ThankYou

**Comment by adityac-deepnorth** [comment]
> Reading the previous issues and responses, it appears that a fine-tuning example script is a work in progress? If that's the case, I was hoping to get clarification on a few things in the mean-time.
> 
> * Do I need to register a new dataset in a similar fashion to /datasets/kinetics.py ? Does the new Dataset class have to exist in the datasets folder to have the registration work?
> * Do I need to manually resize to 256 shortest edge for all of the videos before ingestion into the dataloader? I wasn't sure if this was already implemented or left to the user.
> * Partial model freezing still needs implementation?

Hi, did you figure out the partial model freezing? I'm training SLOWFAST_8x8_R50 (pretrained on Kinetics 400) with my custom dataset with 3 classes. Each class having about 100-150 action videos. I'm thinking of training just s5 and FC layer. 
Also, if I prepare my dataset in Kinetics format, do I still have to come up with my own data loader. I haven't tested it yet so I'm not sure.

Thanks in advance!
