### ISSUE TITLE
Pretrained models not in .pkl format ?

### ISSUE THREAD

**Issue by MiVaVo** [facebookresearch/SlowFast#22]
Well , we all know about security risks that come with unpickling files from internet...
Is it possible to present models in Model Zoo not in pickled format ?

**Comment by takatosp1** [comment]
Hi,

Thanks for using the codebase and share your suggestion!
It’s been quite a standard in pytorch to save and load in pickles format:

https://pytorch.org/tutorials/beginner/saving_loading_models.html

Maybe you could share your suggestion in pytorch repo and if pytorch decide to change the convention then I’ll have the change according to reflect it.
