### ISSUE TITLE
How can I test on  a single video?

### ISSUE THREAD

**Issue by yangxuerong** [facebookresearch/SlowFast#220]
Hi! 
    I want to test a video on  the model SLOWFAST_8x8_R50.pkl（Kinetics），Could you kindly give me some helps? what shuold i do

**Comment by takatosp1** [comment]
Hi 
Thanks for playing with PySlowFast, you can have a csv file with only one video path in it.

**Comment by yangxuerong** [comment]
tkx

**Comment by yangxuerong** [comment]
In fact, What I'm asking is, if I have a video URL, how can I handle it directly instead of downloading it to local storage.

**Comment by yangxuerong** [comment]
Thank you for your reply.  if I have a video URL, how can I handle it directly instead of downloading it to local storage.
