### ISSUE TITLE
[1,1,1] 3DMaxpooling  after s2_fuse in slowfast 

### ISSUE THREAD

**Issue by sdjsngs** [facebookresearch/SlowFast#222]
@ takatosp1     Hi,   in slowfast/mdoel/video_model_builder.py  there has a [1,1,1] 3D MAXpool for each pathway  after s2_fuse,  why use this ?   does it can get  better performance in action classification?   or  better performance in video detection ? thanks for your time.

**Comment by JunweiLiang** [comment]
I think it is a placeholder in case you want to experiment with kernels other than [1, 1, 1], which itself does not do anything.

**Comment by takatosp1** [comment]
Thanks @JunweiLiang for the answer :)
