### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by jiaweihe1996** [facebookresearch/SlowFast#224]
When running multigrid training, the code segment below is not compatible.
https://github.com/facebookresearch/SlowFast/blob/133e40f8349ce37b0e6168639da0811a413579c8/slowfast/utils/misc.py#L158-L161
Because `n=1` and `n // self.num_splits` below becomes zero.
https://github.com/facebookresearch/SlowFast/blob/312366920a394e0a984e7d731077ca74e9f7abe6/slowfast/models/batchnorm_helper.py#L101

**Comment by chaoyuaw** [comment]
Hi @jiaweihe1996, Thanks for trying multigrid training. As a temporary fix, could you try setting LOG_MODEL_INFO to be False?

**Comment by jiaweihe1996** [comment]
Yes, I do so, and it works. Thank you very much.

**Comment by takatosp1** [comment]
Hi @jiaweihe1996,

thanks for playing with PySlowFast! We have updated the logic in the flop counting :) Try to play with the current master
