### ISSUE TITLE
AssertionError: (1, 4)

### ISSUE THREAD

**Issue by lawrencewc** [facebookresearch/SlowFast#225]
when I run
python tools/run_net.py 
--cfg configs/Charades/SLOWFAST_16x8_R50.yaml
 DATA.PATH_TO_DATA_DIR dataset_charades/fram_list/ 
DATA.PATH_PREFIX dataset_charades/Charades_v1_rgb/ 
NUM_GPUS 1 
TRAIN.BATCH_SIZE 16

this error happen：
Traceback (most recent call last):
  File "tools/run_net.py", line 29, in <module>
    main()
  File "tools/run_net.py", line 21, in main
    launch_job(cfg=cfg, init_method=args.init_method, func=train)
  File "slowfast/utils/misc.py", line 276, in launch_job
    func(cfg=cfg)
  File "tools/train_net.py", line 351, in train
    model = build_model(cfg)
  File "slowfast/models/build.py", line 31, in build_model
    model = MODEL_REGISTRY.get(name)(cfg)
  File "slowfast/models/video_model_builder.py", line 156, in __init__
    self._construct_network(cfg)
  File "slowfast/models/video_model_builder.py", line 194, in _construct_network
    norm_module=self.norm_module,
  File "slowfast/models/stem_helper.py", line 75, in __init__
    self._construct_stem(dim_in, dim_out, norm_module)
  File "slowfast/models/stem_helper.py", line 88, in _construct_stem
    norm_module,
  File "slowfast/models/stem_helper.py", line 154, in __init__
    self._construct_stem(dim_in, dim_out, norm_module)
  File "slowfast/models/stem_helper.py", line 166, in _construct_stem
    num_features=dim_out, eps=self.eps, momentum=self.bn_mmt
  File "slowfast/models/batchnorm_helper.py", line 186, in __init__self.num_sync_devices,
AssertionError: (1, 4)

Can you help shed some light on this?
Thanks in advance.
Best regards

**Comment by takatosp1** [comment]
Hi @lawrencewc,

Thanks for playing with PySlowFast! 
Seems you are using sync bn but you only using one GPU now (so don't have enough GPU bn stats to sync on).

**Comment by tianqiaotiemo** [comment]
> when I run
> python tools/run_net.py
> --cfg configs/Charades/SLOWFAST_16x8_R50.yaml
> DATA.PATH_TO_DATA_DIR dataset_charades/fram_list/
> DATA.PATH_PREFIX dataset_charades/Charades_v1_rgb/
> NUM_GPUS 1
> TRAIN.BATCH_SIZE 16
> 
> this error happen：
> Traceback (most recent call last):
> File "tools/run_net.py", line 29, in
> main()
> File "tools/run_net.py", line 21, in main
> launch_job(cfg=cfg, init_method=args.init_method, func=train)
> File "slowfast/utils/misc.py", line 276, in launch_job
> func(cfg=cfg)
> File "tools/train_net.py", line 351, in train
> model = build_model(cfg)
> File "slowfast/models/build.py", line 31, in build_model
> model = MODEL_REGISTRY.get(name)(cfg)
> File "slowfast/models/video_model_builder.py", line 156, in **init**
> self._construct_network(cfg)
> File "slowfast/models/video_model_builder.py", line 194, in _construct_network
> norm_module=self.norm_module,
> File "slowfast/models/stem_helper.py", line 75, in **init**
> self._construct_stem(dim_in, dim_out, norm_module)
> File "slowfast/models/stem_helper.py", line 88, in _construct_stem
> norm_module,
> File "slowfast/models/stem_helper.py", line 154, in **init**
> self._construct_stem(dim_in, dim_out, norm_module)
> File "slowfast/models/stem_helper.py", line 166, in _construct_stem
> num_features=dim_out, eps=self.eps, momentum=self.bn_mmt
> File "slowfast/models/batchnorm_helper.py", line 186, in __init__self.num_sync_devices,
> AssertionError: (1, 4)
> 
> Can you help shed some light on this?
> Thanks in advance.
> Best regards
I have the same problem. How did you solve it?

**Comment by tianqiaotiemo** [comment]
I have the same problem. How did you solve it?

**Comment by richanghmc** [comment]
Same here, I have that problem as well and I was wondering if it was ever solved.

**Comment by alpargun** [comment]
I fixed this issue by assigning the same value to `BN.NUM_SYNC_DEVICES` as `NUM_GPUS`. So, the corresponding variables in the config file looks like this (as I am using 1 GPU):

```
BN:
  NUM_SYNC_DEVICES: 1

NUM_GPUS: 1
```
