### ISSUE TITLE
About reproducing the 24.9 mAP on AVA with R50

### ISSUE THREAD

**Issue by banshee1** [facebookresearch/SlowFast#228]
Hi, thanks for sharing the excellent works.
Now I am confused with some questions.
I am trying to reproduce the results of 24.9 mAP as you reported on AVA with R50. The question is I am not sure which pretrained model to use.
![image](https://user-images.githubusercontent.com/31362830/85411624-272c6280-b59b-11ea-87cc-653f1b48bb6f.png)
It seems that pretrained model isn't released?

**Comment by banshee1** [comment]
And moreover, the codes are built by REGISTRY and I want to build with source code. I find that there're codes for building model in 'slowfast' folder, can I build slowfast with those codes?
Thanks!

**Comment by sdjsngs** [comment]
for this result, did  you use pretrain model like  
SlowFast | R101 | Kinetics 600 | 8 x 8 | 28.2 | 2.1 | link
-- | -- | -- | -- | -- | -- | --
SlowFast | R101 | Kinetics 600 | 8 x 8 | 29.1 | 2.2 | link
in model zoo ? did this model need to train on AVA dataset again or it can just  do the valdation and test ? 
thank you

**Comment by takatosp1** [comment]
Hi,
Thanks for playing with PySlowFast!
If you want to get the pretrained model to inference on AVA, you could get the pretrain model on the right :)

**Comment by galsk87** [comment]
Hi I used the pre-trained models and got 
21.4 with 32x2 and 16.8 with 64x2.

Can you please share the configuration needed to reproduce the results accordingly?
