### ISSUE TITLE
action detection on  custom dataset   like the deom.jif 

### ISSUE THREAD

**Issue by sdjsngs** [facebookresearch/SlowFast#232]
Hi， dose anyone have implement  the video detection on  cuntom dataset,  i want to test on some  videos  without bbox, how can i  make this ?   if anyone konw it or this can not be done in this codebase, please tell me, thank you.

**Comment by takatosp1** [comment]
Hi @sdjsngs,

Thanks for interested in using PySlowFast, we will release the demo script in 4-6 weeks :)

Thanks,
Haoqi
