### ISSUE TITLE
how to change model's input

### ISSUE THREAD

**Issue by habatua** [facebookresearch/SlowFast#235]
Hi.When I used a video as a demo test, I found that the input to the magic slow channel was 8 frames, the fast channel was 32 frames, and after passing through the AvgPool layer, the slow and fast layers were both 1 frame. Are 8 and 32 frames the number of one clip? How do I pass the entire number of frames into the model? 
Could you help me?Thanks!

**Comment by SiftingSands** [comment]
The dataloader should read in the entire video and pass 32 and 8 frames to the model (usually after 2x subsampling). Where those frames are taken from the video is up to the dataloader specifics. For example, ensembling during testing takes N clips evenly spaced throughout the original video.

**Comment by habatua** [comment]
> 数据加载器应读取整个视频，并将32帧和8帧传递给模型（通常在2x二次采样后）。这些帧是从视频中获取的，具体取决于数据加载器。例如，在测试过程中进行合奏需要在整个原始视频中均匀分布N个剪辑。

Thank you very much.If possible, could you introduce the test's sampling process?

**Comment by SiftingSands** [comment]
Look at the kinetics dataloader as a baseline example. [kinetics.py](https://github.com/facebookresearch/SlowFast/blob/master/slowfast/datasets/kinetics.py)
