### ISSUE TITLE
what's the difference between kinetics_val and kinetics_test dataset

### ISSUE THREAD

**Issue by ShoufaChen** [facebookresearch/SlowFast#240]
Hi,

From the paper description, I think the model is trained on `kinetics train` split and referenced  on `kinetics validation` dataset. 

From the this implementation, I noticed that the split modes includes `train`, `val`  and `test`. 

So, I wonder what's the `test` split dataset for Kinetics?

Or is the `test.csv` totally the same as `val.csv`?

Thanks.

**Comment by takatosp1** [comment]
Hi @ShoufaChen 

Thanks for playing with PySlowFast! 
We currently support to do training (on train.csv), evaluation (after certain epoch of training on val.csv), and testing (after the entire training is done on test.csv).
We currently performing testing on val set from Kinetics, and we don't have labels fro Kinetics testset.
