### ISSUE TITLE
when i  do  “e. Install nms for person estimation”，there is no file which names "nms". who can help me ?

### ISSUE THREAD

**Issue by nianjiuhuiyi** [facebookresearch/SlowFast#243]
when i do as GETTING_STARTED.md, 
 but
 e. Install nms for person estimation:
`cd mmskeleton/ops/nms/           
python setup_linux.py develop
cd ../../../`

 i dont find a file which names "nms"
so what happen? what should i do ?

**Comment by takatosp1** [comment]
Hi @nianjiuhuiyi ,

Thanks for playing with PySlowFast, maybe you could try to install detectron2?

Thanks,
