### ISSUE TITLE
epochs for the pre-trained models in MODEL_ZOO

### ISSUE THREAD

**Issue by ShoufaChen** [facebookresearch/SlowFast#245]
Thanks for your work! 

For Kinetics, I noticed that `MAX_EPOCH: 196`. But the related papers mention 256 epochs for Kinetics.

How many epochs does it need to obtain the models provided in the Model_ZOO?

**Comment by takatosp1** [comment]
Hi @ShoufaChen,

There were two training protocol, one is training for 196 epochs and another is training with 250 epochs. The model zoo was trained with 196 epochs.
