### ISSUE TITLE
How I can train SLOWFAST_8x8_R50 on 1 class?  

### ISSUE THREAD

**Issue by Vova-B** [facebookresearch/SlowFast#247]
Hi. 
I want to use a model to classify 1 class. I use pre-trained weights for SLOWFAST_8x8_R50 to do this but get various errors. Ultimately, I get an error from the metrics script in the ks list. How can I train this model in 1 sclass?
Thanks

**Comment by takatosp1** [comment]
Hi @Vova-B,

You might want to have 2 output from the fc, 0 for the class, and 1 for no the class.

Thanks,
Haoqi
