### ISSUE TITLE
DATA.CROP_SIZE v.s. DATA.TRAIN_CROP_SIZE

### ISSUE THREAD

**Issue by ShoufaChen** [facebookresearch/SlowFast#249]
Thanks for your work.

The `DATA.CROP_SIZE` is only used for calculating the pool kernel size of the header.
I wonder what's the specific purpose of using `DATA.CROP_SIZE` rather than `DATA.TRAIN_CROP_SIZE` because I noticed that they're always the same?

The other question is that if I use`DATA.TRAIN_CROP_SIZE = 160`, what's the corresponding `DATA.CROP_SIZE` value? 

https://github.com/facebookresearch/SlowFast/blob/0a7067b85091d695955a9accde2d9f1256ab9229/slowfast/models/video_model_builder.py#L569-L571

**Comment by takatosp1** [comment]
Hi @ShoufaChen,

Thanks for playing with PySlowFast. Training on 160 input dimension will requires a different recipe. If you want to keep the FLOPs of the model, then you might want to use a smaller pooling size.
Thanks,
haoqi

**Comment by Shumpei-Kikuta** [comment]
@ShoufaChen Have you solved above question: "if I useDATA.TRAIN_CROP_SIZE = 160, what's the corresponding DATA.CROP_SIZE value?"?
I came across the same problem.

I think we just change the `DATA.CROP_SIZE` the same value as `DATA.TRAIN_CROP_SIZE` (in this case, 160).
Is my understanding right?

**Comment by ShoufaChen** [comment]
Hi, @Shumpei-Kikuta 

I agree with you that 'we just change the DATA.CROP_SIZE the same value as DATA.TRAIN_CROP_SIZE'.

However, a long time passed and I am not definitely sure.
