### ISSUE TITLE
X3D Architecture

### ISSUE THREAD

**Issue by yldrmBtn** [facebookresearch/SlowFast#250]
I am very interested in X3D: Expanding Architectures for Efficient Video Recognition paper and wonder when will its implementation be available in SlowFast repository. Is it in progress or is there any timeline for X3D architecture implementation?

**Comment by takatosp1** [comment]
Hi, @yldrmBtn 

Thanks for sharing your question! We are planning to release the X3D code soon. (the code has been prepared just waiting for approval)

**Comment by hengxiangYao** [comment]
> Hi, @yldrmBtn
> 
> Thanks for sharing your question! We are planning to release the X3D code soon. (the code has been prepared just waiting for approval)

Hi, @takatosp1 , looking forward to your X3D code, hope we can see the code soon.
