### ISSUE TITLE
error raises when adding multigrid to training(ZeroDivisionError: division by zero`)

### ISSUE THREAD

**Issue by ystsaan** [facebookresearch/SlowFast#257]
I'm applying pyslowfast to my custom dataset, modifying SLOWFAST_8x8_R50_stepwise_multigrid.yaml. The interesting thing is when I delete the  
```
MULTIGRID:
  SHORT_CYCLE: True
  LONG_CYCLE: True
```
in  SLOWFAST_8x8_R50_stepwise_multigrid.yaml, everything works fine. However, with MULTIGRID config added in SLOWFAST_8x8_R50_stepwise_multigrid.yaml, the below error raises. 

```
Traceback (most recent call last):
  File "tools/run_net.py", line 39, in <module>
    main()
  File "tools/run_net.py", line 25, in main
    launch_job(cfg=cfg, init_method=args.init_method, func=train)
  File "/home/anaconda3/envs/multigrid/lib/python3.6/site-packages/slowfast-1.0-py3.6.egg/slowfast/utils/misc.py", line 282, in launch_job
  File "/home/Downloads/SlowFast-master/tools/train_net.py", line 431, in train
    train_loader, model, optimizer, train_meter, cur_epoch, cfg, writer
  File "/home/Downloads/SlowFast-master/tools/train_net.py", line 157, in train_epoch
    train_meter.log_epoch_stats(cur_epoch)
  File "/home/anaconda3/envs/multigrid/lib/python3.6/site-packages/slowfast-1.0-py3.6.egg/slowfast/utils/meters.py", line 548, in log_epoch_stats
ZeroDivisionError: division by zero
```

It seems still some problems with multigrid training.

By the way, I keep everything exactly what it was in SLOWFAST_8x8_R50_stepwise_multigrid.yaml except for turning down test mode, turning on train mode, TRAIN.BATCH_SIZE=4, MODEL.NUM_CLASSES=5, NUM_GPUS=1.

**Comment by ystsaan** [comment]
Question closed, after checking ShortCycleBatchSampler class in multigrid_helper.py, I found error occurs due to too few training videos. The created ShortCycleBatchSampler object will return a zero len if too few training videos like 20 videos were provided.

```
def __len__(self):
    avg_batch_size = sum(self.batch_sizes) / 3.0
    if self.drop_last:
        return int(np.floor(len(self.sampler) / avg_batch_size))
    else:
        return int(np.ceil(len(self.sampler) / avg_batch_size))
```

**Comment by bqhuyy** [comment]
@ystsaan I met the same problem. Can you tell me how to fix this? I'm training on Kinetics 400. My config (4 x RTX 6000) : TRAIN.BATCH_SIZE 56, NUM_GPUS 4, DATA_LOADER.NUM_WORKERS 1

**Comment by ystsaan** [comment]
> @ystsaan I met the same problem. Can you tell me how to fix this? I'm training on Kinetics 400. My config (4 x RTX 6000) : TRAIN.BATCH_SIZE 56, NUM_GPUS 4, DATA_LOADER.NUM_WORKERS 1

This problem occurs when batchsize is big or the number of training videos is small. Try a small batchsize like 4 or 8 and see if the problem is still there.  

Simutaneously, DATA_LOADER.NUM_WORKERS i set is by default, which is 8.

If a small batchsize does not work, you'd better trace the py file where error occurs. You can make pyslowfast print something to debug step by step by simply adding print() at any position you like, recompiling it and running the training command.
