### ISSUE TITLE
Error: AVAMeter has no attribute video_preds

### ISSUE THREAD

**Issue by FabiTheGabi** [facebookresearch/SlowFast#259]
Dear SlowFast-Team,

this line of code results into an error, because the AVAMeter-class has no attribute video_preds.

https://github.com/facebookresearch/SlowFast/blob/cec2d0a3f17e5d1528098999300332e6aa1066ce/tools/test_net.py#L107

Thus it would only work, if "not cfg.DETECTION.ENABLE". 

It would be awesome, if you would implement this feature also for detection tasks.

May I ask, whether you are planning to add TENSORBORAD.HITOGRAM and TENSORBOARD.CONFUSION_MATRIX for detection tasks?

Thank you a lot for your great work.

**Comment by FabiTheGabi** [comment]
This line of code results into the same error.

https://github.com/facebookresearch/SlowFast/blob/cec2d0a3f17e5d1528098999300332e6aa1066ce/tools/train_net.py#L256

**Comment by lequytra** [comment]
Hi @FabiTheGabi, 

Thank you for bringing the issue to our attention. We just added a small fix to avoid this error. For the being, we don't have plans to add confusion matrix visualization for detection tasks since it doesn't work quite well with multi-label dataset.

**Comment by FabiTheGabi** [comment]
Thank you a lot for your quick fix and the explanation 👍
