### ISSUE TITLE
Training with the new data set

### ISSUE THREAD

**Issue by habatua** [facebookresearch/SlowFast#260]
According to the previous feedback, I learned that the network can be fine-tuned only by changing the script. I retrained by loading the pre-training model and changing the categories. My part of configuration file is as follows:
TRAIN:
  ENABLE: True
  DATASET: kinetics
  BATCH_SIZE: 16
  EVAL_PERIOD: 10
  CHECKPOINT_PERIOD: 1
  CHECKPOINT_FILE_PATH: "/home/SlowFast-master/checkpoints/SLOWFAST_8x8_R50.pkl"
  CHECKPOINT_TYPE: caffe2
  AUTO_RESUME: True
MODEL:
  NUM_CLASSES: 54
  ARCH: slowfast
  MODEL_NAME: SlowFast
  LOSS_FUNC: cross_entropy
  DROPOUT_RATE: 0.5
BN:
  USE_PRECISE_STATS: True
  NUM_BATCHES_PRECISE: 200
  MOMENTUM: 0.1
  WEIGHT_DECAY: 0.0
SOLVER:
  BASE_LR: 0.1
  LR_POLICY: cosine
  MAX_EPOCH: 10
  MOMENTUM: 0.9
  WEIGHT_DECAY: 1e-4
  WARMUP_EPOCHS: 34.0
  WARMUP_START_LR: 0.01
  OPTIMIZING_METHOD: sgd

[INFO: logging.py:   96]: json_stats: {"_type": "train_iter", "epoch": "1/10", "eta": "21:32:18", "gpu_mem": "2.95 GB", "iter": "2820/15328", "loss": 2.372385, "lr": 0.010133, "time_diff": 0.515342, "top1_err": 71.875000, "top5_err": 31.250000}
[INFO] slowfast.utils.logging:   96: json_stats: {"_type": "train_iter", "epoch": "1/10", "eta": "21:32:18", "gpu_mem": "2.95 GB", "iter": "2820/15328", "loss": 2.372385, "lr": 0.010133, "time_diff": 0.515342, "top1_err": 71.875000, "top5_err": 31.250000}

[INFO] slowfast.utils.logging:   96: json_stats: {"_type": "train_iter", "epoch": "3/10", "eta": "15:26:11", "gpu_mem": "2.95 GB", "iter": "2490/15328", "loss": 2.177407, "lr": 0.011561, "time_diff": 0.462583, "top1_err": 65.625000, "top5_err": 21.875000}
[INFO: logging.py:   96]: json_stats: {"_type": "train_iter", "epoch": "3/10", "eta": "14:58:03", "gpu_mem": "2.95 GB", "iter": "2500/15328", "loss": 2.209405, "lr": 0.011562, "time_diff": 0.448564, "top1_err": 62.500000, "top5_err": 31.250000}

Loss is basically maintained at about 2，Is there anything wrong with it？

**Comment by HHHcwb** [comment]
Hello,I think it may be related to the network parameters you set, such as learning rate, etc.

Can you tell me how to use the pretrian model on my own dataset? I do not know how to fine-tuned the model.

And by the way did you test the pretrain model on the single video，I use the SLOWFAST_8x8_R50.pkl to test, but it went so fast and I could not see what happened. And I got an error said my cuda ran out of memory, how to sovle this problem?
Thank you!

**Comment by habatua** [comment]
@HHHcwb 
Hi,
I pretain my dataset by loading SLOWFAST_8x8_R50.pkl,and change dataloader,change classes. But Unfortunately, the loss doesn't fall ,maybe there are other changes that need to be made.I'm sorry I can't ensure the mothod is true beacause I don‘t verify it.
 And if you want to test demo, you can have a test.csv that contains a video. As  for cuda ran out of memory,Can you change batch size to 1?

**Comment by HHHcwb** [comment]
Thanks a lot!! 
I solved the memory problem of cuda by adding with torch.no_grad():  in run_net.

**Comment by HHHcwb** [comment]
@habatua 
Can I ask you how to open and modify the pretrain model SLOWFAST_8x8_R50.pkl, when I use 'torch.load', encounter an error, UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd4 in position 1: invalid continuation byte

I think if I want to use the pretrain model I must let it fit my dataset so I must fine-tuned the model.

**Comment by wwdok** [comment]
@habatua Hi, guy, do you enable DETECTION and where do you place your classnames.json ?

**Comment by Abiems** [comment]
@habatua  Hi , can you tell me please how did you fine tune the model ?
