### ISSUE TITLE
Train on ucf-101 

### ISSUE THREAD

**Issue by HHHcwb** [facebookresearch/SlowFast#263]
How to use the pretain model to train on my own dataset.
Such as ucf-101.

**Comment by HHHcwb** [comment]
I already sovle the problem

**Comment by cong235** [comment]
> I already sovle the problem

Hi @HHHcwb , can you share your workflow?

**Comment by slighting666** [comment]
> I already sovle the problem
@cong235 @HHHcwb 

can you share your workflow?
