### ISSUE TITLE
where can I find the ava.names

### ISSUE THREAD

**Issue by opentld** [facebookresearch/SlowFast#269]
When running ava camero detection demo, I have to set the SLOWFAST_32x2_R101_50_50.yaml, LABEL_FILE_PATH, but I don't know where can I download the label file?

@likethesky @Celebio @colesbury @pdollar @alexholdenmiller

**Comment by opentld** [comment]
{
"bend/bow (at the waist)": 1,
"crawl": 2,
"crouch/kneel": 3,
"dance": 4,
"fall down": 5,
"get up": 6,
"jump/leap": 7,
"lie/sleep": 8,
"martial art": 9,
"run/jog": 10,
"sit": 11,
"stand": 12,
"swim": 13,
"walk": 14,
"answer phone": 15,
"brush teeth": 16,
"carry/hold (an object)": 17,
"catch (an object)": 18,
"chop": 19,
"climb (e.g., a mountain)": 20,
"clink glass": 21,
"close (e.g., a door, a box)": 22,
"cook": 23,
"cut": 24,
"dig": 25,
"dress/put on clothing": 26,
"drink": 27,
"drive (e.g., a car, a truck)": 28,
"eat": 29,
"enter": 30,
"exit": 31,
"extract": 32,
"fishing": 33,
"hit (an object)": 34,
"kick (an object)": 35,
"lift/pick up": 36,
"listen (e.g., to music)": 37,
"open (e.g., a window, a car door)": 38,
"paint": 39,
"play board game": 40,
"play musical instrument": 41,
"play with pets": 42,
"point to (an object)": 43,
"press": 44,
"pull (an object)": 45,
"push (an object)": 46,
"put down": 47,
"read": 48,
"ride (e.g., a bike, a car, a horse)": 49,
"row boat": 50,
"sail boat": 51,
"shoot": 52,
"shovel": 53,
"smoke": 54,
"stir": 55,
"take a photo": 56,
"text on/look at a cellphone": 57,
"throw": 58,
"touch (an object)": 59,
"turn (e.g., a screwdriver)": 60,
"watch (e.g., TV)": 61,
"work on a computer": 62,
"write": 63,
"fight/hit (a person)": 64,
"give/serve (an object) to (a person)": 65,
"grab (a person)": 66,
"hand clap": 67,
"hand shake": 68,
"hand wave": 69,
"hug (a person)": 70,
"kick (a person)": 71,
"kiss (a person)": 72,
"lift (a person)": 73,
"listen to (a person)": 74,
"play with kids": 75,
"push (another person)": 76,
"sing to (e.g., self, a person, a group)": 77,
"take (an object) from (a person)": 78,
"talk to (e.g., self, a person, a group)": 79,
"watch (a person)": 80
}


here is the ava.names

**Comment by alexholdenmiller** [comment]
Hi @opentld! No need to tag anyone when you open an issue, the repository maintainers will see the open issue (I also don't work on SlowFast personally)

**Comment by wzan0001** [comment]
It's cool!
