### ISSUE TITLE
Estimated Training Time & CPU Usage

### ISSUE THREAD

**Issue by chongruo** [facebookresearch/SlowFast#27]
Thanks for your work!  When we train SLOWFAST_4x16_R50 on Kinetics with 8 gpus, we find the estimated training time is fluctuated widely, and all cpus are running at 100%.  Not sure whether they are normal behaviors ?

As shown in the figure below, the eta becomes 30 days from 3 days, then goes back to normal. Based on the time interval (saving time) between two checkpoints, the training will take more than 10 days, rather than 5 days shown in the log.

<img width="1310" alt="Screen Shot 2019-11-08 at 5 42 12 PM" src="https://user-images.githubusercontent.com/6445892/68520783-795c8580-024f-11ea-89ab-e32a5c8c124c.png">

All cpu cores are running up to 100% usage. 
![image](https://user-images.githubusercontent.com/6445892/68520789-8da08280-024f-11ea-8c55-44779c5899e9.png)

GPU usage is quite high. Do you think they are normal behaviors, or something was not be set properly?  Our batchsize is 96. Looking forward to your advice. Thanks!

**Comment by takatosp1** [comment]
Hi

Thanks for using the codebase!
It looks you have a CPU bound on video deciding.
You might play with the number of NUM_WORKER (you probably want a smaller number than what you have now).

**Comment by takatosp1** [comment]
If you increase the batch size (normally 64), then each of the iteration will take longer. 
For the estimated time, what you see looks normal to me, currently we are using the delta of each iteration to estimate the overall time, I will make it to average if you found the number fluctuated.
