### ISSUE TITLE
small gap in testing

### ISSUE THREAD

**Issue by Arthurlxy** [facebookresearch/SlowFast#28]
Hi Thanks for releasing the code
I tested the slowfast 50 model on K400 with Pytorch 1.3.
Both 8x8 model and 4x16 model gets 1.6% lower top1 acc. compared with reported scores.

I am trying to figure out the cause of this small gap.
Does the official label follow the alphabetic order?
Is this something expected for weights converted from caffe?

Thanks

**Comment by takatosp1** [comment]
Could you share the name of the config you were using?

**Comment by Arthurlxy** [comment]
> No the performance shall be the same as reported (might have a +-0.3% gap because of C2 convert).
> I suspect you used a wrong frame length.
> Could you share the path to the config you were using?
> Also could you share how large is your Val set. Could I also assume you were using 30 clip testing. Also could you confirm the videos from your Val set are all decodable.

Hi Thanks for your reply
My val set has 19768 videos and they are decodable.
I used the 30 clip testing.
The input has 32 frames with sample rate at 2.
I used this config:
configs/Kinetics/c2/SLOWFAST_8x8_R50.yaml

Thanks for your help

**Comment by takatosp1** [comment]
Could you share me what is the original resolution of your val video?

**Comment by takatosp1** [comment]
I have tested on my local machine again and the numbers matched. I'll close the task since it seems to likely there are some config/ setting wrong on your side. I'll keep tracking this task to help you match the performance.

**Comment by chongruo** [comment]
#42 it may have a better val result.
