### ISSUE TITLE
X3D is slower than slowfast

### ISSUE THREAD

**Issue by gooners1886** [facebookresearch/SlowFast#286]
I compare the speed between X3D_L  and  SLOWFAST_8x8_R50 on Kinetics-400 dataset. Surprisingly,  although the GFlops of X3D_L is smaller(24.8 vs 65.7) , it runs about 3x slower than SLOWFAST_8x8_R50. 

Is there something important need to do to speed up the inference of X3D_L?

**Comment by feichtenhofer** [comment]
Anyone running into this issue, please have a look at https://github.com/facebookresearch/SlowFast/blob/master/projects/x3d/

**Comment by yztongzhan** [comment]
@feichtenhofer , I try the 3D depthwise convolution implementation (https://github.com/pytorch/pytorch/pull/40801) for X3D, but has not obviously acceleration.

**Comment by feichtenhofer** [comment]
Applying the patch works for me, you might be missing some part of the code? For example the training time per iteration of X3D-L should decrease by over 3x compared to the version without the patch.

**Comment by leafxx** [comment]
> @feichtenhofer , I try the 3D depthwise convolution implementation ([pytorch/pytorch#40801](https://github.com/pytorch/pytorch/pull/40801)) for X3D, but has not obviously acceleration.

me, too.

**Comment by youngwanLEE** [comment]
@feichtenhofer @yztongzhan @leafxx 

What pytorch version you apply for patch?

**Comment by nik13** [comment]
How do i apply that patch?

**Comment by youngwanLEE** [comment]
@nik13 
I recommend the instruction of [VoV3D](https://github.com/youngwanLEE/VoV3D/blob/main/INSTALL.md#installation).

**Comment by RussellXie7** [comment]
> @nik13 @Polkach @gurkirt
> I recommend the instruction of [VoV3D](https://github.com/youngwanLEE/VoV3D/blob/main/INSTALL.md#installation).

I thought the feature in  (pytorch/pytorch#40801)  is already merged with pytorch 1.9.0 as indicated from https://github.com/pytorch/pytorch/pull/51027 ?  Or is VoV3D somehow different?

**Comment by makecent** [comment]
@feichtenhofer According to this [PR](https://github.com/pytorch/pytorch/pull/51027), the slow seperable convolution is fixed from PyTorch 1.9. 

But when I test the X3D with pytorch 1.11.0, it's still very slow. The runtime of a X3D-S is similar to the I3D, despite that the X3D-S has much fewer params and FLOPs.
