### ISSUE TITLE
replace detectron2 with custom model

### ISSUE THREAD

**Issue by nikky4D** [facebookresearch/SlowFast#289]
Is there an example where I can replace detectron2 with my own object detection model, for example yolov5 trained on custom dataset? or must I use detectron2 finetuned on this custom dataset?

**Comment by lyxok1** [comment]
Maybe you can directly organize the format of output object proposals from your customized detector as the one in this repo, like [this](https://dl.fbaipublicfiles.com/video-long-term-feature-banks/data/ava/annotations/ava_train_predicted_boxes.csv)

**Comment by lyxok1** [comment]
> Is there an example where I can replace detectron2 with my own object detection model, for example yolov5 trained on custom dataset? or must I use detectron2 finetuned on this custom dataset?

 Maybe you can directly organize the format of output object proposals from your customized detector as the one in this repo, like [this](https://dl.fbaipublicfiles.com/video-long-term-feature-banks/data/ava/annotations/ava_train_predicted_boxes.csv)

**Comment by nikky4D** [comment]
Thanks. But then, where would I pass these object proposals ? which file takes in the proposals?
