### ISSUE TITLE
[WARNING: decoder.py:   89]: Failed to parse extradata

### ISSUE THREAD

**Issue by Shumpei-Kikuta** [facebookresearch/SlowFast#29]
Hello, thank you for your work!

I encountered ffmpeg warning, saying `[WARNING: decoder.py:   89]: Failed to parse extradata`.
I've just looked up what causes this warning, but I don't have any ideas.

Because it's just the warning, can I just ignore them? Or I might make some mistakes?

Thank you for your great work again!

**Comment by takatosp1** [comment]
Hi,
Thanks for using the codebase. This is because the version of pyav and ffmpeg you use, you can simply ignore it.
