### ISSUE TITLE
About X3D checkpoints

### ISSUE THREAD

**Issue by kennymckormick** [facebookresearch/SlowFast#290]
Thanks for releasing the code and checkpoints for X3D. However, I find that the released checkpoints can not be loaded with torch or pickle (2 ways implemented in ur codebase). Would u please share the proper way to load ur X3D checkpoints?

**Comment by githubsora** [comment]
I meet same problem. I cannot find the way to load x3d_*.pyth.

**Comment by yztongzhan** [comment]
@kennymckormick you can try the latest version of PyTorch.
