### ISSUE TITLE
Config for Charades and AVA dataset ? 

### ISSUE THREAD

**Issue by v-wewei** [facebookresearch/SlowFast#3]
HIi, Great work for video understanding ! 
will you pls release the config for Charades dataset  and AVA dataset .Since i am able to get almost the same result on Kinetics-400, but not able to get the comparble result on Charades dataset with finetuned slowonly-res101, maybe i have just miss some important thing , thanks very much !

**Comment by takatosp1** [comment]
Hi,
Thanks for asking! we are going to release the AVA training with the pretrained model soon!
