### ISSUE TITLE
Extracting features from any layer besides the output

### ISSUE THREAD

**Issue by WinckelData** [facebookresearch/SlowFast#300]
**Is it possible to extract the output of any other layer than the output and if so how?**

I am currently working on my Bachelor Thesis and trying out this fantastic project. I'd like to try a few experiments with the output of the last layer before the fc network and the last layer of the fc network (before the output). Therefore i'm trying to extract those feature vectors. Maybe someone can help me here as my pytorch knowledge is yet limited.

**Comment by abhaygargab** [comment]
Were you able to figure this out?

**Comment by WinckelData** [comment]
Yes.
I changed the test_net.py so that i attached Pytorch hooks to the layers i wanted to extract the features of. 
After the forward pass, i saved them as np arrays for further analysis. 
This way i implemented a Video Similarity Search by comparing the featurevectors of the last Linear Layer with several metrics.

**Comment by Rasipuram** [comment]
Can you please post the code you changed in test_net.py for extracting features?
