### ISSUE TITLE
Grad-CAM: colormap is very slow

### ISSUE THREAD

**Issue by Shumpei-Kikuta** [facebookresearch/SlowFast#312]
Thank you so much for your great work!
I am impressed with the new support of Grad-CAM!

I am using Grad-CAM option, and I noticed generating heatmap using colormap is really slow.
It takes more than 10 minutes to show the only single video(spatially cropped and time sampled).
I realized the following part of the code is the cause of the problem:
https://github.com/facebookresearch/SlowFast/blob/fd41618191d3c21c1ca21a61369ce9917646cf9c/slowfast/visualization/gradcam_utils.py#L163

Would you provide me with any solutions?

**Comment by dianyo** [comment]
I've try this and it's much faster than pass tensor to colomap function. Not sure what colormap function will do when got tensor as input. 
```heatmap = self.colormap(localization_map.numpy())```

**Comment by Shumpei-Kikuta** [comment]
@dianyo Thank you for sharing your knowledge.
I'll try your solution later.

**Comment by Shumpei-Kikuta** [comment]
@dianyo Your advice really works for me!
Before: 10 minutes per video
After: 10 seconds per video
Thank you a lot!!

**Comment by Shumpei-Kikuta** [comment]
@dianyo 
I think you should send a pull request to solve this problem.
It must be a big help for everyone.

**Comment by asafDahan** [comment]
Thanks! 
worked like magic
