### ISSUE TITLE
Can you provide a Dockerfile ?

### ISSUE THREAD

**Issue by yangadan** [facebookresearch/SlowFast#32]
Can you provide a Dockerfile for the reseaon I'v failed to configure the environment?

**Comment by Shumpei-Kikuta** [comment]
@yangadan Sorry to cut you off. 
For your reference, you can easily write Dockerfile by using `pytorch/pytorch:1.3-cuda10.1-cudnn7-runtime` as the base image, and `pip install` as this repo requires.
I successfully build the image and run on the docker container.

**Comment by yangadan** [comment]
I made it. Thanks for your help

**Comment by dav-ell** [comment]
@yangadan @Shumpei-Kikuta Can you provide the Dockerfile you created? This would be a nice addition to `GETTING_STARTED.md` also, a section near the top, perhaps, saying, "Using Docker" and referencing the Dockerfile with build commands.

**Comment by Shumpei-Kikuta** [comment]
@dev-ell
Sure. 
I provide you temporarily with my Dockerfile.
Please be careful because I don't think my Dockerfile creates the best image(not memory-efficient, or follow suit).

```Dockerfile
FROM pytorch/pytorch:1.3-cuda10.1-cudnn7-runtime

ARG project_dir=/app/
WORKDIR $project_dir
ADD setup* $project_dir 
ADD slowfast ${project_dir}/slowfast

RUN apt-get update && apt-get upgrade -y \
 && apt-get install -y \
    git \
    make \
    build-essential \
    libssl-dev \
    zlib1g-dev \
    libbz2-dev \
    libreadline-dev \
    libsqlite3-dev \
    wget \
    curl \
    llvm \
    libncurses5-dev \
    libncursesw5-dev \
    xz-utils \
    tk-dev \
    libffi-dev \
    liblzma-dev \
    gcc \
 && pip install \
    numpy \
    torchvision==0.4.1 \
    'git+https://github.com/facebookresearch/fvcore' \
    simplejson \
    sklearn \
    pandas \
&& conda install av -c conda-forge \
&& python setup.py build develop
```

**Comment by dav-ell** [comment]
Thanks @Shumpei-Kikuta. Is it missing detectron2, though? I get this error when I run it:

```
Searching for detectron2
Reading https://pypi.org/simple/detectron2/
No local packages or working download links found for detectron2
error: Could not find suitable distribution for Requirement.parse('detectron2')
```

**Comment by Shumpei-Kikuta** [comment]
@dav-ell ah, I noticed my Dockerfile isn't latest, some commits were added after I created Dockerfile.
I guess you just add packages my Dockerfile doesn't provide to your Dockerfile.
It should be like this:

```
FROM pytorch/pytorch:1.3-cuda10.1-cudnn7-runtime

ARG project_dir=/app/
WORKDIR $project_dir
ADD setup* $project_dir 
ADD slowfast ${project_dir}/slowfast

RUN apt-get update && apt-get upgrade -y \
 && apt-get install -y \
    git \
    make \
    build-essential \
    libssl-dev \
    zlib1g-dev \
    libbz2-dev \
    libreadline-dev \
    libsqlite3-dev \
    wget \
    curl \
    llvm \
    libncurses5-dev \
    libncursesw5-dev \
    xz-utils \
    tk-dev \
    libffi-dev \
    liblzma-dev \
    gcc \
 && pip install \
    numpy \
    torchvision==0.4.1 \
    opencv-python \
    tensorboard \
    moviepy \
    'git+https://github.com/facebookresearch/fvcore' \
    simplejson \
    sklearn \
    pandas \
&& conda install av -c conda-forge
# for detectron
&&     pip install -U torch torchvision cython
&&    pip install -U 'git+https://github.com/facebookresearch/fvcore.git' 
&& 'git+https://github.com/cocodataset/cocoapi.git#subdirectory=PythonAPI'
&&    git clone https://github.com/facebookresearch/detectron2 detectron2_repo
&&    pip install -e detectron2_repo
&& python setup.py build develop
```

Sorry, this is what I can support you the most.

**Comment by nik123** [comment]
Are there any changes of plans for Dockerfile? To train X3D I had to built PyTorch from sources with [this patch](https://github.com/pytorch/pytorch/pull/40801). Creating Dockerfile with PyTorch changes tock me quite a while. Having Dockerfile which already include these changes could save some time.
