### ISSUE TITLE
Please update AVA class names json file link

### ISSUE THREAD

**Issue by wwdok** [facebookresearch/SlowFast#322]
Hi, the `AVA class names json file` link (shown as below ) doesn't not exist, could you please update it ?
![image](https://user-images.githubusercontent.com/43233772/98655510-86d4b000-237a-11eb-89ea-40cedf93c67e.png)

**Comment by syn0419** [comment]
> Hi, the `AVA class names json file` link (shown as below ) doesn't not exist, could you please update it ?

Hi，May I ask what is the link of the screenshot above? I can't even find the link.Is it convenient for you to share it? Thank you!

**Comment by wwdok** [comment]
> > Hi, the `AVA class names json file` link (shown as below ) doesn't not exist, could you please update it ?
> 
> Hi，May I ask what is the link of the screenshot above? I can't even find the link.Is it convenient for you to share it? Thank you!

Of course，the link is at the bottom of [VISUALIZATION_TOOLS page](https://github.com/facebookresearch/SlowFast/blob/master/VISUALIZATION_TOOLS.md)

**Comment by syn0419** [comment]
> > > Hi, the `AVA class names json file` link (shown as below ) doesn't not exist, could you please update it ?
> > 
> > 
> > Hi，May I ask what is the link of the screenshot above? I can't even find the link.Is it convenient for you to share it? Thank you!
> 
> Of course，the link is at the bottom of [VISUALIZATION_TOOLS page](https://github.com/facebookresearch/SlowFast/blob/master/VISUALIZATION_TOOLS.md)

Thanks a lot!

**Comment by AlexanderMelde** [comment]
You can find mappings on the [AVA download page](https://research.google.com/ava/download.html#ava_actions_download), e.g. [`ava_action_list_v2.2.pbtxt`](https://research.google.com/ava/download/ava_action_list_v2.2.pbtxt).

Note you might need to reformat it to look like this: `{"ClassA": 0, "ClassB": 1, "ClassC": 2}`.

**Comment by wwdok** [comment]
@AlexanderMelde yeah, i finnaly did it like you said, the snippet code is :

```
import re
# reading the data from the file
with open('ava_action_list_v2.2.txt') as f:
    data = f.read()
    # print(data)
    result = re.findall(r'["](.*?)["]', data)  # find all contents inside double quote
    with open("result.json", "a") as file:  # a mean append
        for i in range(80):
            num = i+1
            file.write("\"\\\"" + result[i] + "\\\"\": " + str(num) + ", ")
```
but it still need some postprocess, like remove  last coma and add curly brace
