### ISSUE TITLE
UnicodeDecodeError when loading pickle file

### ISSUE THREAD

**Issue by AGrosserHH** [facebookresearch/SlowFast#33]
Hi all, 
I installed the required software with Python 3.7. I am trying to run a model from the model Zoo and have downloaded it. When I am running the command 

    python tools/run_net.py --cfg configs/Kinetics/I3D_NLN_8x8_R50.yaml DATA.PATH_TO_DATA_DIR ./files TEST.CHECKPOINT_FILE_PATH ./models/I3D_NLN_8x8_R50.pkl TRAIN.ENABLE False NUM_GPUS 1
    
I am getting the following error message:

![Bild2](https://user-images.githubusercontent.com/11669082/68935497-03997200-0799-11ea-9052-028c771e1149.png)

How can I solve this?

Cheers,
Andi

**Comment by takatosp1** [comment]
Hi, 
Thanks for using the codebase! 
You can follow the instruction in GETTING_STARTED, or here
https://github.com/facebookresearch/SlowFast/issues/19
