### ISSUE TITLE
the frame_num and sample_rate in c2/slowfast8x8

### ISSUE THREAD

**Issue by YilanWang** [facebookresearch/SlowFast#342]
the name of config and .pkl file of c2/SLOW_FAST_8X8_R50.YAML all shows the frame_num and sample_rate are 8, but in the config file, I noticed that num_frame is 32 and sample_rate is 2, what is the correct settings ? thx for your reply !

**Comment by YilanWang** [comment]
I see it, this is for slow branch……

**Comment by dragen1860** [comment]
the slow branch is 8 frames with 8 frames gap, while the fast branch is 32 frames with 2 frames gap.
