### ISSUE TITLE
How to calculate the mAP?

### ISSUE THREAD

**Issue by tomanick** [facebookresearch/SlowFast#38]
How to calculate the mAP in the Ch5. of the paper "SlowFast Networks for Video Recognition" ?

**Comment by takatosp1** [comment]
Hi,
Thanks for using the codebase.
In the SlowFast paper we followed the traditional of mAP calculation. Regarding to your question of how to calculate the mAP, here are some reference:

https://www.google.com/search?sxsrf=ACYBGNRuwhPnBoYiKxheHttjkXltCEIExQ%3A1574276791577&ei=t47VXb_HIoHT9APN4ruoDA&q=mean+average+precision+python&oq=mean+average+precision+python&gs_l=psy-ab.3..0l2j0i22i30l8.4808.6016..7233...0.0..0.88.552.7......0....1..gws-wiz.0pqTePh3tWE&ved=0ahUKEwj__sGHvvnlAhWBKX0KHU3xDsUQ4dUDCAs&uact=5

**Comment by tomanick** [comment]
Thanks for sharing !!
In addition, which metric did the authors used in the paper? Average Precision Classification or Average Precision Detection?
