### ISSUE TITLE
Dimensions don't match

### ISSUE THREAD

**Issue by JZArray** [facebookresearch/SlowFast#399]
When training Res-101, following error appears 

File "train_net.py", line 106, in train_epoch
    optimizer.step()
File "conda_envs/slowfast_37/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 15, in decorate_context
    return func(*args, **kwargs)
File "conda_envs/slowfast_37/lib/python3.7/site-packages/torch/optim/sgd.py", line 106, in step
    buf.mul_(momentum).add_(d_p, alpha=1 - dampening)
RuntimeError: The size of tensor a (80) must match the size of tensor b (10) at non-singleton dimension 0

How should I solve it?
Thanks

**Comment by JZArray** [comment]
solved

**Comment by Note-Liu** [comment]
How did you solve it？

**Comment by JZArray** [comment]
> How did you solve it？

**Comment by JZArray** [comment]
I have set 'TRAIN.CHECKPOINT_EPOCH_RESET' to true, then it works.

**Comment by Note-Liu** [comment]
> I have set 'TRAIN.CHECKPOINT_EPOCH_RESET' to true, then it works.

Thanks!
