### ISSUE TITLE
How to install detectron2 for Slowfast?

### ISSUE THREAD

**Issue by ashishsinghucd** [facebookresearch/SlowFast#402]
In the installation guide for Pyslowfast, it is mentioned that it requires pytorch1.3. However, detectron2 only supports pytorch>=1.6. Could you please let me know how can I install Slowfast?

**Comment by Mathuran-Mang** [comment]
I am also having trouble installing detectron2

**Comment by guli333** [comment]
same question

**Comment by haooooooqi** [comment]
Hi @ashishsinghucd 
Thanks for everyone playing with PySlowFast!
PySlowFast is compatible with the latest PyTorch version :)

Thanks,
Haoqi
