### ISSUE TITLE
Working on dataset other than humans

### ISSUE THREAD

**Issue by Vishak66** [facebookresearch/SlowFast#410]
Hello All,

Thank you for all the work done here! I was wondering if this network could work on datasets other than humans. For eg: can I have a custom dataset with cars and humans and their associated actions. Will this network be able to predict two completely different objects and their actions? Thank you

**Comment by haooooooqi** [comment]
Hey @Vishak66,
Thanks for playing with PySF! 
The network itself is task agnostic, so if you have the samples and the corresponding labels, if should able to predict the objects and actions!

Thanks,
Haoqi
