### ISSUE TITLE
MViT release schedule

### ISSUE THREAD

**Issue by youngwanLEE** [facebookresearch/SlowFast#415]
Hi, I'm very impressed by your MViT and wonder when MViT will be released.

**Comment by LinxiFan** [comment]
Same here, it's been more than 3 weeks since the README has been updated with "To be released in a week". I wonder if there is any update? Thanks!

**Comment by cecilia930426** [comment]
Same here

**Comment by yztongzhan** [comment]
Same here 😊

**Comment by g1910** [comment]
Same here 😊😊

**Comment by jianghaoyuan1994** [comment]
Same here😊😊😊

**Comment by tcapelle** [comment]
Lol, next week is taking forever.

**Comment by seandatasci** [comment]
who wants to be my favorite person and add it to the repo? :)

**Comment by haooooooqi** [comment]
Hi,
Thanks for the interest from everyone! Appreciated it 
Next week is finally coming :)

Thanks,
Haoqi

**Comment by seandatasci** [comment]
thanks new favorite person! :) @haooooooqi
