### ISSUE TITLE
Kinetics Dataset

### ISSUE THREAD

**Issue by chongruo** [facebookresearch/SlowFast#42]
Someone has posted a link to the kinetics dataset. 
https://github.com/facebookresearch/video-nonlocal-net/issues/67

It may have a better val result with pretrained model.

**Comment by tonysy** [comment]
Hi, could you share your script of test on val split. I use the following:
the test.csv is generated from the xiaolong's data , like:
```
/Datasets/kinetics-400/raw-part/compress/val_256/folding_napkins/_cHyoOCs8iQ.mp4 0
/Datasets/kinetics-400/raw-part/compress/val_256/folding_napkins/aK2ADoMh0ec.mkv 0
/Datasets/kinetics-400/raw-part/compress/val_256/folding_napkins/q-FubIQSMHw.mp4 0
........
```
The script is like this:
```
python tools/run_net.py \
  --cfg configs/Kinetics/c2/SLOWFAST_8x8_R50.yaml \
  DATA.PATH_TO_DATA_DIR ./data/kinetics \
  NUM_GPUS 4 \
  TEST.CHECKPOINT_FILE_PATH ./model_zoo/SLOWFAST_8x8_R50.pkl \
  TEST.CHECKPOINT_TYPE caffe2 \
  TEST.BATCH_SIZE 48 \
  TRAIN.ENABLE False
```
While I get a bad results
```
INFO: json_stats: {"split": "test_final", "top1_acc": "0.49", "top5_acc": "1.31"}

```
Thanks.

**Comment by xuyang67** [comment]
> Hi, could you share your script of test on val split. I use the following:
> the test.csv is generated from the xiaolong's data , like:
> 
> ```
> /Datasets/kinetics-400/raw-part/compress/val_256/folding_napkins/_cHyoOCs8iQ.mp4 0
> /Datasets/kinetics-400/raw-part/compress/val_256/folding_napkins/aK2ADoMh0ec.mkv 0
> /Datasets/kinetics-400/raw-part/compress/val_256/folding_napkins/q-FubIQSMHw.mp4 0
> ........
> ```
> 
> The script is like this:
> 
> ```
> python tools/run_net.py \
>   --cfg configs/Kinetics/c2/SLOWFAST_8x8_R50.yaml \
>   DATA.PATH_TO_DATA_DIR ./data/kinetics \
>   NUM_GPUS 4 \
>   TEST.CHECKPOINT_FILE_PATH ./model_zoo/SLOWFAST_8x8_R50.pkl \
>   TEST.CHECKPOINT_TYPE caffe2 \
>   TEST.BATCH_SIZE 48 \
>   TRAIN.ENABLE False
> ```
> 
> While I get a bad results
> 
> ```
> INFO: json_stats: {"split": "test_final", "top1_acc": "0.49", "top5_acc": "1.31"}
> ```
> 
> Thanks.

**Comment by xuyang67** [comment]
Can you provide the .csv file. Can you guide me to receive the files.

**Comment by wssxjtu** [comment]
> Hi, could you share your script of test on val split. I use the following: the test.csv is generated from the xiaolong's data , like:
> 
> ```
> /Datasets/kinetics-400/raw-part/compress/val_256/folding_napkins/_cHyoOCs8iQ.mp4 0
> /Datasets/kinetics-400/raw-part/compress/val_256/folding_napkins/aK2ADoMh0ec.mkv 0
> /Datasets/kinetics-400/raw-part/compress/val_256/folding_napkins/q-FubIQSMHw.mp4 0
> ........
> ```
> 
> The script is like this:
> 
> ```
> python tools/run_net.py \
>   --cfg configs/Kinetics/c2/SLOWFAST_8x8_R50.yaml \
>   DATA.PATH_TO_DATA_DIR ./data/kinetics \
>   NUM_GPUS 4 \
>   TEST.CHECKPOINT_FILE_PATH ./model_zoo/SLOWFAST_8x8_R50.pkl \
>   TEST.CHECKPOINT_TYPE caffe2 \
>   TEST.BATCH_SIZE 48 \
>   TRAIN.ENABLE False
> ```
> 
> While I get a bad results
> 
> ```
> INFO: json_stats: {"split": "test_final", "top1_acc": "0.49", "top5_acc": "1.31"}
> ```
> 
> Thanks.

请问，是否能够提供一下您生成包含路径及标签的csv的脚本么？感谢您
