### ISSUE TITLE
Webcam Implementation

### ISSUE THREAD

**Issue by Mathuran-Mang** [facebookresearch/SlowFast#423]
Is there anyway to use SlowFast to do real-time activity recognition using a webcam? I saw that @haooooooqi was working on a webcam demo, but I was not able to find the code for that demo anywhere.

**Comment by haooooooqi** [comment]
Hey @Mathuran-Mang,
Thanks for playing with PySlowFast :)
Have you get a chance to take a look at https://github.com/facebookresearch/SlowFast/blob/master/VISUALIZATION_TOOLS.md
Hope it helps :)

Thanks,
Haoqi

**Comment by Mathuran-Mang** [comment]
Thanks so much I will take a look at it!

**Comment by YuJiZhe** [comment]
> Thanks so much I will take a look at it!



> Is there anyway to use SlowFast to do real-time activity recognition using a webcam? I saw that @haooooooqi was working on a webcam demo, but I was not able to find the code for that demo anywhere.

Hey, friend.  Do u use the ''`SLOWFAST_8x8_R50.yaml`" in kinetics datasets of `Demo document` to demo?
