### ISSUE TITLE
Kinetics Dataset 

### ISSUE THREAD

**Issue by aandyjeon** [facebookresearch/SlowFast#43]
Hi, Nice code!
I am a student of Seoul National University in Korea.

Could you please share the Kinetics dataset?
I have a little bit of trouble downloading Kinetics dataset you introduced.
Because some of links of Youtube video disappeared :( 

Best,
Myeongho Jeon

**Comment by takatosp1** [comment]
Thanks for using the codease, you could find more details regarding to dataset downloading in [DATASET.md](slowfast/datasets/DATASET.md). You could also find some useful script under the [ActivityNet Repo](https://github.com/activitynet/ActivityNet/tree/master/Crawler/Kinetics).
