### ISSUE TITLE
error: Could not find suitable distribution for Requirement.parse('PIL')

### ISSUE THREAD

**Issue by Note-Liu** [facebookresearch/SlowFast#430]
when Build PySlowFast, an error message appears:

Searching for PIL
Reading https://pypi.org/simple/PIL/
No local packages or working download links found for PIL
error: Could not find suitable distribution for Requirement.parse('PIL')

How to solve this problem？

**Comment by Donny2333** [comment]
@Note-Liu I have then same question. Did u solve it?

**Comment by gqsmile** [comment]
Hello, I also met such a problem, how do you solve it?

**Comment by darkAlert** [comment]
I had the same error but solved it by removing PIL from install_requires in setup.py

**Comment by YaoFANGUK** [comment]
modify setup.py then change PIL to pillow
 <img src="https://z3.ax1x.com/2021/06/29/RUvBkV.png" >

**Comment by TerenceWang0727** [comment]
@YaoFANGUK Thank you this is very helpful, works for me

**Comment by 1040242795** [comment]
yeah,it work
