### ISSUE TITLE
AttributeError: module 'slowfast' has no attribute 'datasets'

### ISSUE THREAD

**Issue by Note-Liu** [facebookresearch/SlowFast#431]
import slowfast.datasets.transform as transform
AttributeError: module 'slowfast' has no attribute 'datasets'

**Comment by FightAllDays** [comment]
Hi, have you solved this problem?

**Comment by Note-Liu** [comment]
> Hi, have you solved this problem?


I haven't solved it yet.

**Comment by FightAllDays** [comment]
Sorry, I just saw this message. I still haven't been able to solve the problem
