### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd4 in position 1: invalid continuation byte

### ISSUE THREAD

**Issue by Note-Liu** [facebookresearch/SlowFast#432]
python3 tools/run_net.py  --cfg configs/Kinetics/SLOWFAST_8x8_R50.yaml DATA.PATH_TO_DATA_DIR /home/datasets/kinetics NUM_GPUS 4 TRAIN.BATCH_SIZE 16 TRAIN.CHECKPOINT_FILE_PATH /home/SlowFast-master/SLOWFAST_8x8_R50.pkl

the error:
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd4 in position 1: invalid continuation byte

**Comment by Rock-Roll** [comment]
How to solve this problem? I had the same doubts
