### ISSUE TITLE
RuntimeError: Failed to fetch video after 10 retries.

### ISSUE THREAD

**Issue by Note-Liu** [facebookresearch/SlowFast#438]
when i train x3d use：

--cfg configs/Kinetics/X3D_L.yaml

i meet an error:
Failed to decode by torchvision with exception: No such operator video_reader::probe_video_from_memory
RuntimeError: Failed to fetch video after 10 retries.

my train.csv format:
path1 label1
path2 label2
'''''

**Comment by voducman** [comment]
I got the same error, then I changed DECODING_BACKEND to "pyav" and it worked.

**Comment by Note-Liu** [comment]
> I got the same error, then I changed DECODING_BACKEND to "pyav" and it worked.

Thanks for you reply
