### ISSUE TITLE
RuntimeError: DataLoader worker (pid 26471) is killed by signal: Segmentation fault.

### ISSUE THREAD

**Issue by FightAllDays** [facebookresearch/SlowFast#442]
![企业微信截图_16251325524958](https://user-images.githubusercontent.com/22760089/124103388-d09e1200-da93-11eb-9115-3a78a89166dd.png)
When I was training, the above problem occurred, which was very confusing

**Comment by burgosmad** [comment]
Hello there, how did you solve this?
