### ISSUE TITLE
RuntimeError: DataLoader worker (pid 21196) is killed by signal: Killed.

### ISSUE THREAD

**Issue by Note-Liu** [facebookresearch/SlowFast#446]
when testing,I meet the bug

File "/usr/local/lib/python3/site-packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 21196) is killed by signal: Killed.

How to solve it?

**Comment by FightAllDays** [comment]
Hi~you could attempt change decode method torchvision to pyav~

**Comment by FightAllDays** [comment]
Maybe you could attempt change decode method torchvision to pyav

**Comment by vvolhejn** [comment]
@Note-Liu What was the solution?
