### ISSUE TITLE
RunTimeError: CUDA memory requirements

### ISSUE THREAD

**Issue by AGrosserHH** [facebookresearch/SlowFast#45]
Hi,

I have installed PySlowFast for Python 3.7 and I have got CUDA 10.0 installed.  I am now trying to run <br>
    python tools/run_net.py --cfg configs/Kinetics/c2/SLOWFAST_8x8_R50.yaml    DATA.PATH_TO_DATA_DIR ./files TEST.CHECKPOINT_FILE_PATH ./models/SLOWFAST_8x8_R50.pkl TRAIN.ENABLE False TEST.CHECKPOINT_TYPE caffe2 NUM_GPUS 1
<br>
and I am getting a CUDA out of memory error. My GPU card has got 6GB. I tried it as well at a GPU with 12GB and the same error occured. here is the error message: <br>
    RuntimeError: CUDA out of memory. Tried to allocate 300.00 MiB (GPU 0; 5.93 GiB total capacity; 4.99 GiB already allocated; 232.31 MiB free; 17.16 MiB cached)

Is there anything which I need to adapt?

Regards, Andi

**Comment by takatosp1** [comment]
Hi, thanks for using the codebase!
You can reduce the batchsize following the linear scaling rule.
