### ISSUE TITLE
[ERROR: decoder.py: 88]: mmco: unref short failure

### ISSUE THREAD

**Issue by vhvkhoa** [facebookresearch/SlowFast#46]
Thank you for the awesome work.

I was trying to run the run_net.py code to test the pretrained model after following the installation instruction. However, I ran into the error: 

```
[ERROR: decoder.py: 88]: mmco: unref short failure
Failed to decode with pyav with exception: 'av.container.input.InputContainer' object has no attribute 'close'
```

The command I used is:
```
python tools/run_net.py --cfg configs/Kinetics/c2/SLOWFAST_8x8_R50.yaml TEST.CHECKPOINT_FILE_PATH SLOWFAST_8x8_R50.pkl TRAIN.ENABLE False NUM_GPUS 1 TEST.CHECKPOINT_TYPE caffe2
```

After wandering around the internet, I have modified line 165 of decode.py to:
del container

Nevertheless, the error line ```[ERROR: decoder.py: 88]: mmco: unref short failure``` is still there and the code seems to be suspending there.

**Comment by takatosp1** [comment]
Hi, thanks for using the codebase!
Could you share 
1) what is the format of your video file
2) your ffmpeg version
3) you pyav version 

Thanks

**Comment by vhvkhoa** [comment]
Thank you for response to the issue promptly,

I intend to extract features from the ActivityNet dataset so most of the videos are mp4, some of them are mkv and webm.

I am using ffmpeg 4.0 and pyav 6.1.0.

**Comment by takatosp1** [comment]
Thanks you sharing your env. Could you share a screen shot of the error stack?
The logic of the code is that, if the video is too short (which is what the error about), then we just ignore the video and find the next one since we catch all the exceptions at decoder.py:206.

**Comment by vhvkhoa** [comment]
@takatosp1 I have tried to print the video names being processed during testing and I think it is okay to print those error logs because after printing them, the program still works with next videos.

However, I saw that the memory being used is too much (over 60GB of RAM) which made my server suspended and made me thought that it was because of the errors being showed in the console.
Can you have any information about this phenomenon ?
