### ISSUE TITLE
what's the pipeline about ava dataset

### ISSUE THREAD

**Issue by qingzew** [facebookresearch/SlowFast#5]

**Comment by takatosp1** [comment]
We will release the AVA pipeline soon.

**Comment by faheuer** [comment]
Any updates on AVA training or pretrained models?

**Comment by takatosp1** [comment]
Hey, thanks for using the codebase. AVA training pipeline and pretrain models has been released. Please feel free to have any follow up questions in this thread :P

**Comment by tonysy** [comment]
@takatosp1  Could you share the performance results of the given configurations in the ava experiments? Thanks a lot.
