### ISSUE TITLE
K600 training configs and pretrained models.

### ISSUE THREAD

**Issue by takatosp1** [facebookresearch/SlowFast#50]
Thanks for using the codebase, if you are looking for Kinetics 600 related recipes/ models (as #49), I will release it later.

**Comment by NLP-LH** [comment]
Thanks for your codebase. Is there a schedule for releasing?

**Comment by takatosp1** [comment]
Hi, thanks for using the codebase! I have released some K600 pretrain models.

**Comment by yushuinanrong** [comment]
@takatosp1 
It seems the pretrained model for kinetics600 is gone. Could you upload it again?

**Comment by zyx-cv** [comment]
is there a k600 pretrained model fror finetuning slowonly?
