### ISSUE TITLE
Improved MViTs

### ISSUE THREAD

**Issue by mmaaz60** [facebookresearch/SlowFast#502]
Hi,

I just wanted to check if you are planning to release the codes for the Improved MViT paper soon?

Thank You

**Comment by BIGBALLON** [comment]
There, the same issue for me.  
Is there any plan to release the Object Detection training code of the improved MViT ?

**Comment by mmaaz60** [comment]
Hi @kalyanvasudev,

Any plan of releasing the Improved MViT codebase? Thanks

**Comment by lyttonhao** [comment]
Yes, we have the plan to release the improved MViT. Please stay tuned!

**Comment by mmaaz60** [comment]
Hi @lyttonhao,

Any update on releasing Improved MViT training scripts and pretrained models? Thank You

**Comment by BIGBALLON** [comment]
HI, @lyttonhao, Is there any process on Improved MViT?

**Comment by mmaaz60** [comment]
HI @lyttonhao,

Any update on releasing improved-mvit code? Thanks

**Comment by mmaaz60** [comment]
https://github.com/facebookresearch/mvit
