### ISSUE TITLE
使用MVIT测试demo，加载权重时出现问题

### ISSUE THREAD

**Issue by Storyteler** [facebookresearch/SlowFast#524]
感谢您的分享，我在使用[MODEL_ZOO](https://github.com/facebookresearch/SlowFast/blob/main/MODEL_ZOO.md)中提供的k400.pyth时，可以加载部分权重，但有一部分无法加载，具体如下图所示，请问这是为什么。
![Kazam_screenshot_00005](https://user-images.githubusercontent.com/19318096/156132273-ee8b37cf-0cb6-4048-b3b4-795e99418b3f.png)

**Comment by Andy1621** [comment]
It seems that you use the wrong model `config.yaml` or model weights...

BTW, welcome to try our [UniFormer](https://github.com/Sense-X/UniFormer), we provide details to reproduce the results.

**Comment by Anirudh257** [comment]
@Storyteler Use my pullrequest: https://github.com/facebookresearch/SlowFast/pull/516
