### ISSUE TITLE
Script for counting flops

### ISSUE THREAD

**Issue by henrylee2570** [facebookresearch/SlowFast#53]
Hi, 

Thanks very much for releasing the code of this awesome work! --- Could you possibly also share the script for counting flops?

**Comment by takatosp1** [comment]
Hi @henrylee2570,

Thank you so much for using the codebase! We had a flop count in the codebase, but did not open source it since we are considering to have a more general version of FLOP counting in fvcore. You will find the code in the following updates soon.

**Comment by henrylee2570** [comment]
Thanks! Looking forward to the updates

**Comment by oLIVIa-Ld** [comment]
hah, I'm dealing with the same problem. looking forward to learn for calculating the FLOPs.

**Comment by takatosp1** [comment]
Thanks for waiting for the update! The flop count code has been landed. Please let me know if you need any thing :)

**Comment by henrylee2570** [comment]
Thanks very much!
