### ISSUE TITLE
Cannot Reproduce SSv2 Results for MViT

### ISSUE THREAD

**Issue by JunweiLiang** [facebookresearch/SlowFast#532]
Hi,

Thanks for the great work. In the paper, for SSv2 training, do the authors use MixUp and Rand Aug? Currently I'm getting 10 points worse than the reported numbers, with and without the regularizations. 

Thanks,
Junwei

**Comment by Andy1621** [comment]
Welcome to try our [UniFormer](https://github.com/Sense-X/UniFormer), we provide details to reproduce SOTA results for SSV2.
