### ISSUE TITLE
Issue: 'Failed to decode by pyav with exception: name 'gen_logmel' is not defined' in AVslowfast solution.

### ISSUE THREAD

**Issue by funhere** [facebookresearch/SlowFast#538]
Issue: 'Failed to decode by pyav with exception: name 'gen_logmel' is not defined' in AVslowfast solution.
File:  slowfast/datasets/decoder.py
No function 'gen_logmel'.
Could you please add this function? Thanks in advance
<img width="707" alt="image" src="https://user-images.githubusercontent.com/27839820/163928177-474af522-923a-4933-8b4a-a2dd7b8d8a28.png">
.

**Comment by funhere** [comment]
Find it in https://github.com/fanyix/SlowFast/blob/master/slowfast/datasets/decoder.py

**Comment by cc19860606** [comment]
![3a7bcfa9b2cc6de297bfcc58ce6954e](https://user-images.githubusercontent.com/81737024/224600818-179f8037-39f0-4d84-b805-893e03ef06a5.jpg)
I meet this problem, any suggestion for it?
