### ISSUE TITLE
Get TypeError in Windows

### ISSUE THREAD

**Issue by 121649982** [facebookresearch/SlowFast#55]
TypeError: _construct() missing 10 required positional arguments: 'dim_in', 'dim_out', 'stride', 'dim_inner', 'num_groups', 'trans_func_name', 'stride_1x1', 'inplace_relu', 'nonlocal_inds', and 'instantiation'

when i train this model on one gpu computer: 
python tools/run_net.py \
  --cfg configs/Kinetics/C2D_8x8_R50.yaml \
  DATA.PATH_TO_DATA_DIR path_to_your_dataset \
  NUM_GPUS 1 \
  TRAIN.BATCH_SIZE 16 \

I get this error:
           'CHECKPOINT_PERIOD': 1,
           'CHECKPOINT_TYPE': 'pytorch',
           'DATASET': 'kinetics',
           'ENABLE': True,
           'EVAL_PERIOD': 10}}
Traceback (most recent call last):
  File "D:/gc/SlowFast-master/tools/run_net.py", line 151, in <module>
    main()
  File "D:/gc/SlowFast-master/tools/run_net.py", line 127, in main
    train(cfg=cfg)
  File "D:\gc\SlowFast-master\tools\train_net.py", line 194, in train
    model = model_builder.build_model(cfg)
  File "D:\gc\SlowFast-master\slowfast\models\model_builder.py", line 34, in build_model
    model = _MODEL_TYPES[cfg.MODEL.ARCH](cfg)
  File "D:\gc\SlowFast-master\slowfast\models\video_model_builder.py", line 145, in __init__
    self._construct_network(cfg)
  File "D:\gc\SlowFast-master\slowfast\models\video_model_builder.py", line 210, in _construct_network
    trans_func_name=cfg.RESNET.TRANS_FUNC,
  File "D:\gc\SlowFast-master\slowfast\models\resnet_helper.py", line 390, in __init__
    super(ResStage, self).__init__()
  File "D:\Users\admin\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 72, in __init__
    self._construct()
TypeError: _construct() missing 10 required positional arguments: 'dim_in', 'dim_out', 'stride', 'dim_inner', 'num_groups', 'trans_func_name', 'stride_1x1', 'inplace_relu', 'nonlocal_inds', and 'instantiation'
how can I solve it? thank you！

**Comment by takatosp1** [comment]
Hi, Thanks for using the codebase! I am really happy to see that we can have a Windows user. It would be awesome if you can share some of your experience of installing PySlowFast!

Regarding to your issue, seems there is something wrong with your current  Windows python env or with your pytorch lib. If the env is correct, self._construct() in torch\nn\modules\module.py: 72 should not require these positional arguments. You might want to update (or reinstall) your python3 and your Pytorch 1.3.

I'll leave this issue open for a while to see if we can have any Windows expert to help.

**Comment by 121649982** [comment]
> Hi, Thanks for using the codebase! I am really happy to see that we can have a Windows user. It would be awesome if you can share some of your experience of installing/ using PySlowFast!
> 
> Regarding to your issue, seems there is something wrong with your current Windows python env or with your pytorch lib. If the env is correct, self._construct() in torch\nn\modules\module.py: 72 should not require these positional arguments. You might want to update (or reinstall) your python3 and your Pytorch 1.3.
> 
> I'll leave this issue open for a while to see if we can have any Windows expert to help.


Thanks so much for you reply ,this  error disappeared when I update my Pytorch version to 1.3.1

I install the env in windows as follows: 

1. install  PyTorch 1.3
   pip install torch===1.3.1 torchvision===0.4.2 -f https://download.pytorch.org/whl/torch_stable.html
2. fvcore:
    git clone https://github.com/facebookresearch/fvcore
    cd fvcore
    pip install .

3. pip install simplejson

4.PyAV: 
   conda install av -c conda-forge
5. ffmpeg
   pip install ffmpeg
6. PyYaml:
   pip install PyYaml
7. PySlowFast
   git clone https://github.com/facebookresearch/slowfast
   cd slowfast
   python setup.py build develop
