### ISSUE TITLE
Custom training with AVA 2.2 Dataset

### ISSUE THREAD

**Issue by rahul1728jha** [facebookresearch/SlowFast#552]
Custom training using the slowfast model on AVA 2.2 dataset.
-------------------------------------------------------------------------------------------------------------------------
### **ISSUE 1 :**

Pre trained model from : 
```
!wget https://dl.fbaipublicfiles.com/pytorchvideo/model_zoo/ava/SLOWFAST_8x8_R50_DETECTION.pyth
with pathmgr.open('SLOWFAST_8x8_R50_DETECTION.pyth', "rb") as f:
    checkpoint_1 = torch.load(f,encoding='latin-1')

```
The checkpointed model has the following keys:
	'epoch', 'model_state', 'optimizer_state', 'cfg'

```
len(checkpoint_1['optimizer_state']['param_groups'][0]['params']) -- > 220
len(checkpoint_1['optimizer_state']['param_groups'][1]['params']) -- > 112

```
`(list(checkpoint_1['model_state'].keys()))` --- > Following are some of the top layers

['detection_head.proj.weight',
 'detection_head.proj.bias',
 'model.blocks.0.multipathway_blocks.0.conv.weight',
 'model.blocks.0.multipathway_blocks.0.norm.weight',
 'model.blocks.0.multipathway_blocks.0.norm.bias',
]

However the model architecture that gets build have a different names of the layers. Some of them are :
(s1): VideoModelStem(
    (pathway0_stem): ResNetBasicStem(
      (conv): Conv3d(3, 64, kernel_size=[1, 7, 7], stride=[1, 2, 2], padding=[0, 3, 3], bias=False)
      (bn): BatchNorm3d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (pool_layer): MaxPool3d(kernel_size=[1, 3, 3], stride=[1, 2, 2], padding=[0, 1, 1], dilation=1, ceil_mode=False)
    )
    (pathway1_stem): ResNetBasicStem(
      (conv): Conv3d(3, 8, kernel_size=[5, 7, 7], stride=[1, 2, 2], padding=[2, 3, 3], bias=False)
      (bn): BatchNorm3d(8, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (pool_layer): MaxPool3d(kernel_size=[1, 3, 3], stride=[1, 2, 2], padding=[0, 1, 1], dilation=1, ceil_mode=False)
    )
  )
  (s1_fuse): FuseFastToSlow(
    (conv_f2s): Conv3d(8, 16, kernel_size=[7, 1, 1], stride=[4, 1, 1], padding=[3, 0, 0], bias=False)
    (bn): BatchNorm3d(16, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (relu): ReLU(inplace=True)
  )
  s1.pathway0_stem.conv,s1.pathway0_stem.bn 

_**ISSUE**_  
As a result of the mismatch between the checkpointed layers and the model architecture layers, the model weights are not loaded

-------------------------------------------------------------------------------------------------------------------------
### **ISSUE 2 :**

Pre trained model from : 
```
!wget https://dl.fbaipublicfiles.com/pyslowfast/model_zoo/ava/SLOWFAST_32x2_R101_50_50.pkl
with pathmgr.open('SLOWFAST_32x2_R101_50_50.pkl', "rb") as f:
    checkpoint_1 = torch.load(f,encoding='latin-1')

```
The checkpointed model has the following keys:
	'epoch', 'model_state', 'optimizer_state', 'cfg'

(list(checkpoint_1['model_state'].keys())) --- > Following are some of the top layers

['s1.pathway0_stem.conv.weight',
 's1.pathway0_stem.bn.weight',
 's1.pathway0_stem.bn.bias',
 's1.pathway0_stem.bn.running_mean',
 's1.pathway0_stem.bn.running_var',
 ]

Here the model architecture that gets build have a same names of the layers as the model weights are able to load. Some of them are :
(s1): VideoModelStem(
    (pathway0_stem): ResNetBasicStem(
      (conv): Conv3d(3, 64, kernel_size=[1, 7, 7], stride=[1, 2, 2], padding=[0, 3, 3], bias=False)
      (bn): BatchNorm3d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (pool_layer): MaxPool3d(kernel_size=[1, 3, 3], stride=[1, 2, 2], padding=[0, 1, 1], dilation=1, ceil_mode=False)
    )
    (pathway1_stem): ResNetBasicStem(
      (conv): Conv3d(3, 8, kernel_size=[5, 7, 7], stride=[1, 2, 2], padding=[2, 3, 3], bias=False)
      (bn): BatchNorm3d(8, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (pool_layer): MaxPool3d(kernel_size=[1, 3, 3], stride=[1, 2, 2], padding=[0, 1, 1], dilation=1, ceil_mode=False)
    )
  )
  (s1_fuse): FuseFastToSlow(
    (conv_f2s): Conv3d(8, 16, kernel_size=[7, 1, 1], stride=[4, 1, 1], padding=[3, 0, 0], bias=False)
    (bn): BatchNorm3d(16, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (relu): ReLU(inplace=True)
  )
  s1.pathway0_stem.conv,s1.pathway0_stem.bn 

**_ISSUE_**
`len(checkpoint_1['optimizer_state']['param_groups'][0]['params'])` -- > 430
`len(checkpoint_1['optimizer_state']['param_groups'][1]['params'])` -- > 238

The optimizer state that gets loaded as part of model architecure has different number of params :
bn 220, non bn 112, zero 0 no grad 0

So due to the difference (220 vs 430) and (112 vs 238) , the following error comes:
```
Traceback (most recent call last):
  File "tools/run_net.py", line 45, in <module>
    main()
  File "tools/run_net.py", line 26, in main
    launch_job(cfg=cfg, init_method=args.init_method, func=train)
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/darth/code/Users/rahul.jha/Activity-Recognition/SlowFast_Repo/slowfast/slowfast/utils/misc.py", line 311, in launch_job
    func(cfg=cfg)
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/darth/code/Users/rahul.jha/Activity-Recognition/SlowFast_Repo/slowfast/tools/train_net.py", line 614, in train
    checkpoint_epoch = cu.load_checkpoint(
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/darth/code/Users/rahul.jha/Activity-Recognition/SlowFast_Repo/slowfast/slowfast/utils/checkpoint.py", line 384, in load_checkpoint
    optimizer.load_state_dict(checkpoint["optimizer_state"])
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/torch/optim/optimizer.py", line 146, in load_state_dict
    raise ValueError("loaded state dict contains a parameter group "
ValueError: loaded state dict contains a parameter group that doesn't match the size of optimizer's group

```

-------------------------------------------------------------------------------

Can someone please help on how to fix the above issues. It seems like either of the model checkpoints has some inconsistencies with the model architecture that is being build

**Comment by donxy** [comment]
about ISSUE 1:
The keys of state_dict between two checkpoint files are different，but their architecture and value are same，I Successfully convert the Pre-trained model file to checkpoint file from pytorchvideo，use this script：
```
input = './checkpoints/SLOWFAST_32x2_R101_50_50.pkl'
path_save = './checkpoints/new.pyth'
    newmodel = {}
    checkpoint = torch.load(input, map_location="cuda")
    checkpoint_n = checkpoint
    state_dict = checkpoint["model_state"]
    for k in list(state_dict.keys()):
        old_k = k
        if "head" not in k:
            k = "model.blocks." + k

        step_dict = {'s1':0,'s2':1, 's3':2, 's4':3 ,'s5':4}
        for i,t in enumerate(step_dict):
            k = k.replace("model.blocks.{}".format(t), "model.blocks.{}".format(i))

        for t in [0, 1]:
            k = k.replace("pathway{}".format(t), "multipathway_blocks.{}.".format(t))

        for t in [0, 1, 2, 3, 4, 5]:
            k = k.replace("_res{}".format(t), "res_blocks.{}".format(t))

        k = k.replace(".conv_f2s.", ".conv_fast_to_slow.")

        k = k.replace(".branch1.".format(t), ".branch1_conv.".format(t))
        k = k.replace(".branch1_bn.".format(t), ".branch1_norm.".format(t))

        k = k.replace("_fuse", ".multipathway_fusion")
        k = k.replace("._stem.", ".")
        k = k.replace(".bn.", ".norm.")
        k = k.replace(".a.", ".conv_a.")
        k = k.replace(".b.", ".conv_b.")
        k = k.replace(".c.", ".conv_c.")
        k = k.replace(".a_bn.", ".norm_a.")
        k = k.replace(".b_bn.", ".norm_b.")
        k = k.replace(".c_bn.", ".norm_c.")


        k = k.replace("head.projection.weight", "detection_head.proj.weight")
        k = k.replace("head.projection.bias", "detection_head.proj.bias")
        # newmodel[k] = state_dict.pop(old_k).detach().numpy()
        newmodel[k] = state_dict.pop(old_k).detach()


    checkpoint_n["model_state"] = newmodel

    torch.save(checkpoint_n , path_save)
```

**Comment by rahul1728jha** [comment]
Thanks for the help working now.
