### ISSUE TITLE
terminate called after throwing an instance of 'std::bad_alloc'

### ISSUE THREAD

**Issue by Christinepan881** [facebookresearch/SlowFast#560]
Hi, is this library support to run on cluster? I just got the "std::bad_alloc" error when running the script on AWS Cluster:

**Terminate called after throwing an instance of 'std::bad_alloc'
what(): std::bad_alloc
/var/spool/slurmd/job82046/slurm_script: line 25: 27101 Aborted (core dumped) python tools/run_net.py --cfg configs/Kinetics/MVIT_B_16x4_CONV.yaml**

Can anyone help? Thanks!

**Comment by haooooooqi** [comment]
Hi
Thanks for playing with PySF
It seems to be an env issue. I bet you have fixed it :)
