### ISSUE TITLE
About AudioVisual SlowFast Model

### ISSUE THREAD

**Issue by ybkim95** [facebookresearch/SlowFast#567]
Hi, 

I'm currently planning to adopt AudioVisual SlowFast Model and the only related code that I found was create_audio_visual_slowfast.py. 

Since I'm quite new to this (I was using gluon cv, mxnet before), can you please guide me how to use your codes to finetune it with my own dataset? (I currently have videos and labels for these and willing to make my own audios from videos). 

Thank you.

**Comment by haooooooqi** [comment]
Hey 
Thanks for playing with PySlowFast!
There is a 2 year old code reference for avsf
https://github.com/facebookresearch/SlowFast/pull/219

Good luck with the legacy code
