### ISSUE TITLE
Error: too many values to unpack (expected 2) in Trainning SlowFast in K400

### ISSUE THREAD

**Issue by LEM0NTE** [facebookresearch/SlowFast#570]
But there was no such error during the testing phase
![image](https://user-images.githubusercontent.com/74885294/182005728-0f9d2cd9-20f9-40a7-85a0-11c5b8e9d721.png)

**Comment by haooooooqi** [comment]
Hey
Thanks for playing with PySlowFast!
Seems you modified the code since `random_crop` is in line of 157?

https://github.com/facebookresearch/SlowFast/blob/main/slowfast/datasets/utils.py#L157
