### ISSUE TITLE
Mapping from Kinetics categories to enum?

### ISSUE THREAD

**Issue by moscow25** [facebookresearch/SlowFast#58]
Hi, thank you for the library.

I can not find a mapping from category ("snorkeling") to int ID. Maybe the map exists, but is not mentioned in documentation. It would be good to use the pertained model, and know what category being predicted.

Similar, I am confused about examples for inference scripts. Thank you!

**Comment by takatosp1** [comment]
Hi,
Thank you for using the codebase! You can find the map from 
https://deepmind.com/research/open-source/kinetics

**Comment by moscow25** [comment]
Hi @takatosp1 -- of course I looked at the Kinetics dataset website.

I *assume* that the labels are in alphabetical order (aerobics == 0 and zumba == N-1) but this is not on their website (they provide named categories, not numerical one), and in any case may be different in your pretrained models. Could you please confirm my assumption. Would take you 1 second, or me much longer if incorrect. 

Yes, testing works well after I understood to edit the YAML to turn training off, get TESTING model version to CAFFE2, etc. And of course using a much smaller batch than 64...

For inference... if I have an uncategorized clip (not in Kinetics) do you have a script to just make a prediction and save Top1 and Top5 predictions? I assume not. Will write it, but wanted to be sure it's not there first. 

Thanks for putting this library out. I can image in it was a huge effort. It was a trill to see I can run inference of the SlowFast model on Amazon GPU 🙌

**Comment by takatosp1** [comment]
https://github.com/facebookresearch/video-nonlocal-net/blob/master/process_data/kinetics/classids.json
