### ISSUE TITLE
export PYTHONPATH=/path/to/PySlowFast/lib:$PYTHONPATH 怎么操作？

### ISSUE THREAD

**Issue by FHBGH** [facebookresearch/SlowFast#59]

**Comment by takatosp1** [comment]
Hi, thanks for using the codebase!
`/path/to/PySlowFast/lib` is the path to the codebase library folder.
Let's assume the path to your slowfast lib folder is `/path/to/PySlowFast/lib`, then you could run the following command in bash:
> export PYTHONPATH=/path/to/PySlowFast/lib:$PYTHONPATH

**Comment by FHBGH** [comment]
Thank you!


 

-------- 原始邮件 --------
发件人：Haoqi Fan <notifications@github.com>
时间：2019年12月19日 12:44
收件人：facebookresearch/SlowFast <SlowFast@noreply.github.com>
抄送：FHBGH <fanghongbinwy@163.com>,Author <author@noreply.github.com>
主题：Re: [facebookresearch/SlowFast] export PYTHONPATH=/path/to/PySlowFast/lib:$PYTHONPATH 怎么操作？ (#59)
