### ISSUE TITLE
confusion about the configuration in the paper ?

### ISSUE THREAD

**Issue by v-wewei** [facebookresearch/SlowFast#6]
hi, great work! 
But i just have some confusion about some details in the paper .
as the paper mentioned , SlowOnly res_101 and Slowfast res_101  was **fine tuned** on Charades Dataset with only single machine and the corresponding batch_size is 16.

1、does single machine refer to **single  gpu** ? or **4** or **8** gpu?
2、if single machine refer to 8 gpu, the total batch_size is **16** , right?
3、does the model fine tuned with precise_bn in your code ?

Thanks very much . Looking forward your reply !

**Comment by feichtenhofer** [comment]
Hi, thanks,

1) Single machine means one machine with 8 GPUs
2) The SGD batch size is 16, but BN stats are computed on 8 clips
3) Yes, precise BN is used

Hope that helps!

**Comment by v-wewei** [comment]
hi, Thanks for your reply, but how to compute BN stats with in 8 clips , since batch_size is 16. By default, i think BN stats are compute on each gpu which mean BN stats are computed on 2 clips in your case .
So, could you help to explain how can i calculate BN stats within 8 clips ?

**Comment by v-wewei** [comment]
did you use sync_bn for training ? Thanks
