### ISSUE TITLE
Question about bn_helper

### ISSUE THREAD

**Issue by ZJUwangdaiyin** [facebookresearch/SlowFast#60]
Very impressive work! Also very thankful for your kind code sharing!
I have a basic question about the code, which is specifically related with the codes between line56-60 in bn_helper:
if isinstance(inputs, (list,)):
    for i in range(len(inputs)):
        inputs[i] = inputs[i].float().cuda(non_blocking=True)
    else:
        inputs = inputs.cuda(non_blocking=True)

I'm not sure what's the purpose of the 'else' sentence. I will be appreciated if you could disabuse me.
Also, I'm looking forward to the action detection part of code, which you mentioned that you were going to release it soon. While is there any update since there has been a while?

**Comment by takatosp1** [comment]
Thank you for using the codebase!
The else is used for users who do not like use a list of tensor as inputs. If a user changed to use tensor as input, then the else will support cover that case and make the user's life easier.

For AVA, thanks for waiting, I worked on some other tasks and I have moved back to AVA. it will be release in the upcoming weeks. :P
