### ISSUE TITLE
Ask again for bn_helper

### ISSUE THREAD

**Issue by ZJUwangdaiyin** [facebookresearch/SlowFast#61]
Sorry to raise another issue. The original one is issue #60, which has been closed by you.
First of all, thank you so much for your quick reply and detailed explanation.
However, (it's my fault that I didn't express my question in detail), my point is the 'if' and 'else' sentences are not have the same indent, so I suspect that the 'else' sentence cannot work as you want.
Please check the code between line 56-60 in bn_helper.py for more details.

**Comment by takatosp1** [comment]
Hi, thanks for using the codebase and thank you for raising the issue.
You could go ahead to follow what we have in https://github.com/facebookresearch/SlowFast/blob/master/tools/train_net.py#L168
bn_helper.py has been deprecated and it is not used anywhere in the codebase, I'll remove it later. Current we are using the precise bn in fvcore.

**Comment by takatosp1** [comment]
BTW, feel free to reply or reopen the same issue if the topic is the same :P

**Comment by ZJUwangdaiyin** [comment]
Sorry, my bad. Thank you again for your kind and detailed explanation!
