### ISSUE TITLE
Why need to resize the video to the short edge size of 256

### ISSUE THREAD

**Issue by liuxuebo0** [facebookresearch/SlowFast#62]
In https://github.com/facebookresearch/SlowFast/blob/master/slowfast/datasets/DATASET.md , the step 2 shows "resize the video to the short edge size of 256" , and in the 'dataset/kinetics.py', the code randomly resize short side to [256, 320] , so why we need to resize the video manually before training ? Thanks.

**Comment by takatosp1** [comment]
Thanks for using the codebase!
The answer is very simple, scaling a 400x400 to 256 would take longer than scaling a 200x200 images.

**Comment by YuJiZhe** [comment]
how to resize the video to the short edge size of 256

**Comment by pvd0anh** [comment]
@YuJiZhe 
> scale='if(gt(ih\,iw)\,256\,trunc(oh*a/2)*2):if(gt(ih\,iw)\,trunc(ow/a/2)*2\,256)'

You can try this.

**Comment by ChenJoya** [comment]
> @YuJiZhe
> 
> > scale='if(gt(ih,iw),256,trunc(oh*a/2)*2):if(gt(ih,iw),trunc(ow/a/2)*2,256)'
> 
> You can try this.

Pretty good solution. One can resize a video as:
`ffmpeg -i AigCblw--hk_000067_000077.mp4 -vf "scale='if(gt(ih,iw),256,trunc(oh*a/2)*2):if(gt(ih,iw),trunc(ow/a/2)*2,256)'" output.mp4`

For multiple videos, one can perform (**please mkdir a videos_resized folder in prepath ../**):
`for f in *.mp4 ; do ffmpeg -i "$f" -vf "scale='if(gt(ih,iw),256,trunc(oh*a/2)*2):if(gt(ih,iw),trunc(ow/a/2)*2,256)'" "../videos_resized/$f" ;  done`


A case of resized video:
![](https://user-images.githubusercontent.com/20626415/135719221-bb6fdf14-d4e8-4fa0-88b2-30366990ef8b.png)
