### ISSUE TITLE
Code changed today; out of box does not run (import error)

### ISSUE THREAD

**Issue by moscow25** [facebookresearch/SlowFast#64]
Hi! Thanks again for the project.

It appears there was a major code update today, with no old history. After re-install, it seems now I can not run basic inference. Actually, code just fails on import statements.

Is it possible that checked in code does not link? There are not tests, but seems any basic `tools/*py` command is failing. It worked fine before the update.

Thanks!

```
~/open_source/SlowFast$ python tools/run_net.py --cfg configs/Kinetics/SLOWFAST_8x8_R50.yaml NUM_GPUS 1 TRAIN.ENABLE False  DATA.PATH_TO_DATA_DIR ~/data/Kinetics/kinetics-400_test/ TEST.CHECKPOINT_FILE_PATH ~/checkpoints/pretrained/model_zoo/SLOWFAST_8x8_R50.pkl TEST.CHECKPOINT_TYPE caffe2 TEST.BATCH_SIZE 4
Traceback (most recent call last):
  File "tools/run_net.py", line 14, in <module>
    from test_net import test
  File "/home/ubuntu/open_source/SlowFast/tools/test_net.py", line 13, in <module>
    from slowfast.datasets import loader
  File "/home/ubuntu/open_source/SlowFast/slowfast/datasets/__init__.py", line 6, in <module>
    from .kinetics import Kinetics  # noqa
  File "/home/ubuntu/open_source/SlowFast/slowfast/datasets/kinetics.py", line 9, in <module>
    import slowfast.datasets.decoder as decoder
AttributeError: module 'slowfast' has no attribute 'datasets'
```

**Comment by takatosp1** [comment]
Hi @moscow25!
Thanks again for stick with the codebase! I have updated some instructions at INSTALL.md and you might find more details on this. You might pull the latest code and find the updates. Long story short, we added a few more dependency (detectron2, opencv, and etc), and don't forget to update fvcore.
We will started to keep the commit stack, and adding more recent SOTA methods/ models to PySF.

**Comment by moscow25** [comment]
Thank you @takatosp1. I really enjoy this repo, and appreciate your diligence in making this usable for all of us. Most good work in this area, sadly, is not really possible to use because the code is not available, does not work or too confusing.

I definitely like the new methods and looking forward to getting 64-frame model working -- since I really think I need more than 32-frame pre-training for my problem...

New dependencies are no problem (I noticed and installed detectron2, opencv etc) -- no error there. Let me try installing from scratch again. 

I understand you'll have a commit log going forward soon. In project we've open sourced, also common to keep this from scratch couple of times in early version :-)

**Comment by moscow25** [comment]
Confirming that the latest code version builds and runs properly now. 

Thank you!

It would be amazing to eventually have a Git history for these updates. I understand that's more difficult for you. Maybe once things settle down? It's *really* hard to keep code running when everything is re-written on every push :-(

**Comment by moscow25** [comment]
Thank you again for the wonderful codebase. Without much complexity, I was able to adapt the Kinetics model to fine-tuning on a different problem. It worked very well. Looking forward to future updates, and to try one of the bigger models in your paper. Very much appreciated!
