### ISSUE TITLE
Is it acceptable to used mixed-precision for the backward pass of reversibility?

### ISSUE THREAD

**Issue by vedantroy** [facebookresearch/SlowFast#641]
I notice I can speed-up the training speed of my model 2x (at the price of a less stable loss curve), if I turned on `autocast` in the backwards pass of reversibility:

https://github.com/facebookresearch/SlowFast/blob/fcf407ec8252e66313f21aca782ff00b921e5071/slowfast/models/reversible_mvit.py#L562

Is this acceptable?

**Comment by karttikeya** [comment]
Hi, 

Thanks for interest in our work. 

The original experiments were not carried out with mixed precision but in the smaller follow-up setup, I have found mixed precision to work just as well.  Please see [mixed precision in minrev](https://github.com/karttikeya/minREV#-mixed-precision-training-).   

However, the mixed precision experiments were done on smaller models (depth = 6) and so if your find difficulty training larger models, please do report back and I will try to help.

**Comment by vedantroy** [comment]
Looking at minrev, it looks like AMP is enabled on forward pass only. Assuming that's the correct thing to do.
