### ISSUE TITLE
ValueError: invalid literal for int() with base 10: 'drumming'

### ISSUE THREAD

**Issue by Leozyc-waseda** [facebookresearch/SlowFast#647]
Thank you for your excellent work.
I want to test the performance of the model on K400 using SlowFast, and I have set up the environment and dataset according to the requirements of install.md and dataset.md. The generated test.csv file is as shown below.
![image](https://user-images.githubusercontent.com/52599722/236752546-3c10b688-6c96-42e7-b324-7818c78dcd9e.png)

I used this command, but got this error. I can't understand, maybe someone has encountered the same error?
```
(slowfast) pana-tat@panatat-4CXE:~/work/video_classification/SlowFast$ python tools/run_net.py   --cfg /home/pana-tat/work/video_classification/SlowFast/configs/Kinetics/SLOWFAST_8x8_R50.yaml   DATA.PATH_TO_DATA_DIR '/home/pana-tat/work/video_classification/SlowFast/test.csv'     TEST.CHECKPOINT_FILE_PATH '/home/pana-tat/work/video_classification/PySlowFast_Model_Zoo/SLOWFAST_8x8_R50.pkl' 
...
[05/09 00:35:49][INFO] checkpoint.py:  701: Unknown way of loading checkpoint. Using with random initialization, only for debugging.
[05/09 00:35:49][INFO] kinetics.py:   93: Constructing Kinetics test...
Traceback (most recent call last):
  File "/home/pana-tat/work/video_classification/SlowFast/tools/run_net.py", line 52, in <module>
    main()
  File "/home/pana-tat/work/video_classification/SlowFast/tools/run_net.py", line 37, in main
    launch_job(cfg=cfg, init_method=args.init_method, func=test)
  File "/home/pana-tat/work/video_classification/SlowFast/slowfast/utils/misc.py", line 430, in launch_job
    func(cfg=cfg)
  File "/home/pana-tat/work/video_classification/SlowFast/tools/test_net.py", line 218, in test
    test_loader = loader.construct_loader(cfg, "test")
  File "/home/pana-tat/work/video_classification/SlowFast/slowfast/datasets/loader.py", line 114, in construct_loader
    dataset = build_dataset(dataset_name, cfg, split)
  File "/home/pana-tat/work/video_classification/SlowFast/slowfast/datasets/build.py", line 31, in build_dataset
    return DATASET_REGISTRY.get(name)(cfg, split)
  File "/home/pana-tat/work/video_classification/SlowFast/slowfast/datasets/kinetics.py", line 94, in __init__
    self._construct_loader()
  File "/home/pana-tat/work/video_classification/SlowFast/slowfast/datasets/kinetics.py", line 150, in _construct_loader
    self._labels.append(int(label))
ValueError: invalid literal for int() with base 10: 'drumming'

```

**Comment by XinyangHan** [comment]
Hi! I encountered this as well!! May I ask how you solved it? Looks like the labels should be integers, but I am confused how to construct these labels.

**Comment by 42Viva** [comment]
> Thank you for your excellent work. I want to test the performance of the model on K400 using SlowFast, and I have set up the environment and dataset according to the requirements of install.md and dataset.md. The generated test.csv file is as shown below. ![image](https://user-images.githubusercontent.com/52599722/236752546-3c10b688-6c96-42e7-b324-7818c78dcd9e.png)
> 
> I used this command, but got this error. I can't understand, maybe someone has encountered the same error?
> 
> ```
> (slowfast) pana-tat@panatat-4CXE:~/work/video_classification/SlowFast$ python tools/run_net.py   --cfg /home/pana-tat/work/video_classification/SlowFast/configs/Kinetics/SLOWFAST_8x8_R50.yaml   DATA.PATH_TO_DATA_DIR '/home/pana-tat/work/video_classification/SlowFast/test.csv'     TEST.CHECKPOINT_FILE_PATH '/home/pana-tat/work/video_classification/PySlowFast_Model_Zoo/SLOWFAST_8x8_R50.pkl' 
> ...
> [05/09 00:35:49][INFO] checkpoint.py:  701: Unknown way of loading checkpoint. Using with random initialization, only for debugging.
> [05/09 00:35:49][INFO] kinetics.py:   93: Constructing Kinetics test...
> Traceback (most recent call last):
>   File "/home/pana-tat/work/video_classification/SlowFast/tools/run_net.py", line 52, in <module>
>     main()
>   File "/home/pana-tat/work/video_classification/SlowFast/tools/run_net.py", line 37, in main
>     launch_job(cfg=cfg, init_method=args.init_method, func=test)
>   File "/home/pana-tat/work/video_classification/SlowFast/slowfast/utils/misc.py", line 430, in launch_job
>     func(cfg=cfg)
>   File "/home/pana-tat/work/video_classification/SlowFast/tools/test_net.py", line 218, in test
>     test_loader = loader.construct_loader(cfg, "test")
>   File "/home/pana-tat/work/video_classification/SlowFast/slowfast/datasets/loader.py", line 114, in construct_loader
>     dataset = build_dataset(dataset_name, cfg, split)
>   File "/home/pana-tat/work/video_classification/SlowFast/slowfast/datasets/build.py", line 31, in build_dataset
>     return DATASET_REGISTRY.get(name)(cfg, split)
>   File "/home/pana-tat/work/video_classification/SlowFast/slowfast/datasets/kinetics.py", line 94, in __init__
>     self._construct_loader()
>   File "/home/pana-tat/work/video_classification/SlowFast/slowfast/datasets/kinetics.py", line 150, in _construct_loader
>     self._labels.append(int(label))
> ValueError: invalid literal for int() with base 10: 'drumming'
> ```

May i ask how did u solve that? i guess we should change the 'int(label)' into '(label)'?

**Comment by Leozyc-waseda** [comment]
https://github.com/facebookresearch/video-nonlocal-net/blob/main/process_data/kinetics/classids.json
I forgot how I did it, I probably wrote code to handle it. I replaced the test.csv and it needs to correspond with the above classids.json.
![image](https://github.com/facebookresearch/SlowFast/assets/52599722/e52d561b-6eb1-4662-aee9-c29076adf7fd)


```
import csv
import os
import json

# Function: Convert the format of test.csv to a new format
def generate_test_new_csv(test_csv_path, test_videos_dir, output_csv_path):
    video_label_mapping = {}
    with open(test_csv_path, mode='r') as csv_file:
        csv_reader = csv.reader(csv_file)
        next(csv_reader)  # Skip the header row
        for row in csv_reader:
            label_name, video_id, start_time, end_time, split, is_cc = row
            # Format start_time and end_time as 6-digit strings
            start_time_str = f"{int(start_time):06d}"
            end_time_str = f"{int(end_time):06d}"
            video_filename = f"{video_id}_{start_time_str}_{end_time_str}.mp4"
            video_label_mapping[video_filename] = label_name

    # Remove the last slash from test_videos_dir
    test_videos_dir = test_videos_dir.rstrip('/')

    with open(output_csv_path, mode='w') as output_csv_file:
        csv_writer = csv.writer(output_csv_file, delimiter=',', quotechar='"', quoting=csv.QUOTE_MINIMAL)
        for video_filename, label in video_label_mapping.items():
            video_path = os.path.join(test_videos_dir, video_filename)
            csv_writer.writerow([video_path, label])

# Function: Replace names with numbers based on classids.json
def replace_name_with_number(csv_path, classids_path):
    # Load classids.json
    with open(classids_path, "r") as f:
        classids = json.load(f)

    # Load csv
    with open(csv_path, "r") as csvfile:
        reader = csv.reader(csvfile)
        csv_data = list(reader)

    # Replace names with numbers
    for row in csv_data:
        for class_name, class_id in classids.items():
            if row[1] == class_name.strip('\"'):
                row[1] = class_id
                break

    # Write the replaced data back to csv
    with open(csv_path, "w", newline="") as csvfile:
        writer = csv.writer(csvfile)
        writer.writerows(csv_data)

    print("Replaced names in test.csv with numbers from classids.json and saved to test_new.csv.")

# Function: Check if video files in the folder actually exist
def filter_existing_videos(test_csv_path, output_csv_path, directory_path):
    with open(test_csv_path, 'r') as csvinput:
        with open(output_csv_path, 'w') as csvoutput:
            writer = csv.writer(csvoutput, delimiter=' ')
            reader = csv.reader(csvinput, delimiter=' ')

            for row in reader:
                mp4_file_path = row[0]
                relative_path = os.path.relpath(mp4_file_path, directory_path)
                if os.path.exists(os.path.join(directory_path, relative_path)):
                    writer.writerow(row)

    print(f"Filtered CSV saved to {output_csv_path}.")

# Main part of the code
if __name__ == '__main__':
    test_csv_path = '/home/pana-tat/work/video_classification/kinetics-dataset/k400/test.csv'
    test_videos_dir = '/home/pana-tat/work/video_classification/kinetics-dataset/k400/test'
    output_csv_path = '/home/pana-tat/work/video_classification/kinetics-dataset/k400/test_new.csv'
    classids_path = 'classids.json'

    # Convert the format of test.csv to a new format
    generate_test_new_csv(test_csv_path, test_videos_dir, output_csv_path)
    # Replace names with numbers based on classids.json
    replace_name_with_number(output_csv_path, classids_path)
    # Check if video files in the folder actually exist
    filter_existing_videos(output_csv_path, output_csv_path, test_videos_dir)

```

**Comment by burgosmad** [comment]
> > Thank you for your excellent work. I want to test the performance of the model on K400 using SlowFast, and I have set up the environment and dataset according to the requirements of install.md and dataset.md. The generated test.csv file is as shown below. ![image](https://user-images.githubusercontent.com/52599722/236752546-3c10b688-6c96-42e7-b324-7818c78dcd9e.png)
> > I used this command, but got this error. I can't understand, maybe someone has encountered the same error?
> > ```
> > (slowfast) pana-tat@panatat-4CXE:~/work/video_classification/SlowFast$ python tools/run_net.py   --cfg /home/pana-tat/work/video_classification/SlowFast/configs/Kinetics/SLOWFAST_8x8_R50.yaml   DATA.PATH_TO_DATA_DIR '/home/pana-tat/work/video_classification/SlowFast/test.csv'     TEST.CHECKPOINT_FILE_PATH '/home/pana-tat/work/video_classification/PySlowFast_Model_Zoo/SLOWFAST_8x8_R50.pkl' 
> > ...
> > [05/09 00:35:49][INFO] checkpoint.py:  701: Unknown way of loading checkpoint. Using with random initialization, only for debugging.
> > [05/09 00:35:49][INFO] kinetics.py:   93: Constructing Kinetics test...
> > Traceback (most recent call last):
> >   File "/home/pana-tat/work/video_classification/SlowFast/tools/run_net.py", line 52, in <module>
> >     main()
> >   File "/home/pana-tat/work/video_classification/SlowFast/tools/run_net.py", line 37, in main
> >     launch_job(cfg=cfg, init_method=args.init_method, func=test)
> >   File "/home/pana-tat/work/video_classification/SlowFast/slowfast/utils/misc.py", line 430, in launch_job
> >     func(cfg=cfg)
> >   File "/home/pana-tat/work/video_classification/SlowFast/tools/test_net.py", line 218, in test
> >     test_loader = loader.construct_loader(cfg, "test")
> >   File "/home/pana-tat/work/video_classification/SlowFast/slowfast/datasets/loader.py", line 114, in construct_loader
> >     dataset = build_dataset(dataset_name, cfg, split)
> >   File "/home/pana-tat/work/video_classification/SlowFast/slowfast/datasets/build.py", line 31, in build_dataset
> >     return DATASET_REGISTRY.get(name)(cfg, split)
> >   File "/home/pana-tat/work/video_classification/SlowFast/slowfast/datasets/kinetics.py", line 94, in __init__
> >     self._construct_loader()
> >   File "/home/pana-tat/work/video_classification/SlowFast/slowfast/datasets/kinetics.py", line 150, in _construct_loader
> >     self._labels.append(int(label))
> > ValueError: invalid literal for int() with base 10: 'drumming'
> > ```
> 
> May i ask how did u solve that? i guess we should change the 'int(label)' into '(label)'?

As I found that val.csv has labels with no label, it returns the error **ValueError: invalid literal for int() with base 10: '\n'**

I tried to  change the 'int(label)' into '(label)' but no, if I do that the problem becomes to **IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices**

**Comment by mumairhassan** [comment]
Hi,

I am also facing the same issue. Is there any solution to this?

```
File "/home/muhammad.u.hassan/code/SlowFast/slowfast/datasets/kinetics.py", line 143, in _construct_loader
    self._labels.append(int(label))
ValueError: invalid literal for int() with base 10: 'drumming,013SMb0SX8I,20,30,test,0'
```

**Comment by pepper725** [comment]
> Hi,
> 
> I am also facing the same issue. Is there any solution to this?
> 
> ```
> File "/home/muhammad.u.hassan/code/SlowFast/slowfast/datasets/kinetics.py", line 143, in _construct_loader
>     self._labels.append(int(label))
> ValueError: invalid literal for int() with base 10: 'drumming,013SMb0SX8I,20,30,test,0'
> ```

Have you solved the problem?

**Comment by tina908** [comment]
> Thank you for your excellent work. I want to test the performance of the model on K400 using SlowFast, and I have set up the environment and dataset according to the requirements of install.md and dataset.md. The generated test.csv file is as shown below. ![image](https://user-images.githubusercontent.com/52599722/236752546-3c10b688-6c96-42e7-b324-7818c78dcd9e.png)
> 
> I used this command, but got this error. I can't understand, maybe someone has encountered the same error?
> 
> ```
> (slowfast) pana-tat@panatat-4CXE:~/work/video_classification/SlowFast$ python tools/run_net.py   --cfg /home/pana-tat/work/video_classification/SlowFast/configs/Kinetics/SLOWFAST_8x8_R50.yaml   DATA.PATH_TO_DATA_DIR '/home/pana-tat/work/video_classification/SlowFast/test.csv'     TEST.CHECKPOINT_FILE_PATH '/home/pana-tat/work/video_classification/PySlowFast_Model_Zoo/SLOWFAST_8x8_R50.pkl' 
> ...
> [05/09 00:35:49][INFO] checkpoint.py:  701: Unknown way of loading checkpoint. Using with random initialization, only for debugging.
> [05/09 00:35:49][INFO] kinetics.py:   93: Constructing Kinetics test...
> Traceback (most recent call last):
>   File "/home/pana-tat/work/video_classification/SlowFast/tools/run_net.py", line 52, in <module>
>     main()
>   File "/home/pana-tat/work/video_classification/SlowFast/tools/run_net.py", line 37, in main
>     launch_job(cfg=cfg, init_method=args.init_method, func=test)
>   File "/home/pana-tat/work/video_classification/SlowFast/slowfast/utils/misc.py", line 430, in launch_job
>     func(cfg=cfg)
>   File "/home/pana-tat/work/video_classification/SlowFast/tools/test_net.py", line 218, in test
>     test_loader = loader.construct_loader(cfg, "test")
>   File "/home/pana-tat/work/video_classification/SlowFast/slowfast/datasets/loader.py", line 114, in construct_loader
>     dataset = build_dataset(dataset_name, cfg, split)
>   File "/home/pana-tat/work/video_classification/SlowFast/slowfast/datasets/build.py", line 31, in build_dataset
>     return DATASET_REGISTRY.get(name)(cfg, split)
>   File "/home/pana-tat/work/video_classification/SlowFast/slowfast/datasets/kinetics.py", line 94, in __init__
>     self._construct_loader()
>   File "/home/pana-tat/work/video_classification/SlowFast/slowfast/datasets/kinetics.py", line 150, in _construct_loader
>     self._labels.append(int(label))
> ValueError: invalid literal for int() with base 10: 'drumming'
> ```

May I ask how did you solve that?

**Comment by LSKhappychild** [comment]
@tina908 

I went thru the same problem, and found that there exists an extra csv file for mapping the literal label values into integer value (e.g. drumming -> 15). You can find it by googling some repositories regarding k400 dataset.

**Comment by tina908** [comment]
@LSKhappychild 

Thank you very much for your response. 
Could you please provide a more detailed explanation? I am a beginner and would greatly appreciate your guidance.

**Comment by LSKhappychild** [comment]
@tina908 

As the log says, casting 'label', which is a string like 'drumming', is causing the error. So converting each action label (drumming) into integer number is needed. 
Follow the link I attached, then as you can see in the first row, "abseiling" is converted to integer id 0. 
This kind of conversion is needed. 
It would be quite simple to make any type of script for id mapping.
