### ISSUE TITLE
按步骤搭建环境后运行预测提示没有找到slowfast模块

### ISSUE THREAD

**Issue by kola515** [facebookresearch/SlowFast#655]
运行python tools/run_net.py --cfg demo/AVA/SLOWFAST_32x2_R101_50_50.yaml 提示下面错误?
Traceback (most recent call last):
  File "/home/modelData/action/slowfast/tools/run_net.py", line 5, in <module>
    from slowfast.config.defaults import assert_and_infer_cfg
ModuleNotFoundError: No module named 'slowfast ？？

**Comment by BrianXiao1** [comment]
Just type `export PYTHONPATH=/path/to/SlowFast/slowfast:$PYTHONPATH` on terminal

**Comment by wjw0905** [comment]
> export PYTHONPATH=/path/to/SlowFast/slowfast:$PYTHONPATH

thanks
