### ISSUE TITLE
Module 'slowfast.datasets.transform' has no 'lighting' memberpylint(no-member)

### ISSUE THREAD

**Issue by anhminh3105** [facebookresearch/SlowFast#67]
pylint on my vscode showed it, I tried to find the lighting() function in transform.py but there isn't really such function defined. Could you help check it out? I'm still downloading the dataset though so I haven't run to test it yet.
![image](https://user-images.githubusercontent.com/18170028/71620080-74251280-2bd0-11ea-8e8a-78265c2d110a.png)

**Comment by takatosp1** [comment]
Hi, thanks for working on the great demo @anhminh3105!
We provided two sets of transforms, on is using pytorch as "backend", and another is using cv2 as backend. For ava we are using cv2 as backend, you should able to find the `lighting_list` at `slowfast/datasets/cv2_transform.py`. I'll also provide the corresponding functions in pytorch if you want to using AVA on "pytorch backend".

**Comment by anhminh3105** [comment]
Thanks, that'd be great to test out.

Also found you fixed that line that I doubted. (y)

**Comment by takatosp1** [comment]
Thanks again for contributing to PySlowFast!!!
