### ISSUE TITLE
whats the meaning of output from terminal?

### ISSUE THREAD

**Issue by Leozyc-waseda** [facebookresearch/SlowFast#677]
training done: _p33.65_f12.65 _t0.08_m2.88 _a63.51 Top5 Acc: 100.00 MEM: 2.88 f: 12.6452

**Comment by ythu2** [comment]
It displays the number of model parameters, FLOPs, median training epoch time, memory usage, top-1 accuracy, and top-5 accuracy.

See the below line for details
https://github.com/facebookresearch/SlowFast/blob/6092dad7be32bb1d6b71fe1bade258dc8b492fe3/tools/train_net.py#L761C5-L775C6

**Comment by Leozyc-waseda** [comment]
@ythu2 
Thank you very much ! :)
