### ISSUE TITLE
Demo not working: 'utf-8' codec can't decode byte 0x9e in position 0: invalid start byte

### ISSUE THREAD

**Issue by bilel-bj** [facebookresearch/SlowFast#69]
I run the test example but it failed in loading the checkpoint which I downloaded from the model zoo.
I run this command 

`python tools/run_net.py --cfg configs/AVA/c2/SLOWFAST_32x2_R101_50_50.yaml DATA.PATH_TO_DATA_DIR ./data/  TEST.CHECKPOINT_FILE_PATH  ./configs/AVA/c2/SLOWFAST_32x2_R101_50_50.pkl TRAIN.ENABLE False `

I got this error
```
Traceback (most recent call last):
  File "tools/run_net.py", line 152, in <module>
    main()
  File "tools/run_net.py", line 147, in main
    test(cfg=cfg)
  File "/home/bilel/1-demos/SlowFast/tools/test_net.py", line 138, in test
    convert_from_caffe2=cfg.TEST.CHECKPOINT_TYPE == "caffe2",
  File "/home/bilel/1-demos/SlowFast/slowfast/utils/checkpoint.py", line 220, in load_checkpoint
    checkpoint = torch.load(path_to_checkpoint, map_location="cpu")
  File "/home/bilel/anaconda3/envs/env_pytorch/lib/python3.6/site-packages/torch/serialization.py", line 426, in load
    return _load(f, map_location, pickle_module, **pickle_load_args)
  File "/home/bilel/anaconda3/envs/env_pytorch/lib/python3.6/site-packages/torch/serialization.py", line 603, in _load
    magic_number = pickle_module.load(f, **pickle_load_args)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x9e in position 0: invalid start byte

```

**Comment by takatosp1** [comment]
Hi, thanks for using the pretrain model!
You must downloaded the model from a wrong column. 
Here is an example you could follow:

| architecture | depth | Pretrain Model |  frame length x sample rate  | MAP | AVA version | model |
| ------------- | ------------- | ------------- | ------------- | ------------- | ------------- |------------- |
| SlowOnly | R50 | [Kinetics 400](https://dl.fbaipublicfiles.com/pyslowfast/model_zoo/ava/pretrain/C2D_8x8_R50.pkl) | 4 x 16 | 19.5 | 2.2 | [`link`](https://dl.fbaipublicfiles.com/pyslowfast/model_zoo/ava/C2D_8x8_R50.pkl) |
| SlowFast | R101 | [Kinetics 600]


The `Kinetics 400` or `Kinetics 600` **Pretrain Model** on the left is the model trained on Kinetics dataset, and you could use it to finetune on AVA. The `link` on the right is the model trained (or finetuned) on AVA. 

If you want to run the test script, you should get the model from the right side.

**Comment by bilel-bj** [comment]
Thanks a lot for your kind reply!!
I downloaded the specified file and the error remains. Could be because the file is not Caffe2 originally.

This what I typed:
`python tools/run_net.py --cfg configs/AVA/c2/C2D_8x8_R50.yaml DATA.PATH_TO_DATA_DIR ./data/  TEST.CHECKPOINT_FILE_PATH  ./configs/AVA/c2/C2D_8x8_R50.pkl TRAIN.ENABLE False NUM_GPUS 1`

This is what I get:
```
Traceback (most recent call last):
  File "tools/run_net.py", line 152, in <module>
    main()
  File "tools/run_net.py", line 147, in main
    test(cfg=cfg)
  File "/home/bilel/1-demos/SlowFast/tools/test_net.py", line 138, in test
    convert_from_caffe2=cfg.TEST.CHECKPOINT_TYPE == "caffe2",
  File "/home/bilel/1-demos/SlowFast/slowfast/utils/checkpoint.py", line 220, in load_checkpoint
    checkpoint = torch.load(path_to_checkpoint, map_location="cpu")
  File "/home/bilel/anaconda3/envs/env_pytorch/lib/python3.6/site-packages/torch/serialization.py", line 426, in load
    return _load(f, map_location, pickle_module, **pickle_load_args)
  File "/home/bilel/anaconda3/envs/env_pytorch/lib/python3.6/site-packages/torch/serialization.py", line 603, in _load
    magic_number = pickle_module.load(f, **pickle_load_args)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xed in position 0: invalid continuation byte

```

**Comment by takatosp1** [comment]
Hi, thanks for the follow up. 
Seems you are not using the config in the yaml precisely, there are two solution to make it straight:

1) You should able to find these in the config yaml I shared:
"""
TRAIN:
  # CHECKPOINT_FILE_PATH: path to pretrain model
  CHECKPOINT_TYPE: caffe2
"""
Where I have already set the `CHECKPOINT_TYPE` to `caffe2`.
You could go ahead to fill the `CHECKPOINT_FILE_PATH` as `./configs/AVA/c2/C2D_8x8_R50.pkl`.

2) If you want to go with `TEST.CHECKPOINT_FILE_PATH`, then remember don't forget to set `TEST.CHECKPOINT_TYPE` to `caffe2`.

**Comment by bilel-bj** [comment]
Thanks again for your kind reply!! really useful

**Comment by takatosp1** [comment]
Hey @bilel-bj, thank you for interested in PySlowFast and I really appreciated that! Feel free to let me know if you need any other help! 

Regarding to the demo you raised in two other threads, I am expecting to release the demo in ~2 weeks. Let me know if you need any other features/ functions.

**Comment by YuJiZhe** [comment]
> Hey @bilel-bj, thank you for interested in PySlowFast and I really appreciated that! Feel free to let me know if you need any other help!
> 
> Regarding to the demo you raised in two other threads, I am expecting to release the demo in ~2 weeks.
> 
> Feel free to let me know if you need any other features/ functions.

hi, friend! Can I add you a wechat to talk about this slowfast program? I need your help, please!~
