### ISSUE TITLE
Testing On SLOWFAST_4x16_R50.yaml Model

### ISSUE THREAD

**Issue by Israrulhaq190** [facebookresearch/SlowFast#7]
I have single GPU in my machine and trying to run it by modifying the cfg to 1 GPU instead of 8 GPUs.
Also i have downloaded the weights and placed inside the checkpoints folder.
SLOWFAST_4x16_R50.pkl

Everything is compile successfully but when i run:
python tools/run_net.py --cfg configs/Kinetics/SLOWFAST_4x16_R50.yaml

This is what i get

raise NotImplementedError("Unknown way to load checkpoint.")
NotImplementedError: Unknown way to load checkpoint.

**Comment by takatosp1** [comment]
Thanks for using the code. 
You have downloaded the pretrained parameter and passed the config to the testing pipeline, which is great! Then you only have one last thing need to do before the actual testing:
In order to let the pipeline know where do you store the pretrained file, you need to pass the path to the pretrain file in the config by setting up the CHECKPOINT_FILE_PATH.

https://github.com/facebookresearch/SlowFast/blob/eb6c6a94240cda9df45ceaebefc9c2a81c688a58/tools/test_net.py#L95

**Comment by Israrulhaq190** [comment]
> Thanks for using the code.
> You have downloaded the pretrained parameter and passed the config to the testing pipeline, which is great! Then you only have one last thing need to do before the actual testing:
> In order to let the pipeline know where do you store the pretrained file, you need to pass the path to the pretrain file in the config by setting up the CHECKPOINT_FILE_PATH.
> 
> https://github.com/facebookresearch/SlowFast/blob/eb6c6a94240cda9df45ceaebefc9c2a81c688a58/tools/test_net.py#L95

Thanks, I have resolved this issue. Now i am about to test the model but i think there is format issues of test.csv file which i am using.

Below is the csv file i am using as test. Please check the format.
youtube_id | time_start | time_end | split
-- | -- | -- | --
--6bJUbfpnQA1:AMJ1 | 17 | 27 | test
--8YXc8iCt8 | 2 | 12 | test
--coBvtS-eQ | 57 | 67 | test
--q6ElFyVq0 | 148 | 158 | test
--q_mvQ8zP8 | 67 | 77 | test
--qlUJAiVkg | 0 | 10 | test
--sYD7KnbOk | 276 | 286 | test
--swPW3U9EE | 247 | 257 | test
--xD8NX4lxQ | 18 | 28 | test
-08En2aQklI | 233 | 243 | test

When i test it says:
File slowfast/datasets/kinetics.py", line 90, in _construct_loader
assert len(path_label.split()) == 2
AssertionError


I have also added the prefix video path as well as test.csv file path in default.py

**Comment by takatosp1** [comment]
Hi,
Thanks for the follow up! 
You need to follow the instruction in the activity net repo to clip the video to 10 s clips. Then you can follow our instruction in the dataset.md to prepare the format as 
‘’’
path_to_video label
‘’’
Meanwhile, I’ll talk to the legal team regarding to the issue that whether we can share the script for converting the video data to make your life easier.

**Comment by tonysy** [comment]
Hi, I want to know  whether  the label is  the contiguous id of the class(e.g, [0, 1, 2, ....,399])? Thanks a lot
