### ISSUE TITLE
Demo not working

### ISSUE THREAD

**Issue by bilel-bj** [facebookresearch/SlowFast#70]
Could you please see my reply to this issue:

https://github.com/facebookresearch/SlowFast/issues/69#issuecomment-570041985

**Comment by takatosp1** [comment]
Hi, thank you for using the codebase!
Long story short, you were using a wrong (or at least not completely correct) config in #69 
I have share all the details you need to follow in the original thread, please feel free to go ahead and check it there. 

Also thanks for opening a new issue as a kind reminder. I would love to share it here that I would get an email notice if anyone replied in any issue, no matter whether it is opened or closed. So you can simply reply in any of the thread (without additional reminder), and I will get back to it as soon as I possibly can. If you worry that I will miss a closed issue, feel free to reopen it :P. 

Thanks again for using PySlowFast and I really appreciate your enthusiasm.

**Comment by bilel-bj** [comment]
Thanks a lot for your kind reply!! Really impressive
