### ISSUE TITLE
Running demo on webcam

### ISSUE THREAD

**Issue by bilel-bj** [facebookresearch/SlowFast#71]
Could you please share with us the code related to running the SlowFast on the wecam?

**Comment by takatosp1** [comment]
Hi @bilel-bj, thanks for the follow up on the demo! You could go ahead to check #34, where @anhminh3105 has implemented a cool demo on webcam for video/ action classification. I'll using #34 to track the progress on webcam demo, and expecting to release it in ~2 weeks (need to prioritize different tasks). I'll label this issue as duplicate and will share all the updates at #34.

**Comment by bilel-bj** [comment]
Thanks a lot for your kind reply!!
