### ISSUE TITLE
Where can I download official label files?

### ISSUE THREAD

**Issue by LSKhappychild** [facebookresearch/SlowFast#715]
Thank you for your great work!
I referred to the DATASET.md to prepare the kinetics dataset, but I could not find label files with the intended format in the attached repo.

I assume the intended format of label is
{path to video}, label (as int)
but what I see in the attached repo is quite different. 

Where can I download official label csv files?

Thanks

**Comment by shezwad** [comment]
I used these ones. 
[kinetic.json](https://github.com/user-attachments/files/16462632/kinetic.json)
[label_map.txt](https://github.com/user-attachments/files/16462633/label_map.txt)

**Comment by LSKhappychild** [comment]
Thanks!
