### ISSUE TITLE
Slow training speed

### ISSUE THREAD

**Issue by adwardlee** [facebookresearch/SlowFast#73]
Hi @takatosp1 ,

Thanks for sharing the code. Is it normal that one epoch cost almost one day to finish for kinetics dataset? cfg is SLOWFAST_8x8_R50.yaml, 8 gpus and 4 num_workers are used. 

Another question is that resizing the short side of videos to 256 is recommended in `DATASET.md`, while the default jitter scales ranges from 256 to 320. It means the video may be enlarged sometimes?

Thanks,

**Comment by takatosp1** [comment]
Hi, thanks for using PySlowFast!
The training speed depends on your machine, the three main factors on machine side are CPU, GPU, and I/O speed, the three main factors on training side are video original scale, model input scale, and model capacity. For example, if you did not descale the video during preprocessing, it will takes you much longer when you decide the video (I guess that’s partially the reason you see a low training speed if you did not do it.)

Normally it takes me 5-7 days to train a model on single machine with 8 GPUs. Please do remember to rescale the video and it will give you a sweet speed gain. Beside of that, one common issue is to check your I/O speed, more specifically the speed of reading your videos. You may also play with the number of workers to make a fully utilization of your cpu.

**Comment by adwardlee** [comment]
Hi, thanks for your reply. 
To my knowledge, it could harm the final accuracy to rescale from low resolution to high. Why descaling the video to 256 while it would be upscaled to higher resolution in [](https://github.com/facebookresearch/SlowFast/blob/master/slowfast/datasets/kinetics.py#L200) ? Thanks.
