### ISSUE TITLE
Demo for camera input

### ISSUE THREAD

**Issue by ss24cs** [facebookresearch/SlowFast#83]
Hi, buddy, I got some error for this demo:
here my problems:
(torch) stelo@stelo-Z390-GAMING-X:~/experiments/SlowFast-master/SlowFast_0109$ python tools/run_net.py --predict_source 0 --cfg configs/Kinetics/c2/SLOWFAST_8x8_R50.yaml
[INFO: test_net.py:   86]: Test with config:
[INFO: test_net.py:   87]: BN:
  EPSILON: 1e-05
  MOMENTUM: 0.1
  NUM_BATCHES_PRECISE: 200
  USE_PRECISE_STATS: True
  WEIGHT_DECAY: 0.0
DATA:
  CROP_SIZE: 224
  INPUT_CHANNEL_NUM: [3, 3]
  MEAN: [0.45, 0.45, 0.45]
  NUM_FRAMES: 32
  PATH_PREFIX: 
  PATH_TO_DATA_DIR: 
  SAMPLING_RATE: 2
  STD: [0.225, 0.225, 0.225]
  TEST_CROP_SIZE: 256
  TRAIN_CROP_SIZE: 224
  TRAIN_JITTER_SCALES: [256, 320]
DATA_LOADER:
  ENABLE_MULTI_THREAD_DECODE: False
  NUM_WORKERS: 8
  PIN_MEMORY: True
DIST_BACKEND: nccl
LOG_PERIOD: 10
MODEL:
  ARCH: slowfast
  DROPOUT_RATE: 0.5
  FC_INIT_STD: 0.01
  LOSS_FUNC: cross_entropy
  MULTI_PATHWAY_ARCH: ['slowfast']
  NUM_CLASSES: 400
  SINGLE_PATHWAY_ARCH: ['c2d', 'i3d', 'slowonly']
NONLOCAL:
  GROUP: [[1, 1], [1, 1], [1, 1], [1, 1]]
  INSTANTIATION: dot_product
  LOCATION: [[[], []], [[], []], [[], []], [[], []]]
NUM_GPUS: 1
NUM_SHARDS: 1
OUTPUT_DIR: .
PREDICT:
  ENABLE: True
  LABEL_FILE_PATH: ./configs/Kinetics/demo/kinetics_400_labels.csv
  SOURCE: 0
RESNET:
  DEPTH: 50
  INPLACE_RELU: True
  NUM_BLOCK_TEMP_KERNEL: [[3, 3], [4, 4], [6, 6], [3, 3]]
  NUM_GROUPS: 1
  STRIDE_1X1: False
  TRANS_FUNC: bottleneck_transform
  WIDTH_PER_GROUP: 64
  ZERO_INIT_FINAL_BN: True
RNG_SEED: 0
SHARD_ID: 0
SLOWFAST:
  ALPHA: 4
  BETA_INV: 8
  FUSION_CONV_CHANNEL_RATIO: 2
  FUSION_KERNEL_SZ: 7
SOLVER:
  BASE_LR: 0.1
  DAMPENING: 0.0
  GAMMA: 0.1
  LRS: []
  LR_POLICY: cosine
  MAX_EPOCH: 196
  MOMENTUM: 0.9
  NESTEROV: True
  OPTIMIZING_METHOD: sgd
  STEPS: []
  STEP_SIZE: 1
  WARMUP_EPOCHS: 34
  WARMUP_FACTOR: 0.1
  WARMUP_START_LR: 0.01
  WEIGHT_DECAY: 0.0001
TEST:
  BATCH_SIZE: 64
  CHECKPOINT_FILE_PATH: ./checkpoints/SLOWFAST_8x8_R50.pkl
  CHECKPOINT_TYPE: caffe2
  DATASET: kinetics
  ENABLE: True
  NUM_ENSEMBLE_VIEWS: 10
  NUM_SPATIAL_CROPS: 3
TRAIN:
  AUTO_RESUME: True
  BATCH_SIZE: 64
  CHECKPOINT_FILE_PATH: 
  CHECKPOINT_INFLATE: False
  CHECKPOINT_PERIOD: 1
  CHECKPOINT_TYPE: caffe2
  DATASET: kinetics
  ENABLE: False
  EVAL_PERIOD: 10
Traceback (most recent call last):
  File "tools/run_net.py", line 178, in <module>
    main()
  File "tools/run_net.py", line 156, in main
    test(cfg=cfg)
  File "/home/stelo/experiments/SlowFast-master/SlowFast_0109/tools/test_net.py", line 90, in test
    model = model_builder.build_model(cfg)
  File "/home/stelo/experiments/SlowFast-master/slowfast/models/model_builder.py", line 34, in build_model
    model = _MODEL_TYPES[cfg.MODEL.ARCH](cfg)
  File "/home/stelo/experiments/SlowFast-master/slowfast/models/video_model_builder.py", line 144, in __init__
    self.enable_detection = cfg.DETECTION.ENABLE
  File "/home/stelo/anaconda3/envs/torch/lib/python3.7/site-packages/yacs/config.py", line 141, in __getattr__
    raise AttributeError(name)
AttributeError: DETECTION
This attribute error could you help analysis the root problem? And how to fix it?

**Comment by takatosp1** [comment]
Hi, thank you so much for playing with PySlowFast!
Could you please kindly enough remind me the source of your code? (since I haven't release the camera demo for PySlowFast yet) xD.

**Comment by takatosp1** [comment]
I'll share the update of the demo in #34 :P

**Comment by ss24cs** [comment]
https://github.com/anhminh3105/SlowFast.git
This source of my code, I had viewed this issue "Demo programme on camera input #34" and got above question.
