### ISSUE TITLE
Running error

### ISSUE THREAD

**Issue by yangsusanyang** [facebookresearch/SlowFast#85]
Dear author,

I am trying to evaluate your algorithm performance on ava data sets using command line "python tools/run_net.py --cfg configs/AVA/c2/SLOWFAST_64x2_R101_50_50.yaml DATA.PATH_TO_DATA_DIR data/ava/ TEST.CHECKPOINT_FILE_PATH model/SLOWFAST_64x2_R101_50_50.pkl TRAIN.ENABLE False NUM_GPUS 1". I got the following error,

Traceback (most recent call last):
  File "tools/run_net.py", line 152, in <module>
    main()
  File "tools/run_net.py", line 147, in main
    test(cfg=cfg)
  File "/media/workspace_karl/slowfast/tools/test_net.py", line 138, in test
    convert_from_caffe2=cfg.TEST.CHECKPOINT_TYPE == "caffe2",
  File "/media/workspace_karl/slowfast/slowfast/utils/checkpoint.py", line 186, in load_checkpoint
    caffe2_checkpoint = pickle.load(f, encoding="latin1")
_pickle.UnpicklingError: unpickling stack underflow

I wonder if you could point out what is going wrong. 

Many Thanks!

**Comment by takatosp1** [comment]
Hi, thanks for playing with AVA!
I had an update the link of this model a few hours ago, currently it’s a pytorch model. Could you change the checkpoint type from caffe2 to pytorch and try it again? 

I’ll have a following diff to update the yaml.

**Comment by yangsusanyang** [comment]
Thanks for your fast reply!
Want to clarify with you first: I re-downloaded the model pkl file of "SLOWFAST_64x2_R101_50_50.pkl" from "https://github.com/facebookresearch/SlowFast/blob/master/MODEL_ZOO.md". I changed the  checkpoint type from caffe2 to pytorch in file "SLOWFAST_64x2_R101_50_50.yaml". 

When I rerun the command, and this time I got error of 
"Traceback (most recent call last):
  File "tools/run_net.py", line 152, in <module>
    main()
  File "tools/run_net.py", line 147, in main
    test(cfg=cfg)
  File "/media/workspace_karl/slowfast/tools/test_net.py", line 138, in test
    convert_from_caffe2=cfg.TEST.CHECKPOINT_TYPE == "caffe2",
  File "/media/workspace_karl/slowfast/slowfast/utils/checkpoint.py", line 189, in load_checkpoint
    for key in caffe2_checkpoint["blobs"].keys():
TypeError: 'int' object is not subscriptable
"

Please help.

Thanks  a lot

**Comment by takatosp1** [comment]
Hi thanks for the follow up!
I feel you did not put the CHECKPOINT_TYPE at the right place. If you look into your error message, your convert_from_caffe2 is still True. It is suppose to be False when you load a pytorch model.

If you set TEST.CHECKPOINT_FILE_PATH to the path to your checkpoint, you should also set TEST.CHECKPOINT_TYPE to pytorch (or caffe2 depends on your case).

**Comment by yangsusanyang** [comment]
Thank you very much for your quick response. 
I tried both 
caffe2 (python tools/run_net.py --cfg configs/AVA/c2/SLOWFAST_64x2_R101_50_50_pytroch.yaml DATA.PATH_TO_DATA_DIR data/ava/ TEST.CHECKPOINT_FILE_PATH model/SLOWFAST_64x2_R101_50_50.pkl TRAIN.ENABLE False NUM_GPUS 1 TEST.CHECKPOINT_TYPE caffe2>mylog4) 
and 
pytorch  (python tools/run_net.py --cfg configs/AVA/c2/SLOWFAST_64x2_R101_50_50_pytroch.yaml DATA.PATH_TO_DATA_DIR data/ava/ TEST.CHECKPOINT_FILE_PATH model/SLOWFAST_64x2_R101_50_50.pkl TRAIN.ENABLE False NUM_GPUS 1 TEST.CHECKPOINT_TYPE pytorch>mylog3),
but I got the same error below
" 
Traceback (most recent call last):
  File "tools/run_net.py", line 152, in <module>
    main()
  File "tools/run_net.py", line 147, in main
    test(cfg=cfg)
  File "/media/workspace_karl/slowfast/tools/test_net.py", line 138, in test
    convert_from_caffe2=cfg.TEST.CHECKPOINT_TYPE == "caffe2",
  File "/media/workspace_karl/slowfast/slowfast/utils/checkpoint.py", line 189, in load_checkpoint
    for key in caffe2_checkpoint["blobs"].keys():
TypeError: 'int' object is not subscriptable
"

Attached please find the 2 log files.


[mylog.zip](https://github.com/facebookresearch/SlowFast/files/4047739/mylog.zip)

Thank you for your time!

**Comment by takatosp1** [comment]
Thanks for the kind follow up and using PySlowFast!

It is a little big strange that I can not reproduce the issue you reported.
Could you run
```
md5sum model/SLOWFAST_64x2_R101_50_50.pk
```
and share me the hash?

**Comment by takatosp1** [comment]
Also if you read the code, if you have checkpoint type as 'pytorch', you would not jump to `slowfast/slowfast/utils/checkpoint.py", line 189`, becuase `slowfast/utils/checkpoint.py", line 189` will be `convert_from_caffe2 == False`.

**Comment by yangsusanyang** [comment]
Thanks very much for your kind reply! 
Yes, the error is strange. I did not do anything else on purpose.  Attached is md5sum result. 
I will double check if the versions of other software match your requirement.
[md5sum.txt](https://github.com/facebookresearch/SlowFast/files/4059586/md5sum.txt)

**Comment by yangsusanyang** [comment]
A nice day to you.

I verified all software version: no problem.

I modified SLOWFAST_64x2_R101_50_50.yaml file to update the annotation_dir,  FRAME_DIR, and FRAME_LIST_DIR, CHECKPOINT_TYPE, and NUM_GPUS as shown below with the rest contents in the original file no changed:
AVA:
  ANNOTATION_DIR: data/AVA/annotations/
  FRAME_DIR: data/AVA/frames/
  FRAME_LIST_DIR: data/AVA/annotations/
  TEST_PREDICT_BOX_LISTS: ["person_box_67091280_iou90/ava_detection_val_boxes_and_labels.csv"]
TEST:
  CHECKPOINT_TYPE: pytorch  
NUM_GPUS: 1

Then I am able to bypass the previous error. But I encounter the following errors:

Traceback (most recent call last):
  File "tools/run_net.py", line 158, in <module>
    main()
  File "tools/run_net.py", line 153, in main
    test(cfg=cfg)
  File "/media/workspace_karl/slowfast/tools/test_net.py", line 187, in test
    perform_test(test_loader, model, test_meter, cfg)
  File "/media/workspace_karl/slowfast/tools/test_net.py", line 65, in perform_test
    preds = model(inputs, meta["boxes"])
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/media/workspace_karl/slowfast/slowfast/models/video_model_builder.py", line 372, in forward
    x = self.head(x, bboxes)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/media/workspace_karl/slowfast/slowfast/models/head_helper.py", line 119, in forward
    out = roi_align(out, bboxes)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/media/workspace_karl/detectron2_repo/detectron2/layers/roi_align.py", line 95, in forward
    input, rois, self.output_size, self.spatial_scale, self.sampling_ratio, self.aligned
  File "/media/workspace_karl/detectron2_repo/detectron2/layers/roi_align.py", line 20, in forward
    input, roi, spatial_scale, output_size[0], output_size[1], sampling_ratio, aligned
**_RuntimeError: Not compiled with GPU support (ROIAlign_forward at /media/workspace_karl/detectron2_repo/detectron2/layers/csrc/ROIAlign/ROIAlign.h:73)_**
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x47 (0x7f29e96c5687 in /opt/conda/lib/python3.6/site-packages/torch/lib/libc10.so)
frame #1: detectron2::ROIAlign_forward(at::Tensor const&, at::Tensor const&, float, int, int, int, bool) + 0x16a (0x7f29c145667a in /media/workspace_karl/detectron2_repo/detectron2/_C.cpython-36m-x86_64-linux-gnu.so)
frame #2: <unknown function> + 0x202fa (0x7f29c14662fa in /media/workspace_karl/detectron2_repo/detectron2/_C.cpython-36m-x86_64-linux-gnu.so)
frame #3: <unknown function> + 0x203fe (0x7f29c14663fe in /media/workspace_karl/detectron2_repo/detectron2/_C.cpython-36m-x86_64-linux-gnu.so)
frame #4: <unknown function> + 0x1aca0 (0x7f29c1460ca0 in /media/workspace_karl/detectron2_repo/detectron2/_C.cpython-36m-x86_64-linux-gnu.so)
<omitting python frames>
frame #11: THPFunction_apply(_object*, _object*) + 0x9ff (0x7f2a1d6f1acf in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_python.so)


I guess the error is coming from detectron2. Wonder if it is easy for you to point our the possible error source.

Thanks very much.

**Comment by yangsusanyang** [comment]
I searched the issue and found some similar issue opened here: https://github.com/facebookresearch/detectron2/issues/267

Do you think it is because my cuda version is too latest? Which version do you suggest?


The following is my NVIDIA video card information:

NVRM version: NVIDIA UNIX x86_64 Kernel Module  418.39  Sat Feb  9 19:19:37 CST 2019
GCC version:  gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.11)

+-----------------------------------------------------------------------------+
| NVIDIA-SMI 418.39       Driver Version: 418.39       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce RTX 2080    Off  | 00000000:65:00.0  On |                  N/A |
|  0%   37C    P8     1W / 215W |     61MiB /  7951MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
+-----------------------------------------------------------------------------+

**Comment by john2020-210** [comment]
@yangsusanyang Have you solved the problem ? I met the same problem and my environment is also cuda version 10.1 pytorch1.4

**Comment by 3210448723** [comment]
哈哈，纯小白，我看的这个[视频讲解](https://www.bilibili.com/video/BV1su4y1Q7n3?t=248.6&p=13)，但是也遇到了同样问题
