### ISSUE TITLE
why do we need Detectron2

### ISSUE THREAD

**Issue by iotbeg** [facebookresearch/SlowFast#86]
I had forked the previous 'commit' of the code repo, which did not have Detectron2. While I am trying to download Detectron2, I am getting a long error. 

I would like to know why is Detectron2 required esp. since the paper doesn't mention object detection(or atleast what I infer) and what part of code is it used in?

**Comment by takatosp1** [comment]
Hi, thanks for using PySlowFast!
If you check what we have in the [demo gif](https://github.com/facebookresearch/SlowFast/blob/master/demo/ava_demo.gif), you will find that PySlowFast supports action detection, which means the codebase needs detection components. (at least RoIAlignment).
We had a long debate on whether we shall depends on Detectron2, or other more light weight libraries with detection components. What I've been found is that Detectron2 is not that hard to install so we moved with Detectron2. 
Could you share me what is the error you got to install Detectron2? On one hand, I can try to help you fix your install error for Detectron2, and on the other hand, if many people complaining about install Detectron2, we could also move to depends on other libraries, or have the RoI layers in PySlowFast directly.

Looking forward to see the feedbacks from all the users who are straggling install Detectron2.

**Comment by salmaShahid** [comment]
`C:\Users\LeNoVo` T430\AppData\Local\Programs\Python\Python36\slowfast>python setup.py build develop
running build
running build_py
running develop
running egg_info
writing slowfast.egg-info\PKG-INFO
writing dependency_links to slowfast.egg-info\dependency_links.txt
writing requirements to slowfast.egg-info\requires.txt
writing top-level names to slowfast.egg-info\top_level.txt
reading manifest file 'slowfast.egg-info\SOURCES.txt'
writing manifest file 'slowfast.egg-info\SOURCES.txt'
running build_ext
Creating c:\users\lenovo t430\appdata\local\programs\python\python36\lib\site-packages\slowfast.egg-link (link to .)
slowfast 1.0 is already the active version in easy-install.pth

Installed c:\users\lenovo t430\appdata\local\programs\python\python36\slowfast
Processing dependencies for slowfast==1.0
Searching for detectron2
Reading https://pypi.org/simple/detectron2/
Couldn't find index page for 'detectron2' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.org/simple/
No local packages or working download links found for detectron2
error: Could not find suitable distribution for Requirement.parse('detectron2')

> 

Sir i found this error while running your code inside slowfast folder
`python setup.py build develop`

kindly help me over this problem...

**Comment by iotbeg** [comment]
@salmaShahid maybe because you haven't downloaded Detectron2? There is an install readme with instructions to do so.

@takatosp1 Thank you for your answer. I am currently trying to 'overfit' the network for a small subset of Kinetics dataset so I am assuming I won't need it because I am trying to perform Action Recognition. Having said that, the error while downloading Detectron2 is VERY long (too long to copy-paste) but I have a feeling it might have something to do with gcc compilers so I will look into it again and will report back.


Thank you

**Comment by ppwwyyxx** [comment]
Actually you need to remove "detectron2" from setup.py (there is a PR for it), and install it following its [instructions](https://github.com/facebookresearch/detectron2/blob/master/INSTALL.md) instead.

**Comment by takatosp1** [comment]
Looks like there are not many people had trouble to install Detectron2 (at least it was pretty straightforward to install from my side).

I'm closing the issue then.

**Comment by luwanglin** [comment]
so I also encounted this problem ,

ERROR: Command errored out with exit status 128: git clone -q https://github.com/cocodataset/cocoapi.git /tmp/pip-req-build-7blorgvs Check the logs for full command output.

**Comment by onlyonewater** [comment]
Hi,@luwanglin ,I had the same  problem,did you solve it?
