### ISSUE TITLE
LINK : fatal error LNK1181: cannot open input file 'swresample.lib'

### ISSUE THREAD

**Issue by salmaShahid** [facebookresearch/SlowFast#89]
Sir while running code this error occur 
![error](https://user-images.githubusercontent.com/51890862/72203564-fc3bcf80-348e-11ea-936a-d8f6410d814c.PNG)

plz help me over this problem...
i already installed the build tools of Microsoft Visual cpp 14 and set path in environment variables 
but this error occur again and again kindly guide me...

**Comment by takatosp1** [comment]
Hi
Thanks a lot for playing with PySlowFast! Seems this is caused by some py av decoder linking issue.
You might able to follow what #55 do to install PySlowFast in windows.

Feel free to share your update here :P
