### ISSUE TITLE
How to prepare the kinetics dataset, does it need extract frame? and how to train this code on UCF dataset

### ISSUE THREAD

**Issue by JoseponLee** [facebookresearch/SlowFast#90]
The dataset.md didn't make clear how to prepara the kinetics dataset, does  it need extract frame? or just like no-local repo which is using lmdb, extract frame on the fly. I noticed that no-local repo provide a copy of kinetics, dose it ok I direct use that. and the structure of file is just like AVA dataset or it's different.
By the way, does anyone knows that how to change the code and train it on UCF dataset. because I don't have much GPU, it's hard for me to train on kinetics dataset....

**Comment by JoseponLee** [comment]
Maybe I can check it on datasets/kinetics.py

**Comment by gtgtgt1117** [comment]
> Maybe I can check it on datasets/kinetics.py, and write a script for UCF could work

Hi,could you share your code with me ?

**Comment by JoseponLee** [comment]
actually, I train it on UCF and Kinetics, but it did't get a good result, maybe because of the hyperparameter.

**Comment by gtgtgt1117** [comment]
> actually, I train it on UCF and Kinetics, but it did't get a good result, maybe because of the hyperparameter.

Thank you for your reply! This is my email 18801046982@163.com
