### ISSUE TITLE
How much time to train SlowFast on kinetics-400

### ISSUE THREAD

**Issue by huangjun12** [facebookresearch/SlowFast#91]

**Comment by takatosp1** [comment]
Hi 

Thanks for playing with PySlowFast 📦 
Normally you would spent ~5-7 days to train a SlowFast model on K400 dataset for ~200 epochs with 8GPUs. 
You will get a good speed up by using multiple machines as well.

**Comment by ShijianXu** [comment]
Hi, @takatosp1 
I tried to train a resnet3d-18 on kinetics-400 with 8 gpus. I found that the gpu utilities drop to 0% and then clime up to 100% periodically. I think this might be a signal that the dataloader can not catch up with the speed of gpus. Besides, I did some modifications to kinetics.py, making it sample two frames from each video (however duo to my poor modification, it seems that it requires decoding the video twice).

In my estimation, it will takes about 20+ days to train the network, which is too long. May I ask what is suggested settings for multiple gpu training on kinetics-400, like num_workers, batch_size, etc. Besides, will the decoding be a bottleneck for speeding up the training?

Thanks a lot.

**Comment by takatosp1** [comment]
Hi, @ShijianXu  
Thanks for playing with PySlowFast. May I know your machine configuration?
More specifically what is the I/O speed, what is the CPU, and how many cores do you have for your CPU.
In general, 20+ sounds crazy and I think there must be something wrong with the config, you should able to play with different config and speed it up significantly. The simplest way is to play with the number_workers and the decoder backend to find the optimal config for your machine. In the meanwhile, please make sure your video is properly rescaled (check the pre-processing doc).

**Comment by ShijianXu** [comment]
Thanks for your reply. It has 88 processors with the following information: 

> ......
processor       : 87
vendor_id       : GenuineIntel
cpu family      : 6
model           : 79
model name      : Intel(R) Xeon(R) CPU E5-2699 v4 @ 2.20GHz
stepping        : 1
microcode       : 0xb00001b
cpu MHz         : 2201.000
cache size      : 56320 KB
physical id     : 1
siblings        : 44
core id         : 28
cpu cores       : 22
apicid          : 121
initial apicid  : 121
fpu             : yes
fpu_exception   : yes
cpuid level     : 20
wp              : yes
......

I am not sure about the I/O speed. I think maybe I need to change my modification to decode the video only once each time.

**Comment by takatosp1** [comment]
Thank CPU looks good, and you should able to decode it much faster (at least 2x) if there is nothing else wrong. 

BTW, could you please clarify what do you meant by `decode the video only once each time`?

**Comment by ShijianXu** [comment]
Actually, I am writing some codes based on partial codes of slowfast, which requires sampling two clips from a video. I modified the `kinetics.py` in slowfast. But I think my modification is poor since it decodes the same video twice. Maybe this is the bottleneck.
