### ISSUE TITLE
Error for downloading AVA v2.2

### ISSUE THREAD

**Issue by CHALLENGER9200** [facebookresearch/SlowFast#92]
I download AVA v2.1 successfully with the following command line:
```
DATA_DIR="../../data/ava/videos"

if [[ ! -d "${DATA_DIR}" ]]; then
  echo "${DATA_DIR} doesn't exist. Creating it.";
  mkdir -p ${DATA_DIR}
fi

wget https://s3.amazonaws.com/ava-dataset/annotations/ava_file_names_trainval_v2.1.txt

for line in $(cat ava_file_names_trainval_v2.1.txt)
do
  wget https://s3.amazonaws.com/ava-dataset/trainval/$line -P ${DATA_DIR}
done
```

However, when I replace `v2.1` with `v2.2`, I get an error:
```
cat: ava_file_names_trainval_v2.2.txt: No such file or directory
```

It seems that `https://s3.amazonaws.com/ava-dataset/annotations/ava_file_names_trainval_v2.2.txt` is not exist. Could you please help me?

**Comment by takatosp1** [comment]
Hi, @CHALLENGER9200 
If you check the end of the [DATASET.md](https://github.com/facebookresearch/SlowFast/blob/master/slowfast/datasets/DATASET.md), you will find we have provided a link for all the post processed annotations.
