### ISSUE TITLE
Some problem when I install detectron2

### ISSUE THREAD

**Issue by luwanglin** [facebookresearch/SlowFast#93]
pip install -U 'git+https://github.com/facebookresearch/fvcore.git' 'git+https://github.com/cocodataset/cocoapi.git#subdirectory=PythonAPI'
Collecting git+https://github.com/facebookresearch/fvcore.git
  Cloning https://github.com/facebookresearch/fvcore.git to /tmp/pip-req-build-n6ta7s6m
  Running command git clone -q https://github.com/facebookresearch/fvcore.git /tmp/pip-req-build-n6ta7s6m
Collecting git+https://github.com/cocodataset/cocoapi.git#subdirectory=PythonAPI
  Cloning https://github.com/cocodataset/cocoapi.git to /tmp/pip-req-build-7blorgvs
  Running command git clone -q https://github.com/cocodataset/cocoapi.git /tmp/pip-req-build-7blorgvs
  error: RPC failed; curl 56 GnuTLS recv error (-54): Error in the pull function.
  fatal: The remote end hung up unexpectedly
  fatal: 过早的文件结束符（EOF）
  fatal: index-pack failed
ERROR: Command errored out with exit status 128: git clone -q https://github.com/cocodataset/cocoapi.git /tmp/pip-req-build-7blorgvs Check the logs for full command output.

**Comment by onlyonewater** [comment]
when I use the command pip install 'git+https://github.com/facebookresearch/fvcore' to install fvcore, I met the error:
ERROR: Command errored out with exit status 128: git clone -q https://github.com/facebookresearch/fvcore /tmp/pip-req-build-_q4h91d0 Check the logs for full command output. 
What's the reason?I am confused..
My environment is Python 3.7.0, pytorch 1.4.0.

**Comment by hansdom** [comment]
> when I use the command pip install 'git+https://github.com/facebookresearch/fvcore' to install fvcore, I met the error:
> ERROR: Command errored out with exit status 128: git clone -q https://github.com/facebookresearch/fvcore /tmp/pip-req-build-_q4h91d0 Check the logs for full command output.
> What's the reason?I am confused..
> My environment is Python 3.7.0, pytorch 1.4.0.

I met the same problem, did you solve it?

**Comment by hansdom** [comment]
> pip install -U 'git+https://github.com/facebookresearch/fvcore.git' 'git+https://github.com/cocodataset/cocoapi.git#subdirectory=PythonAPI'
> Collecting git+https://github.com/facebookresearch/fvcore.git
> Cloning https://github.com/facebookresearch/fvcore.git to /tmp/pip-req-build-n6ta7s6m
> Running command git clone -q https://github.com/facebookresearch/fvcore.git /tmp/pip-req-build-n6ta7s6m
> Collecting git+https://github.com/cocodataset/cocoapi.git#subdirectory=PythonAPI
> Cloning https://github.com/cocodataset/cocoapi.git to /tmp/pip-req-build-7blorgvs
> Running command git clone -q https://github.com/cocodataset/cocoapi.git /tmp/pip-req-build-7blorgvs
> error: RPC failed; curl 56 GnuTLS recv error (-54): Error in the pull function.
> fatal: The remote end hung up unexpectedly
> fatal: 过早的文件结束符（EOF）
> fatal: index-pack failed
> ERROR: Command errored out with exit status 128: git clone -q https://github.com/cocodataset/cocoapi.git /tmp/pip-req-build-7blorgvs Check the logs for full command output.

I met the same problem, did you solve it?
