### ISSUE TITLE
Improvement in accuracy of doing person-level instead of scene-level classification?

### ISSUE THREAD

**Issue by anuar12** [facebookresearch/SlowFast#97]
Thanks for releasing AVA code and model!

So one can do scene-level "Kinetics-style" classification or person-level "AVA-style" classification. Would you expect an increase in accuracy moving from scene-level to person-level excluding those situations where multiple people in the scene are doing different actions? I would imagine person-level recognition provides more supervision in terms of localization and additional per-person class label but is it that important?

**Comment by takatosp1** [comment]
Hi @anuar12,

Thanks for playing with PySlowFast and sharing your question. 
By "increasing accuracy", could you clarify a bit what task/ dataset were you referring to?
I feel it depends on the dataset we are playing with. For AVA, we might see more distinct actions from different people, but for Kinetics, the dataset is designed to have multiple people perform similar actions in the same video.
