### ISSUE TITLE
Possibly incorrect C2D pretrained model

### ISSUE THREAD

**Issue by henrylee2570** [facebookresearch/SlowFast#98]
Hi, thanks for the great work! I think the provided C2D model pre-trained on Kinetics might be incorrect, could you kindly help and check that?

I got `UnpicklingError: invalid load key, '\x1f'.` when loading it via pickle; I could get I3D and I3D NLN models when treating the `C2D_NOPOOL_8x8_R50.pkl` as a tar and untar it.

Thanks very much!

**Comment by tonysy** [comment]
same error

**Comment by anuar12** [comment]
try changing CHECKPOINT_TYPE to `caffe2`

**Comment by henrylee2570** [comment]
@anuar12 It was a pickle error, which is a step in caffe2 checkpoint loading

**Comment by takatosp1** [comment]
Hi,
Thanks for playing with PySlowFast!
As @anuar12 mentioned, could you please set the checkpoint type to caffe2 when you load a caffe2 pretrained model?

Thanks and looking forward to see your updates :)
